<section class="content">
    
    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <?php
        $form = $this->form;

        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class='form-group'>
            <label for='username'>Nome de usuário</label>
            <?php
            echo $this->formRow($form->get('user_name')
                            ->setAttribute('class', 'form-control')
            );
            ?>
        </div>

        <div class='form-group'>
            <label for='username'>Senha</label>
            <?php
            echo $this->formRow($form->get('user_password')
                            ->setAttribute('class', 'form-control')
            );
            ?>
        </div>


        <div class='form-group'>
            <label for='password'>Confirmação de senha</label>
            <?php
            echo $this->formRow($form->get('user_password_confirm')
                            ->setAttribute('class', 'form-control')
            );
            ?>
        </div>
        <div class='form-group'>
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>