<div class="container-fluid">
    <h1>Welcome to User's Controller Index!</h1>

    <?php echo $this->message; ?>
    <hr>

    <div class="table-responsive">
        <table class='table'>
            <thead>
                <tr>
                    <th>#</th>
                        <th>Username</th>
                        <th>Password</th>
                        <th>Password Salt</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Registration Date</th>
                    <th>Roles</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->users as $user): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($user->getUserId()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getUserName()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getUserPassword()); ?></td>
                            <td><?php echo $this->escapeHtml($user->getUserPasswordSalt()); ?></td>
                        <td><?php echo $this->escapeHtml($user->getUserEmail()); ?></td>
                        <td><?php echo $user->getUserActive() ? 'TRUE' : 'FALSE'; ?></td>
                        <td><?php
                            echo $this->escapeHtml($user->getUserRegistrationDate()
                                            ->format('d/m/Y'));
                            ?></td>
                        <td>
                            <ul class='list-group'>
                                <?php foreach ($user->getRole()->toArray() as $role): ?>
                                    <li class='list-group-item'><?php echo $this->escapeHtml($role->getRoleName()); ?></li>
                                    <?php endforeach; ?>
                            </ul>
                        </td>
                            <td><a  href='<?php echo $this->url('authentication/default', array('controller' => 'user', 'action' => 'edit', 'id' => $user->getUserId())); ?>'>Edit</a></td>
                            <td><a  href='<?php echo $this->url('authentication/default', array('controller' => 'user', 'action' => 'delete', 'id' => $user->getUserId())); ?>'>Delete</a></td>                        
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>