<section class="content">
    <?php echo $this->message; ?>
    <hr>

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="table-responsive">
                <table id="userTable" class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Registration Date</th>
                            <th>Username</th>
                            <th>Active</th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->users as $user): ?>
                            <tr class="cats-row" data-id="<?php echo $user->getUserId(); ?>">
                                <td><?php echo $this->escapeHtml($user->getUserId()); ?></td>
                                <td>
                                    <?php
                                    echo $this->escapeHtml($user->getUserRegistrationDate()
                                            ->format('d/m/Y'));
                                    ?>
                                </td>  
                                <td><?php echo $this->escapeHtml($user->getUserName()); ?></td>
                                <td><?php echo $user->getUserActive() ? 'TRUE' : 'FALSE'; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/authentication/user/user';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>
