<section class="content">
    
    <div class="col-xs-12 col-md-10 col-md-offset-1">
        <table class="table table-bordered table-striped" id="contact-table">
            <thead>
                <th>Identificação</th>
                <th>Relação</th>
                <th>Assunto</th>
                <th>Mensagem</th>
            </thead>
            <tbody>
                <?php foreach ($contacts as $contact) : ?>
                    <tr>
                        <td>
                            <span class="text-bold">Nome: </span> <?php echo $contact->getName(); ?>
                            <br>
                            <span class="text-bold">Email: </span> <?php echo $contact->getEmail(); ?>
                        </td>
                        <td><?php echo Site\Entity\Contact::POSITIONS_DESCRIPTION[$contact->getPosition()]; ?></td>
                        <td><?php echo $contact->getSubject(); ?></td>
                        <td><?php echo $contact->getMessage(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/site/site-management/contact';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>