<?php

namespace DoctrineORMModule\Proxy\__CG__\SchoolManagement\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StudentClass extends \SchoolManagement\Entity\StudentClass implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classId', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classBeginDate', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classEndDate', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'className', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'enrollments');
        }

        return array('__isInitialized__', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classId', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classBeginDate', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'classEndDate', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'className', '' . "\0" . 'SchoolManagement\\Entity\\StudentClass' . "\0" . 'enrollments');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StudentClass $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getClassId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClassId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassId', array());

        return parent::getClassId();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassBeginDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassBeginDate', array());

        return parent::getClassBeginDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassEndDate', array());

        return parent::getClassEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName', array());

        return parent::getClassName();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassBeginDate(\DateTime $classBeginDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassBeginDate', array($classBeginDate));

        return parent::setClassBeginDate($classBeginDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setClassEndDate(\DateTime $classEndDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassEndDate', array($classEndDate));

        return parent::setClassEndDate($classEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setClassName($className)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassName', array($className));

        return parent::setClassName($className);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrollments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrollments', array());

        return parent::getEnrollments();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnrollments(\Doctrine\Common\Collections\Collection $enrollments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnrollments', array($enrollments));

        return parent::setEnrollments($enrollments);
    }

    /**
     * {@inheritDoc}
     */
    public function addEnrollment(\SchoolManagement\Entity\Enrollment $enrollment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnrollment', array($enrollment));

        return parent::addEnrollment($enrollment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEnrollment(\SchoolManagement\Entity\Enrollment $enrollment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEnrollment', array($enrollment));

        return parent::removeEnrollment($enrollment);
    }

}
