<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \Recruitment\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressId', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressPostalCode', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressCountry', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressState', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressCity', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressNeighborhood', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressStreet', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressNumber', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressComplement', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'people');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressId', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressPostalCode', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressCountry', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressState', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressCity', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressNeighborhood', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressStreet', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressNumber', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'addressComplement', '' . "\0" . 'Recruitment\\Entity\\Address' . "\0" . 'people');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAddressId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAddressId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', array());

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressPostalCode', array());

        return parent::getAddressPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCountry', array());

        return parent::getAddressCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressState', array());

        return parent::getAddressState();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCity', array());

        return parent::getAddressCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressNeighborhood()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressNeighborhood', array());

        return parent::getAddressNeighborhood();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressStreet', array());

        return parent::getAddressStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressNumber', array());

        return parent::getAddressNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressComplement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressComplement', array());

        return parent::getAddressComplement();
    }

    /**
     * {@inheritDoc}
     */
    public function getPople()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPople', array());

        return parent::getPople();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressPostalCode($addressPostalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressPostalCode', array($addressPostalCode));

        return parent::setAddressPostalCode($addressPostalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCountry($addressCountry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCountry', array($addressCountry));

        return parent::setAddressCountry($addressCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressState($addressState)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressState', array($addressState));

        return parent::setAddressState($addressState);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCity($addressCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCity', array($addressCity));

        return parent::setAddressCity($addressCity);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressNeighborhood($addressNeighborhood)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressNeighborhood', array($addressNeighborhood));

        return parent::setAddressNeighborhood($addressNeighborhood);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressStreet($addressStreet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressStreet', array($addressStreet));

        return parent::setAddressStreet($addressStreet);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressNumber($addressNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressNumber', array($addressNumber));

        return parent::setAddressNumber($addressNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressComplement($addressComplement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressComplement', array($addressComplement));

        return parent::setAddressComplement($addressComplement);
    }

    /**
     * {@inheritDoc}
     */
    public function setPeople(\Doctrine\Common\Collections\Collection $people)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeople', array($people));

        return parent::setPeople($people);
    }

    /**
     * {@inheritDoc}
     */
    public function addPerson(\Recruitment\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerson', array($person));

        return parent::addPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function removePerson(\Recruitment\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerson', array($person));

        return parent::removePerson($person);
    }

}
