<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \Recruitment\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personId', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personFirstName', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personLastName', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personGender', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personRg', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personCpf', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personEmail', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personSocialMedia', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personPhoto', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personPhone', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personAlternativePhone', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personBirthday', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'addresses', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'user', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'registrations', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'isRelativeOf', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'relatives');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personId', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personFirstName', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personLastName', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personGender', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personRg', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personCpf', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personEmail', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personSocialMedia', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personPhoto', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personPhone', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personAlternativePhone', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'personBirthday', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'addresses', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'user', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'registrations', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'isRelativeOf', '' . "\0" . 'Recruitment\\Entity\\Person' . "\0" . 'relatives');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPersonId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPersonId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonId', array());

        return parent::getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonFirstName', array());

        return parent::getPersonFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonLastName', array());

        return parent::getPersonLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonBirthday', array());

        return parent::getPersonBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonBirthday(\DateTime $personBirthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonBirthday', array($personBirthday));

        return parent::setPersonBirthday($personBirthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonRg', array());

        return parent::getPersonRg();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonCpf', array());

        return parent::getPersonCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonEmail', array());

        return parent::getPersonEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonSocialMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonSocialMedia', array());

        return parent::getPersonSocialMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonPhoto', array());

        return parent::getPersonPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonPhoto($personPhoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonPhoto', array($personPhoto));

        return parent::setPersonPhoto($personPhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonPhone', array());

        return parent::getPersonPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonAlternativePhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonAlternativePhone', array());

        return parent::getPersonAlternativePhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', array());

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonFirstName($personFirstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonFirstName', array($personFirstName));

        return parent::setPersonFirstName($personFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonLastName($personLastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonLastName', array($personLastName));

        return parent::setPersonLastName($personLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonRg($personRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonRg', array($personRg));

        return parent::setPersonRg($personRg);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonCpf($personCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonCpf', array($personCpf));

        return parent::setPersonCpf($personCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonEmail($personEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonEmail', array($personEmail));

        return parent::setPersonEmail($personEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonSocialMedia($personSocialMedia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonSocialMedia', array($personSocialMedia));

        return parent::setPersonSocialMedia($personSocialMedia);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonPhone($personPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonPhone', array($personPhone));

        return parent::setPersonPhone($personPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonAlternativePhone($personAlternativePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonAlternativePhone', array($personAlternativePhone));

        return parent::setPersonAlternativePhone($personAlternativePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddresses(\Doctrine\Common\Collections\Collection $addresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddresses', array($addresses));

        return parent::setAddresses($addresses);
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\Recruitment\Entity\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', array($address));

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\Recruitment\Entity\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', array($address));

        return parent::removeAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrations', array());

        return parent::getRegistrations();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Authentication\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrations(\Doctrine\Common\Collections\Collection $registrations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrations', array($registrations));

        return parent::setRegistrations($registrations);
    }

    /**
     * {@inheritDoc}
     */
    public function addRegistration(\Recruitment\Entity\Registration $registration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegistration', array($registration));

        return parent::addRegistration($registration);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegistration(\Recruitment\Entity\Registration $registration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegistration', array($registration));

        return parent::removeRegistration($registration);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRelativeOf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRelativeOf', array());

        return parent::getIsRelativeOf();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRelativeOf(\Doctrine\Common\Collections\Collection $isRelativeOf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRelativeOf', array($isRelativeOf));

        return parent::setIsRelativeOf($isRelativeOf);
    }

    /**
     * {@inheritDoc}
     */
    public function addIsRelativeOf(\Recruitment\Entity\Person $isRelativeOf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIsRelativeOf', array($isRelativeOf));

        return parent::addIsRelativeOf($isRelativeOf);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIsRelativeOf(\Recruitment\Entity\Person $isRelativeOf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIsRelativeOf', array($isRelativeOf));

        return parent::removeIsRelativeOf($isRelativeOf);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatives', array());

        return parent::getRelatives();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatives(\Doctrine\Common\Collections\Collection $relatives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatives', array($relatives));

        return parent::setRelatives($relatives);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelative(\Recruitment\Entity\Person $relative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelative', array($relative));

        return parent::addRelative($relative);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelative(\Recruitment\Entity\Person $relative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelative', array($relative));

        return parent::removeRelative($relative);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonGender', array());

        return parent::getPersonGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonGender($personGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonGender', array($personGender));

        return parent::setPersonGender($personGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonName', array());

        return parent::getPersonName();
    }

}
