<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Relative extends \Recruitment\Entity\Relative implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relativeId', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'person', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relative', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relativeRelationship');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relativeId', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'person', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relative', '' . "\0" . 'Recruitment\\Entity\\Relative' . "\0" . 'relativeRelationship');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Relative $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRelativeId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRelativeId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelativeId', array());

        return parent::getRelativeId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', array());

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\Recruitment\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', array($person));

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelative()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelative', array());

        return parent::getRelative();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelative(\Recruitment\Entity\Person $relative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelative', array($relative));

        return parent::setRelative($relative);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelativeRelationship()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelativeRelationship', array());

        return parent::getRelativeRelationship();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelativeRelationship($relativeRelationship)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelativeRelationship', array($relativeRelationship));

        return parent::setRelativeRelationship($relativeRelationship);
    }

}
