<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Registration extends \Recruitment\Entity\Registration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationId', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationDate', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'recruitment', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'preInterview', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'person', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'recruitmentKnowAbout', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'occupation', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'education', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerWork', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'howAndWhenKnowUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'whyWorkWithUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerWithUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'responsibility', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'proactive', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerSpirit', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'commitment', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'teamWork', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'efficiency', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'courtesy', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationStatus', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerInterview', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'studentInterview');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationId', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationDate', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'recruitment', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'preInterview', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'person', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'recruitmentKnowAbout', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'occupation', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'education', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerWork', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'howAndWhenKnowUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'whyWorkWithUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerWithUs', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'responsibility', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'proactive', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerSpirit', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'commitment', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'teamWork', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'efficiency', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'courtesy', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'registrationStatus', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'volunteerInterview', '' . "\0" . 'Recruitment\\Entity\\Registration' . "\0" . 'studentInterview');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Registration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRegistrationId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRegistrationId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationId', array());

        return parent::getRegistrationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationDate($format = 'd/m/Y \\à\\s H:i:s')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationDate', array($format));

        return parent::getRegistrationDate($format);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationDateAsDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationDateAsDateTime', array());

        return parent::getRegistrationDateAsDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitment', array());

        return parent::getRecruitment();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitment(\Recruitment\Entity\Recruitment $recruitment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitment', array($recruitment));

        return parent::setRecruitment($recruitment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerson', array());

        return parent::getPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerson(\Recruitment\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerson', array($person));

        return parent::setPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentKnowAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentKnowAbout', array());

        return parent::getRecruitmentKnowAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationNumber', array());

        return parent::getRegistrationNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreInterview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreInterview', array());

        return parent::getPreInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreInterview(\Recruitment\Entity\PreInterview $preInterview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreInterview', array($preInterview));

        return parent::setPreInterview($preInterview);
    }

    /**
     * {@inheritDoc}
     */
    public function addRecruitmentKnowAbout(\Doctrine\Common\Collections\Collection $arr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecruitmentKnowAbout', array($arr));

        return parent::addRecruitmentKnowAbout($arr);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecruitmentKnowAbout(\Doctrine\Common\Collections\Collection $arr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecruitmentKnowAbout', array($arr));

        return parent::removeRecruitmentKnowAbout($arr);
    }

    /**
     * {@inheritDoc}
     */
    public function hasPreInterview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPreInterview', array());

        return parent::hasPreInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function getOccupation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOccupation', array());

        return parent::getOccupation();
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', array());

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteerWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerWork', array());

        return parent::getVolunteerWork();
    }

    /**
     * {@inheritDoc}
     */
    public function getHowAndWhenKnowUs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHowAndWhenKnowUs', array());

        return parent::getHowAndWhenKnowUs();
    }

    /**
     * {@inheritDoc}
     */
    public function getWhyWorkWithUs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhyWorkWithUs', array());

        return parent::getWhyWorkWithUs();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteerWithUs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerWithUs', array());

        return parent::getVolunteerWithUs();
    }

    /**
     * {@inheritDoc}
     */
    public function setOccupation($occupation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOccupation', array($occupation));

        return parent::setOccupation($occupation);
    }

    /**
     * {@inheritDoc}
     */
    public function setEducation($education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducation', array($education));

        return parent::setEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function setVolunteerWork($volunteerWork)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolunteerWork', array($volunteerWork));

        return parent::setVolunteerWork($volunteerWork);
    }

    /**
     * {@inheritDoc}
     */
    public function setHowAndWhenKnowUs($howAndWhenKnowUs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHowAndWhenKnowUs', array($howAndWhenKnowUs));

        return parent::setHowAndWhenKnowUs($howAndWhenKnowUs);
    }

    /**
     * {@inheritDoc}
     */
    public function setWhyWorkWithUs($whyWorkWithUs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWhyWorkWithUs', array($whyWorkWithUs));

        return parent::setWhyWorkWithUs($whyWorkWithUs);
    }

    /**
     * {@inheritDoc}
     */
    public function setVolunteerWithUs($volunteerWithUs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolunteerWithUs', array($volunteerWithUs));

        return parent::setVolunteerWithUs($volunteerWithUs);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsibility()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsibility', array());

        return parent::getResponsibility();
    }

    /**
     * {@inheritDoc}
     */
    public function getProactive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProactive', array());

        return parent::getProactive();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteerSpirit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerSpirit', array());

        return parent::getVolunteerSpirit();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommitment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommitment', array());

        return parent::getCommitment();
    }

    /**
     * {@inheritDoc}
     */
    public function getTeamWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeamWork', array());

        return parent::getTeamWork();
    }

    /**
     * {@inheritDoc}
     */
    public function getEfficiency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEfficiency', array());

        return parent::getEfficiency();
    }

    /**
     * {@inheritDoc}
     */
    public function getCourtesy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCourtesy', array());

        return parent::getCourtesy();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsibility($responsibility)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsibility', array($responsibility));

        return parent::setResponsibility($responsibility);
    }

    /**
     * {@inheritDoc}
     */
    public function setProactive($proactive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProactive', array($proactive));

        return parent::setProactive($proactive);
    }

    /**
     * {@inheritDoc}
     */
    public function setVolunteerSpirit($volunteerSpirit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolunteerSpirit', array($volunteerSpirit));

        return parent::setVolunteerSpirit($volunteerSpirit);
    }

    /**
     * {@inheritDoc}
     */
    public function setCommitment($commitment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommitment', array($commitment));

        return parent::setCommitment($commitment);
    }

    /**
     * {@inheritDoc}
     */
    public function setTeamWork($teamWork)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeamWork', array($teamWork));

        return parent::setTeamWork($teamWork);
    }

    /**
     * {@inheritDoc}
     */
    public function setEfficiency($efficiency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEfficiency', array($efficiency));

        return parent::setEfficiency($efficiency);
    }

    /**
     * {@inheritDoc}
     */
    public function setCourtesy($courtesy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCourtesy', array($courtesy));

        return parent::setCourtesy($courtesy);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationStatus', array());

        return parent::getRegistrationStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function addRegistrationStatus(\Recruitment\Entity\RegistrationStatus $regStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegistrationStatus', array($regStatus));

        return parent::addRegistrationStatus($regStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function hasRegistrationStatus(\Recruitment\Entity\RegistrationStatus $regStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRegistrationStatus', array($regStatus));

        return parent::hasRegistrationStatus($regStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegistrationStatus(\Recruitment\Entity\RegistrationStatus $regStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegistrationStatus', array($regStatus));

        return parent::removeRegistrationStatus($regStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentRegistrationStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentRegistrationStatus', array());

        return parent::getCurrentRegistrationStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteerInterview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerInterview', array());

        return parent::getVolunteerInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolunteerInterview(\Recruitment\Entity\VolunteerInterview $volunteerInterview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolunteerInterview', array($volunteerInterview));

        return parent::setVolunteerInterview($volunteerInterview);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudentInterview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudentInterview', array());

        return parent::getStudentInterview();
    }

    /**
     * {@inheritDoc}
     */
    public function setStudentInterview(\Recruitment\Entity\StudentInterview $studentInterview)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStudentInterview', array($studentInterview));

        return parent::setStudentInterview($studentInterview);
    }

}
