<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VolunteerInterview extends \Recruitment\Entity\VolunteerInterview implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'volunteerInterviewId', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'registration', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'proactivity', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'commitmentAndEfficiency', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'volunteerProfile', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'interest', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'interpersonalRelationship', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'personality', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'coherence', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'result', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'testClass');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'volunteerInterviewId', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'registration', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'proactivity', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'commitmentAndEfficiency', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'volunteerProfile', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'interest', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'interpersonalRelationship', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'personality', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'coherence', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'result', '' . "\0" . 'Recruitment\\Entity\\VolunteerInterview' . "\0" . 'testClass');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VolunteerInterview $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getVolunteerInterviewId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getVolunteerInterviewId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerInterviewId', array());

        return parent::getVolunteerInterviewId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistration', array());

        return parent::getRegistration();
    }

    /**
     * {@inheritDoc}
     */
    public function getProactivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProactivity', array());

        return parent::getProactivity();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommitmentAndEfficiency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommitmentAndEfficiency', array());

        return parent::getCommitmentAndEfficiency();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteerProfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteerProfile', array());

        return parent::getVolunteerProfile();
    }

    /**
     * {@inheritDoc}
     */
    public function getInterest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterest', array());

        return parent::getInterest();
    }

    /**
     * {@inheritDoc}
     */
    public function getInterpersonalRelationship()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterpersonalRelationship', array());

        return parent::getInterpersonalRelationship();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonality()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonality', array());

        return parent::getPersonality();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoherence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoherence', array());

        return parent::getCoherence();
    }

    /**
     * {@inheritDoc}
     */
    public function getResult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResult', array());

        return parent::getResult();
    }

    /**
     * {@inheritDoc}
     */
    public function getTestClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestClass', array());

        return parent::getTestClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistration(\Recruitment\Entity\Registration $registration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistration', array($registration));

        return parent::setRegistration($registration);
    }

    /**
     * {@inheritDoc}
     */
    public function setProactivity($proactivity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProactivity', array($proactivity));

        return parent::setProactivity($proactivity);
    }

    /**
     * {@inheritDoc}
     */
    public function setCommitmentAndEfficiency($commitmentAndEfficiency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommitmentAndEfficiency', array($commitmentAndEfficiency));

        return parent::setCommitmentAndEfficiency($commitmentAndEfficiency);
    }

    /**
     * {@inheritDoc}
     */
    public function setVolunteerProfile($volunteerProfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolunteerProfile', array($volunteerProfile));

        return parent::setVolunteerProfile($volunteerProfile);
    }

    /**
     * {@inheritDoc}
     */
    public function setInterest($interest)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterest', array($interest));

        return parent::setInterest($interest);
    }

    /**
     * {@inheritDoc}
     */
    public function setInterpersonalRelationship($interpersonalRelationship)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterpersonalRelationship', array($interpersonalRelationship));

        return parent::setInterpersonalRelationship($interpersonalRelationship);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonality($personality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonality', array($personality));

        return parent::setPersonality($personality);
    }

    /**
     * {@inheritDoc}
     */
    public function setCoherence($coherence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoherence', array($coherence));

        return parent::setCoherence($coherence);
    }

    /**
     * {@inheritDoc}
     */
    public function setResult($result)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResult', array($result));

        return parent::setResult($result);
    }

    /**
     * {@inheritDoc}
     */
    public function setTestClass($testClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestClass', array($testClass));

        return parent::setTestClass($testClass);
    }

}
