<?php

namespace DoctrineORMModule\Proxy\__CG__\Recruitment\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recruitment extends \Recruitment\Entity\Recruitment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentId', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentNumber', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentYear', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentBeginDate', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentEndDate', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentPublicNotice', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentType');
        }

        return array('__isInitialized__', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentId', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentNumber', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentYear', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentBeginDate', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentEndDate', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentPublicNotice', '' . "\0" . 'Recruitment\\Entity\\Recruitment' . "\0" . 'recruitmentType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Recruitment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRecruitmentId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRecruitmentId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentId', array());

        return parent::getRecruitmentId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentNumber', array());

        return parent::getRecruitmentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentYear', array());

        return parent::getRecruitmentYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentNumber($recruitmentNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentNumber', array($recruitmentNumber));

        return parent::setRecruitmentNumber($recruitmentNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentYear($recruitmentYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentYear', array($recruitmentYear));

        return parent::setRecruitmentYear($recruitmentYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentBeginDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentBeginDate', array());

        return parent::getRecruitmentBeginDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentEndDate', array());

        return parent::getRecruitmentEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentPublicNotice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentPublicNotice', array());

        return parent::getRecruitmentPublicNotice();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruitmentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruitmentType', array());

        return parent::getRecruitmentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentBeginDate(\DateTime $recruitmentBeginDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentBeginDate', array($recruitmentBeginDate));

        return parent::setRecruitmentBeginDate($recruitmentBeginDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentEndDate(\DateTime $recruitmentEndDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentEndDate', array($recruitmentEndDate));

        return parent::setRecruitmentEndDate($recruitmentEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentPublicNotice($recruitmentPublicNotice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentPublicNotice', array($recruitmentPublicNotice));

        return parent::setRecruitmentPublicNotice($recruitmentPublicNotice);
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruitmentType($recruitmentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruitmentType', array($recruitmentType));

        return parent::setRecruitmentType($recruitmentType);
    }

}
