
<div class="container">
    <h1>Privilege index</h1>
    <hr>

    <?php echo $this->message; ?>

    <div class="table-responsive">
        <table class='table'>
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Privilege Name</th>
                    <th class="text-center">Allow?</th>
                    <th class="text-center">Resource Name</th>
                    <th class="text-center">Role Name</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->privileges as $privilege): ?>
                    <tr>
                        <td class="text-center"> <?php echo $this->escapeHtml($privilege->getPrivilegeId()); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($privilege->getPrivilegeName()); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($privilege->getPrivilegePermissionAllow() ? 'TRUE' : 'FALSE'); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($privilege->getResource()->getResourceName()); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($privilege->getRole()->getRoleName()); ?></td>
                        <td class="text-center"> <a class="btn btn-danger" href="<?php echo $this->url('authorization/default', array('controller' => 'privilege', 'action' => 'edit')); ?>">Edit</a></td>
                        <td class="text-center"> <a class="btn btn-danger" href="<?php echo $this->url('authorization/default', array('controller' => 'privilege', 'action' => 'delete')); ?>">Delete</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

