<section class="content">
    <?php
    $this->headTitle()->append('Adicionar Questão')
        ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row">

        <div class="container-fluid">
            <p>Por favor, antes de inserir a questão, aguarde até que a fórmula abaixo seja exibida. 
                Caso a fórmula não apareça dentro de alguns segundos, por favor, recarregue a página.</p>
            <br>
            <h3 id="testEquation" style="display:none;" class="text-center">
                $$ e^{ix} = \cos{x} + i \sin{x}. $$
            </h3>
        </div>
        <hr>
        <?php if ($form !== null): ?>
            <div class="container-fluid">
                <div class="col-xs-12 col-md-6">
                    <h3 class="text-center">Questão</h3>
                    <?php $form->prepare(); ?>
                    <?php echo $this->form()->openTag($form); ?>
                    <div class="col-md-12">
                        <?php echo $this->formRow($form->get('exam-question')->get('subjectId')); ?>
                        <?php echo $this->formRow($form->get('exam-question')->get('examQuestionType')); ?>
                        <?php echo $this->formRow($form->get('exam-question')->get('examQuestionEnunciation')); ?>
                        <div class="hero-unit">
                            <?php echo $this->formCollection($form->get('exam-question')->get('answerOptions')); ?>
                        </div>
                        <div class="btn-group btn-group-justified" id="alternative-control-btns">
                            <div class="btn-group"><?php echo $this->formElement($form->get('addAlternative')); ?></div>
                            <div class="btn-group"><?php echo $this->formElement($form->get('removeAlternative')); ?></div>             
                        </div>
                        <br>
                    </div>
                    <div class="col-md-12">
                        <?php echo $this->formRow($form->get('submit')); ?>
                    </div>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <h3 class="text-center">Pré-visualização</h3>
                    <div id="mathPreview" class="text-justify"></div>
                    <div id="mathBuffer"></div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/add-question';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>

