<section class="content">
    <?php
    $this->headTitle()->append('Criar Conteúdo')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <?php if ($this->form !== null) :
                echo $this->render('exam_content_template', array(
                    'form' => $this->form,
                    'baseSubjects' => $this->baseSubjects,
                    'subjectQuantities' => null,
                    'editAllowed' => $this->editAllowed,
                ));
            endif;
            ?>
        </div>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/create-content';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>