<section class="content">
    <?php 
        $this->headTitle()->append('Editar questão')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row" id="data" 
         data-subject-id=
            "<?php if ($sId !== null) {
                echo $sId;
            } else {
                echo 0;
            }
            ?>">
        <?php if ($form !== null): ?>
            <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
                <?php echo $this->form($form); ?>
            </div>
        <?php endif; ?>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/edit-question';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>
