<!-- INÍCIO - Templates para a pré-visualização do conteúdo -->
<div id="base-subject-template" class="hide">
    <div class="base-subject-block">
        <h3 class="text-center no-margin dontsplit dontend">
            <strong class="title"></strong>
        </h3>
    </div>
</div>

<div id="parallel-subject-template" class="hide">
    <div class="parallel-subject-block">
        <h3 class="text-center no-margin dontsplit dontend">
            <strong class="title"></strong>
        </h3>
    </div>
</div>

<div id="parallel-subjects-template" class="hide">
    <div class="parallel-subjects-block">
    </div>
</div>

<div id="single-column-subject-template" class="hide">
    <div class="single-column-block">
        <h3 class="text-center no-margin dontsplit dontend">
            <strong class="title"></strong>
        </h3>
    </div>
</div>

<div id="single-column-question-template" class="hide">
    <div class="question-block">
    </div>
</div>

<div id="question-alternative-template" class="hide">
    <div class="question-alternative">
        <span class="dontend pull-left question-alternative-identifier" style="padding-right: 1mm">
            <!-- ALTERNATIVA -->
        </span>
    </div>
</div>

<div id="control-icons-template" class="hide">
    <span class="do-not-print control-icons pull-right">
        <i class="rm-question fa fa-times"></i><br>
        <i class="move-up fa fa-sort-asc"></i><br>
        <i class="move-down fa fa-sort-desc"></i>
    </span> 
</div>

<div id="question-template" class="hide">
    <div class="question-block">
        <p class="no-margin dontsplit dontend">
            <strong>QUESTÃO <span class="q-number"></span></strong>
        </p> 
        <!-- ENUNCIADO -->
        <!-- ALTERNATIVAS -->
        <hr class="q-divider removeiffirst removeiflast">
    </div>
</div>
<!-- FIM -Templates para a pré-visualização do conteúdo -->
