<p><?php echo $this->message; ?></p>
<div class="row">
    <?php if ($this->form !== null) : ?>
        <?php
        $form->prepare();
        $examContent = $form->get('exam-content-fieldset');
        echo $this->form()->openTag($form);
        ?>
        <div class="col-xs-12 no-padding">
            <div class="box box-success">
                <div class="box-header with-border">
                    <i class="fa fa-info-circle" aria-hidden="true"></i>
                    <h3 class="box-title">Instruções</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body" style="display: block;">
                    <ul>
                        <li>Descreva o conteúdo a ser criado para facilitar a reutilização em provas futuras.</li>
                        <li>Informe o número da primeira questão no campo abaixo.</li>
                        <li>Informe o número de questões da prova que serão referentes a cada uma das disciplinas abaixo.</li>
                        <li>
                            Ordene as áreas e disciplinas de acordo com a sequência pretendida para as questões na prova. 
                            <br> 
                            Para ordenar, arraste o bloco para a posição desejada.
                        </li>
                    </ul>
                    <div class="col-xs-12 margin-bottom">
                        <button type="button" class="btn btn-flat col-xs-3">
                            <span style="font-size: 22px;"><i class="fa fa-columns"></i></span>
                            <br>
                            <span class="text-bold">Disciplinas paralelas</span>
                        </button>
                        <div class="col-xs-9">
                            São disciplinas que compartilham a numeração das questões. Ex: Inglês e Espanhol.
                            <br>
                            Para definir as disciplinas, selecione as desejadas e, então, clique no botão com o ícone mostrado a esquerda.
                            <br>
                            Disciplinas paralelas sempre estarão em sequência. A posição do grupo é dada pela primeira disciplina, seguindo a ordem estabelecida.
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <button type="button" class="btn btn-flat col-xs-3">
                            <span style="font-size: 22px;"><i class="fa fa-align-justify"></i></span>
                            <br>
                            <span class="text-bold">Coluna única</span>
                        </button>
                        <div class="col-xs-9">
                            São disciplinas cujas questões são exibidas em uma única coluna, diferentemente do resto da prova. Ex: Redação
                            <br>
                            Para que uma disciplina seja de coluna única, selecione-a e clique no botão com o ícone mostrado a esquerda.
                            <br>
                            Disciplinas de coluna única não são numeradas.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <?php echo $this->formRow($examContent->get('description')); ?>
            </div>
            <div class="col-xs-12">
                <div class="form-group">
                    <label>
                        Número da primeira questão 
                    </label>
                    <input type="number"
                           class="col-xs-12" 
                           style="line-height: 2;"
                           id="start-number"
                           value="1"
                           tabindex="1">
                    <p class="text-red text-bold col-xs-12" id="start-number-error"></p>
                </div>
            </div>
            
            <?php if (isset($this->contentId)) : ?>
               <div id="content-info" data-id="<?php echo $this->contentId; ?>"></div>
            <?php endif; ?>
               
            <div id="all-base-subjects"
                 class="col-xs-12 no-padding"
                 style="overflow:auto; float: left;"><!-- style: Fix para um bug do jquery-ui (sortable) -->
                <?php if ($this->editAllowed) : ?>
                    <?php 
                        $i = 0;
                        $colors = ['purple', 'orange', 'navy', 'maroon', 'teal'];
                        
                    foreach ($this->baseSubjects as $baseSubjectIndex => $baseSubject) : ?>
                        <?php 
                        $baseSubjectId = $baseSubject->getSubjectId();
                        $baseSubjectName = $baseSubject->getSubjectName();
                        ?>
                        <div id="base-subject-<?php echo $baseSubjectId ; ?>"
                             class="base-subjects"
                             data-name="<?php echo $baseSubjectName; ?>"
                             data-id="<?php echo $baseSubjectId; ?>"
                        >
                            <div class="box box-widget widget-user-2">
                                <div class="box-header widget-user-header 
                                     bg-<?php echo $colors[$baseSubjectIndex % count($colors)];?>">
                                    <div class="box-tools pull-right">
                                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                            <i class="fa fa-2x fa-minus" style="color: white;"></i>
                                        </button>
                                    </div>
                                    <div class="widget-user-image">
                                        <i class="fa fa-sort" aria-hidden="true" 
                                           style="font-size: 25px; float:left;"></i>
                                    </div>
                                    <h3 class="widget-user-username"><?php echo $baseSubjectName; ?></h3>
                                </div>

                                <div class="box-footer no-padding">
                                    <div class="col-xs-8 no-padding">
                                        <table class="table table-bordered table-condensed col-xs-12">
                                            <thead>
                                                <tr>
                                                    <th></th>
                                                    <th class="text-center">
                                                        Nome da disciplina
                                                    </th>
                                                    <th class="text-center">
                                                        Nº de questões
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody class="bg-gray-light children-subjects" style="overflow:auto;"><!-- style: Fix para um bug do jquery-ui (sortable) -->
                                            <?php 
                                            $bSubjectChildren = $baseSubject->getChildren();
                                            foreach ($bSubjectChildren as $subject) : ?>
                                                <?php 
                                                $subjectId = $subject->getSubjectId();
                                                $subjectName = $subject->getSubjectName();
                                                $singleColumnSubject = "";
                                                ?>
                                                <tr id="subject-<?php echo $subjectId; ?>" 
                                                    class="subjects cats-row bg-gray-light
                                                    <?php echo $singleColumnSubject ?>" 
                                                    style="border: solid 1px darkgrey"
                                                    data-name="<?php echo $subjectName; ?>"
                                                    data-id="<?php echo $subjectId; ?>"
                                                >
                                                    <td class="col-xs-1 text-center sort-icon">
                                                        <i class="fa fa-sort" 
                                                           aria-hidden="true" 
                                                           style="font-size: 18px;">
                                                        </i>
                                                    </td>
                                                    <td class="col-xs-8">
                                                        <div class="col-xs-12 text-center">
                                                            <?php echo $subjectName; ?>
                                                        </div>
                                                    </td>
                                                    <td class="quantity-block col-xs-1 no-padding form-group" 
                                                        style="line-height: 2;"
                                                        data-quantity="">

                                                        <?php $this
                                                                ->formInput($form
                                                                        ->get('examQuestionQuantity')
                                                                        ->get($i)
                                                                        ->get('quantity') 
                                                                        ->setValue(0));
                                                        ?>
                                                        <?php echo $this
                                                                ->formInput($form
                                                                        ->get('examQuestionQuantity')
                                                                        ->get($i)
                                                                        ->get('quantity'));
                                                        ?>
                                                    </td>
                                                </tr>

                                                <?php ++$i; ?>
                                            <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="col-xs-4 no-padding">
                                        <div class="col-xs-12 parallel-block margin-bottom">
                                            <button type="button" class="select-parallel-subjects col-xs-12 btn">
                                                <span style="font-size: 22px;"><i class="fa fa-columns"></i></span>
                                                <br>
                                                <strong>Disciplinas paralelas</strong>
                                            </button>
                                            <div class="col-xs-12 parallel-groups no-padding">
                                            </div>
                                            <div class="col-xs-12">
                                                <p class="parallel-group-error text-bold text-red"></p>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 single-column-block margin-bottom">
                                            <button type="button" class="select-single-column-subjects col-xs-12 btn">
                                                <span style="font-size: 22px;"><i class="fa fa-align-justify"></i></span>
                                                <br>
                                                <strong>Disciplinas de coluna única</strong>
                                            </button>
                                            <div class="col-xs-12 single-column-subjects no-padding">
                                            </div>
                                            <div class="col-xs-12">
                                                <p class="single-column-subject-error text-bold text-red"></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <p class="text-bold text-red hide" id="quantity-error">
                                            Para diminuir a quantidade de questões dessa disciplina, é necessário remover as questões associadas a ela, na montagem do conteúdo.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                <?php else : ?>
                    <h4 class="text-bold text-uppercase text-center">
                        Não é possível editar o número de questões pois esse conteúdo está associado a uma ou mais provas.
                    </h4>
                <?php endif; ?> 
            </div>
            
            <div class="info-box" style="display: inline-block;">
                <span class="info-box-icon bg-olive"><i class="fa fa-plus"></i></span>

                <div class="info-box-content">
                    <span id="question-count" class="info-box-number">0</span>
                    <span class="info-box-text">Questões </span>
                </div>
            </div>
        </div>
        <?php echo $this->formButton($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    <?php endif; ?>
</div>