<section class="content">
    <?php
    $this->headTitle()->append('Simulados')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <table class="table table-condensed table-bordered table-striped" id="exams-table">              
                <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Data</th>
                        <th class="text-center">Nome</th>
                        <th class="text-center">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($this->exams !== null): ?>
                        <?php foreach ($this->exams as $exam):?>
                            <tr class="cats-row text-center" 
                                data-id="<?php echo $exam->getExamId(); ?>" 
                                id="exam-<?php echo $exam->getExamId(); ?>">
                                <td><?php echo $exam->getExamId(); ?></td>
                                <td><?php echo ($exam->getExamDate() !== null ? $exam->getExamDate()->format('d/m/Y') : '-'); ?></td>
                                <td><?php echo $exam->getExamName(); ?></td>
                                <td><?php echo ($exam->getExamStatus() !== null ? SchoolManagement\Entity\Exam::statusToString($exam->getExamStatus()) : '-'); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/index';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>