<section class="content">
    <?php
    $this->headLink()->appendStylesheet('/css/exam-print.css', 'all');
    $this->headTitle()->append('Preparação do Conteúdo')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    
    <div class="row">  
            <?php if ($this->editAllowed) : ?>  
                <div class="box box-success color-palette-box no-margin">
                    <div class="box-header with-border">
                        <h3 class="box-title text-uppercase"><i class="fa fa-list" aria-hidden="true"></i> DISCIPLINAS E QUESTÕES </h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div><!-- /.box-tools -->
                    </div>   
                    <div class="box-body">                
                        <?php $colors = ['purple', 'orange', 'navy', 'maroon', 'teal']; ?>
                        <style>
                            .nav-tabs-custom>.nav-tabs>li.active  {
                                border-top-color: #4c4c4c;
                            }

                            #content-info > .nav-tabs > li > a {
                                color: white;
                            } 
                            #content-info > .nav-tabs > li.active > a {
                                color: black;
                            } 

                        </style>
                        <div class="col-xs-12 no-padding nav-tabs-custom" 
                             id="content-info" 
                             data-id="<?php echo $this->contentId; ?>"
                             style="border: thin lightgray solid; ">
                            <ul class="nav nav-tabs margin-bottom">
                                <?php foreach ($this->baseSubjects as $i => $baseSubject) : ?> 
                                    <li class=" no-margin
                                        <?php 
                                        if ($i === 0) :
                                            echo " active ";
                                        endif; 
                                        ?>
                                        bg-<?php echo $colors[$i % count($colors)]; ?>">
                                        <a class="text-white" 
                                           href="#base-subject-info-<?php echo $baseSubject->getSubjectId(); ?>" 
                                           data-toggle="tab"
                                           style="border-right: 0; border-left: 0;">
                                            <?php echo $baseSubject->getSubjectName(); ?>
                                        </a>
                                    </li>
                                <?php endforeach; ?>    
                            </ul>

                            <div class="tab-content"
                                 style="border-right: thick <?php echo $colors[$i % count($colors)]; ?> solid">
                                <?php foreach ($this->baseSubjects as $i => $baseSubject) : ?>
                                    <?php
                                    $baseSubjectName = $baseSubject->getSubjectName();
                                    $baseSubjectId = $baseSubject->getSubjectId();                                       
                                    ?>

                                    <div class="tab-pane base-subject-info nav-tabs-custom no-margin <?php 
                                                    if ($i === 0) :
                                                        echo " active ";
                                                    endif; 
                                                    ?>"  
                                         id="base-subject-info-<?php echo $baseSubjectId; ?>"
                                         data-name="<?php echo $baseSubjectName; ?>"
                                         data-id="<?php echo $baseSubjectId; ?>">

                                        <ul class="nav nav-tabs margin-bottom">  
                                            <?php foreach ($baseSubject->getChildren() as $j => $subject) : ?>
                                                <li class="
                                                    <?php 
                                                    if ($j === 0) :
                                                        echo " active ";
                                                    endif; 
                                                    ?>">
                                                    <a href="#subject-info-<?php echo $subject->getSubjectId(); ?>" 
                                                       data-toggle="tab">
                                                        <?php echo $subject->getSubjectName(); ?>
                                                    </a>
                                                </li>                                           
                                            <?php endforeach; ?>
                                        </ul>

                                        <div class="tab-content">
                                            <?php foreach ($baseSubject->getChildren() as $j => $subject) : ?>
                                                <?php
                                                $subjectId = $subject->getSubjectId();
                                                $subjectName = $subject->getSubjectName();
                                                ?>
                                                <div class="tab-pane subject-info row
                                                    <?php 
                                                    if ($j === 0) :
                                                        echo " active ";
                                                    endif; 
                                                    ?>
                                                    " 
                                                    data-id="<?php echo $subjectId; ?>"
                                                    data-name="<?php echo $subjectName; ?>"
                                                    id="subject-info-<?php echo $subjectId; ?>">        
                                                    <div class="col-xs-11">
                                                        <?php
                                                        foreach ($subject->getChildren() as $topic) :

                                                            //  DFS para imprimir a arvore de disciplinas
                                                            $visited = [];
                                                            $stack = new SplStack();
                                                            $stack->push($topic);
                                                            while (!$stack->isEmpty()) :
                                                                $current = $stack->pop();
                                                                if (isset($visited[$current->getSubjectId()])) :
                                                                    continue;
                                                                endif;
                                                                $visited[$current->getSubjectId()]
                                                                        = true;
                                                                if (empty($current->getChildren()->toArray())) :
                                                                    ?>
                                                                    <?php
                                                                    $topicName = $current->getSubjectName();
                                                                    $topicId = $current->getSubjectId();
                                                                    ?>
                                                                    <button class="btn btn-flat topic-info
                                                                            bg-<?php echo $colors[$i % count($colors)]; ?>"
                                                                            style="cursor: pointer;"
                                                                            data-id="<?php echo $topicId; ?>"
                                                                            data-name="<?php echo $topicName; ?> - <?php echo $subjectName; ?>"
                                                                            id="topic-info-<?php echo $topicId; ?>">
                                                                        <?php echo $topicName;  ?>
                                                                    </button>
                                                                    <?php
                                                                endif;

                                                                foreach ($current->getChildren()->toArray() as $child) :
                                                                    $stack->push($child);
                                                                endforeach;
                                                            endwhile;

                                                        endforeach;
                                                        ?> 
                                                        <button class="btn btn-flat topic-info
                                                                bg-<?php echo $colors[$i % count($colors)]; ?>"
                                                                style="cursor: pointer;"
                                                                data-id="<?php echo $subjectId; ?>"
                                                                data-name="SEM TÓPICO - <?php echo $subjectName; ?>"
                                                                id="topic-info-<?php echo $subjectId; ?>">
                                                            SEM TÓPICO
                                                        </button>
                                                    </div>
                                                    <div class="col-xs-1 no-padding">
                                                        <div class="info-box-content no-margin">
                                                            <span class="info-box-number">
                                                                <span class="q-added">0</span> 
                                                                / 
                                                                <span class="q-amount text-blue">0</span>                                                                
                                                            </span>                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            
                            <div class="info-box-content no-margin">
                                <span class="info-box-number text-right">
                                    <span id="added-questions">0</span> 
                                    / 
                                    <span id="questions-count" class="text-blue">0</span>
                                </span>                                                            
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                
                <div class="row">
                    <div class="col-xs-6">
                        <div class="box box-warning color-palette-box no-padding no-margin">
                            <div class="box-header with-border">
                                <h3 class="box-title text-uppercase"><i class="fa fa-list" aria-hidden="true"></i> SELEÇÃO DAS QUESTÕES</h3>
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                </div><!-- /.box-tools -->
                            </div>

                            <div class="box-body">  
                                <div class="col-xs-12" id="questions">
                                    <div class="row"> 
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 save-content">
                                                  <i class="fa fa-save"></i> Salvar conteúdo
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 autosaving" data-autosave="off">
                                                  <i class="fa fa-check"></i> Salvar automaticamente
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 add-question">
                                                  <i class="fa fa-plus"></i> Adicionar questões
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin refresh-button col-xs-12">
                                                  <i class="fa fa-refresh"></i> Recarregar questões
                                                </a>
                                            </div>
                                        </div>
                                    </div> 
                                    <div class="row text-center">
                                        <h4 id="table-content-title">TÍTULO</h4>
                                    </div>
                                    <div class="row text-center">
                                        <p class="text-red text-bold" style="display: none;" id="question-quantity-exceeded-alert">Não é possível adicionar mais questões a esta disciplina, pois o limite especificado na configuração do conteúdo já foi atingido.</p>
                                    </div>
                                    <div class="row">
                                        <div class="table-responsive">
                                            <table class="table table-condensed table-bordered" id="question-table">
                                                <thead>
                                                <th>Questões</th>
                                                </thead>
                                                <tbody>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div> 
                                    <div class="row"> 
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 save-content">
                                                  <i class="fa fa-save"></i> Salvar conteúdo
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 autosaving" data-autosave="off">
                                                  <i class="fa fa-check"></i> Salvar automaticamente
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin col-xs-12 add-question">
                                                  <i class="fa fa-plus"></i> Adicionar questões
                                                </a>
                                            </div>
                                        </div>
                                        <div class="col-xs-3 no-padding">
                                            <div class="col-xs-12">
                                                <a class="btn btn-app no-margin refresh-button col-xs-12">
                                                  <i class="fa fa-refresh"></i> Recarregar questões
                                                </a>
                                            </div>
                                        </div>
                                    </div>   
                                </div>
                            </div>
                        </div>
                    </div>

                <?php else : ?> 
                    <h4 class="text-bold text-uppercase text-center" style="opacity: 0.5">
                        Não é possível selecionar questões pois esse conteúdo está associado a uma ou mais provas.
                    </h4>
                <?php endif; ?> 

                <!-- PROVA -->
                <div class="col-xs-6">
                    <div class="box box-warning color-palette-box no-padding no-margin">
                        <div class="box-header with-border">
                            <h3 class="box-title text-uppercase"><i class="fa fa-file-text-o"></i> PRÉ-VISUALIZAÇÃO DA PROVA </h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                            </div><!-- /.box-tools -->
                        </div>
                        <div class="box-body">
                            <?php echo $this->render('exam_content_structure_templates', array()); ?>

                            <!-- PREVIEW -->
                            <div class="preview-page <?php echo ($this->editAllowed ? '' : 'view-only'); ?>"
                                 style="width: 100%; max-height: 800px; overflow: scroll;">
                                <div class="content-questions">
                                </div>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                </div>
            </div>
            
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-paragraph"></i> DESCRIÇÃO DO CONTEÚDO </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->description; ?>
                    <span class="hide" id="questions-start-at-number">
                        <?php echo $this->questionsStartAtNumber; ?>
                    </span>
                </div><!-- /.box-body -->
            </div><!-- /.box -->    
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/prepare-content';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>