<section class="content">
    <?php
    $this->headLink()->appendStylesheet('/css/exam-print.css', 'all');
    $this->headTitle()->append('Preparação do Conteúdo')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-paragraph"></i> DESCRIÇÃO </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->description; ?>
                    <span class="hide" id="questions-start-at-number">
                        <?php echo $this->questionsStartAtNumber; ?>
                    </span>
                </div><!-- /.box-body -->
            </div><!-- /.box -->            
            
            <div class="box box-success color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-list" aria-hidden="true"></i> SELEÇÃO DAS QUESTÕES</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="box-body">
                    <?php if ($this->editAllowed) : ?>                     
                        <?php $colors = ['purple', 'orange', 'navy', 'maroon', 'teal']; ?>
                        <style>
                            .nav-tabs-custom>.nav-tabs>li.active  {
                                border-top-color: #4c4c4c;
                            }
                        </style>
                        <div class="col-xs-12 no-padding" id="content-info" data-id="<?php echo $this->contentId; ?>">
                            <?php foreach ($this->baseSubjects as $i => $baseSubject) : ?> 
                                <?php
                                $baseSubjectName = $baseSubject->getSubjectName();
                                $baseSubjectId = $baseSubject->getSubjectId();                                       
                                ?>
                                <div class="base-subject-info nav-tabs-custom" 
                                     id="base-subject-info-<?php echo $baseSubjectId; ?>"
                                     data-name="<?php echo $baseSubjectName; ?>"
                                     data-id="<?php echo $baseSubjectId; ?>"
                                     style="border: thin lightgray solid; 
                                            border-right: thick <?php echo $colors[$i % count($colors)]; ?> solid">
                                    
                                    <ul class="nav nav-tabs">  
                                        <?php foreach ($baseSubject->getChildren() as $j => $subject) : ?>
                                            <li class="
                                                <?php 
                                                if ($j === 0) :
                                                    echo " active ";
                                                endif; 
                                                ?>">
                                                <a href="#subject-info-<?php echo $subject->getSubjectId(); ?>" 
                                                   data-toggle="tab">
                                                       <?php echo $subject->getSubjectName(); ?>
                                                </a>
                                            </li>                                           
                                        <?php endforeach; ?>
                                    </ul>
                                    
                                    <div class="tab-content">
                                        <?php foreach ($baseSubject->getChildren() as $j => $subject) : ?>
                                            <?php
                                            $subjectId = $subject->getSubjectId();
                                            $subjectName = $subject->getSubjectName();
                                            ?>
                                            <div class="tab-pane subject-info row
                                                <?php 
                                                if ($j === 0) :
                                                    echo " active ";
                                                endif; 
                                                ?>
                                                " 
                                                data-id="<?php echo $subjectId; ?>"
                                                data-name="<?php echo $subjectName; ?>"
                                                id="subject-info-<?php echo $subjectId; ?>">        
                                                <div class="col-xs-11">
                                                    <?php
                                                    foreach ($subject->getChildren() as $topic) :

                                                        //  DFS para imprimir a arvore de disciplinas
                                                        $visited = [];
                                                        $stack = new SplStack();
                                                        $stack->push($topic);
                                                        while (!$stack->isEmpty()) :
                                                            $current = $stack->pop();
                                                            if (isset($visited[$current->getSubjectId()])) :
                                                                continue;
                                                            endif;
                                                            $visited[$current->getSubjectId()]
                                                                    = true;
                                                            if (empty($current->getChildren()->toArray())) :
                                                                ?>
                                                                <?php
                                                                $topicName = $current->getSubjectName();
                                                                $topicId = $current->getSubjectId();
                                                                ?>
                                                                <button class="btn btn-flat topic-info
                                                                        bg-<?php echo $colors[$i % count($colors)]; ?>"
                                                                        style="cursor: pointer;"
                                                                        data-id="<?php echo $topicId; ?>"
                                                                        data-name="<?php echo $topicName; ?> - <?php echo $subjectName; ?>"
                                                                        id="topic-info-<?php echo $topicId; ?>">
                                                                    <?php echo $topicName;  ?>
                                                                </button>
                                                                <?php
                                                            endif;

                                                            foreach ($current->getChildren()->toArray() as $child) :
                                                                $stack->push($child);
                                                            endforeach;
                                                        endwhile;

                                                    endforeach;
                                                    ?> 
                                                    <button class="btn btn-flat topic-info
                                                            bg-<?php echo $colors[$i % count($colors)]; ?>"
                                                            style="cursor: pointer;"
                                                            data-id="<?php echo $subjectId; ?>"
                                                            data-name="SEM TÓPICO - <?php echo $subjectName; ?>"
                                                            id="topic-info-<?php echo $subjectId; ?>">
                                                        SEM TÓPICO
                                                    </button>
                                                </div>
                                                <div class="col-xs-1 no-padding">
                                                    <div class="info-box-content no-margin">
                                                        <span class="info-box-number">
                                                            <span class="q-added">0</span> 
                                                            / 
                                                            <span class="q-amount text-blue">0</span>                                                                
                                                        </span>                                                            
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            <?php endforeach; ?>

                        </div>
                        
                        <div class="col-xs-12" id="questions">
                            <div class="row text-center">
                                <h4 id="table-content-title">TÍTULO</h4>
                                <div class="pull-right no-padding"> 
                                    <span class="text-bold text-sm" style="padding-right: 5%;">RECARREGAR QUESTÕES</span>
                                    <i class="fa fa-refresh text-purple" style="font-size: 17px;" id="refresh-button" aria-hidden="true"></i>               
                                </div>
                            </div>
                            <div class="row"> 
                                <div class="col-xs-4 col-xs-offset-4"> 
                                    <button class="btn-block btn btn-flat btn-success add-question"><span class="glyphicon glyphicon-plus"></span></button>
                                </div>    
                            </div>  
                            <div class="row">
                                <div class="table-responsive">
                                    <table class="table table-condensed table-bordered" id="question-table">
                                        <thead>
                                        <th>Questões</th>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div> 
                            <div class="row"> 
                                <div class="col-xs-4 col-xs-offset-4"> 
                                    <button class="btn-block btn btn-flat btn-success add-question"><span class="glyphicon glyphicon-plus"></span></button>
                                </div>    
                            </div>  
                        </div>
                    <?php else : ?> 
                        <h4 class="text-bold text-uppercase text-center" style="opacity: 0.5">
                            Não é possível selecionar questões pois esse conteúdo está associado a uma ou mais provas.
                        </h4>
                    <?php endif; ?> 
                </div>
                <!-- /.box-body -->
            </div>
            
            <!-- PROVA -->
            <div class="box box-warning color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-file-text-o"></i> PRÉ-VISUALIZAÇÃO DA PROVA </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="box-body">
                    <?php if ($this->editAllowed) : ?> 
                        <div class="do-not-print col-xs-12">
                            <div class="info-box-content no-margin">
                                <span class="info-box-number">
                                    <span id="added-questions">0</span> 
                                    / 
                                    <span id="questions-count" class="text-blue">0</span>
                                </span>                                                            
                            </div>
                        </div>

                        <div class="do-not-print row">  
                            <button class="col-xs-6 col-xs-offset-3 btn btn-success" id="save-content">Salvar Conteúdo</button>
                            <br><br><br><br>
                            <label class="col-xs-12 text-center"><input type='checkbox' id="autosaving" style="margin-right: 5px">Salvar automaticamente a cada mudança</label>
                        </div>
                    <?php endif; ?>                     
                    
                    <?php echo $this->render('exam_content_structure_templates', array()); ?>
                    
                    <!-- PREVIEW -->
                    <div class="preview-page <?php echo ($this->editAllowed ? '' : 'view-only'); ?>">
                        <div class="content-questions">
                        </div>
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.box-body -->
            
        </div>
    </div>
</div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/prepare-content';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>