<section class="content">
    <?php
    $this->headLink()->appendStylesheet('/css/exam-print.css', 'all');
    $this->headTitle()->append('Preparação do Conteúdo')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-paragraph"></i> DESCRIÇÃO </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <?php echo $this->contentDescription; ?>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            
            <div class="box box-primary collapsed-box color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-cogs"></i> CONFIGURAÇÃO DO SIMULADO</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <input type="hidden" name="contentId" id="contentId" value="<?php echo $this->contentId; ?>">
                <div class="box-body">
                    <div class="col-xs-12 no-padding">
                        <table class="table table-bordered table-condensed" style="opacity: 0.5">
                            <tr>
                                <?php foreach ($this->baseSubjects as $baseSubject) : ?>
                                    <?php
                                    if ($baseSubject->getSubjectName() === "REDAÇÃO") :
                                        continue;
                                    endif;
                                    ?>
                                    <th>
                                        <h4 class="text-uppercase"><?php echo $baseSubject->getSubjectName(); ?></h4>
                                    </th>
                                <?php endforeach; ?>
                            </tr>
                            <tr>
                            <?php 
                                $i = 0;
                            ?>
                            <?php foreach ($this->baseSubjects as $baseSubject) : ?>
                                <?php 
                                    $baseSubjectId = $baseSubject->getSubjectId();
                                    if ($baseSubject->getSubjectName() === "REDAÇÃO") :
                                        continue;
                                    endif;
                                ?>

                                <td class="base-subject col-xs-3" 
                                    id="base-subject-<?php echo $baseSubjectId; ?>" 
                                    data-id="<?php echo $baseSubjectId; ?>" 
                                    data-name="<?php echo $baseSubject->getSubjectName(); ?>">

                                    <?php foreach ($baseSubject->getChildren() as $subject) : ?>
                                        <?php 
                                            $subjectId = $subject->getSubjectId();
                                        ?>    

                                        <div class="col-xs-12">
                                            <?php echo $subject->getSubjectName(); ?>
                                        </div>
                                        <div class="col-xs-12 quantity-block" 
                                             data-s-id="<?php echo $subjectId; ?>" 
                                             data-quantity="<?php  
                                                if ($this->subjectQuantities !== null 
                                                        && isset($this->subjectQuantities[$baseSubjectId]) /*Base subject existe no array*/
                                                        && isset($this->subjectQuantities[$baseSubjectId][$subjectId])) : /*Subject existe no array*/
                                                    echo $this->subjectQuantities[$baseSubjectId][$subjectId];
                                                endif;
                                                ?>">                                        
                                            <div class="form-group ">
                                                <input type="number" class="col-md-5 col-xs-12 pull-right amount-input form-control" data-old-value="" min="0" value="" disabled>
                                            </div>
                                        </div>
                                        <?php ++$i; ?>

                                    <?php endforeach; ?>
                                </td>

                            <?php endforeach; ?>
                            </tr>
                        </table>
                        <div class="col-md-12"><strong>Total: <span id="question-count">0</span></strong></div>
                        <!-- /.col -->
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            
            <div class="box box-success color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-list" aria-hidden="true"></i> SELEÇÃO DAS QUESTÕES</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="box-body">
                    <?php if ($this->editAllowed) : ?> 
                        <div class="col-md-3 col-xs-12 no-padding" id="subjects">
                            <dl class="col-xs-12 no-padding">
                                <?php foreach ($this->baseSubjects as $baseSubject) : ?>
                                    <div class="base-subject-info no-margin no-padding" 
                                         data-name="<?php echo $baseSubject->getSubjectName(); ?>"
                                         data-id="<?php echo $baseSubject->getSubjectId(); ?>">

                                        <?php foreach ($baseSubject->getChildren() as $subject) : ?>
                                            <dt id="select-<?php echo $subject->getSubjectId(); ?>"
                                                data-name="<?php echo $subject->getSubjectName(); ?>">
                                                    <?php echo $subject->getSubjectName(); ?>
                                                <span class="pull-right">
                                                    <span class="q-added text-green">0</span>
                                                    <?php if ($baseSubject->getSubjectName() !== "REDAÇÃO"): ?>
                                                        /
                                                        <span class="q-amount text-blue"></span>
                                                    <?php endif; ?>
                                                </span>
                                            </dt>
                                            <dd class="col-xs-12" id="subject-<?php echo $subject->getSubjectId() ?>">
                                                <select name="subject" class="col-xs-12 no-padding no-border" multiple>

                                                    <?php
                                                    foreach ($subject->getChildren() as $topic) :

                                                        //  DFS para imprimir a arvore de disciplinas
                                                        $visited = [];
                                                        $stack = new SplStack();
                                                        $stack->push($topic);
                                                        while (!$stack->isEmpty()) :
                                                            $current = $stack->pop();
                                                            if (isset($visited[$current->getSubjectId()])) :
                                                                continue;
                                                            endif;
                                                            $visited[$current->getSubjectId()]
                                                                    = true;
                                                            if (empty($current->getChildren()->toArray())) :
                                                                ?>
                                                                <option value="<?php echo $current->getSubjectId(); ?>">
                                                                    <?php echo $current->getSubjectName(); ?>
                                                                </option>
                                                                <?php
                                                            endif;

                                                            foreach ($current->getChildren()->toArray() as $child) :
                                                                $stack->push($child);
                                                            endforeach;
                                                        endwhile;

                                                    endforeach;
                                                    ?>    
                                                    <option value="<?php echo $subject->getSubjectId(); ?>">SEM TÓPICO DEFINIDO</option>

                                                </select>
                                            </dd>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endforeach; ?>
                            </dl>
                        </div>
                        <div class="col-md-9 col-xs-12" id="questions">
                            <div class="row">
                                <div class="col-xs-4 col-xs-offset-4"> 
                                    <button class="btn-primary btn-block btn btn-success add-question"><span class="glyphicon glyphicon-plus"></span></button>           
                                </div> 
                                <div class="pull-right no-padding"> 
                                    <span class="text-bold text-sm" style="padding-right: 5%;">RECARREGAR QUESTÕES</span>
                                    <i class="fa fa-refresh text-purple" style="font-size: 17px;" id="refresh-button" aria-hidden="true"></i>               
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-condensed table-bordered" id="question-table">
                                    <thead>
                                    <th>Questões</th>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-xs-4 col-xs-offset-4"> 
                                <button class="btn-primary btn-block btn btn-success add-question"><span class="glyphicon glyphicon-plus"></span></button>           
                            </div>
                        </div>
                    <?php else : ?> 
                        <h4 class="text-bold text-uppercase text-center" style="opacity: 0.5">
                            Não é possível selecionar questões pois esse conteúdo está associado a uma ou mais provas.
                        </h4>
                    <?php endif; ?> 
                </div>
                <!-- /.box-body -->
            </div>
            
            <!-- PROVA -->
            <div class="box box-warning color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-file-text-o"></i> PRÉ-VISUALIZAÇÃO DA PROVA </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="box-body">
                    <div class="progress" id="content-load-progress" style="display: none;">
                        <div class="progress-bar progress-bar-green" role="progressbar" style="width: 0%"><span class="sr-only" style="position: static;">0%</span></div>
                    </div>
                    <?php if ($this->editAllowed) : ?> 
                        <div class="do-not-print col-xs-12">
                            <strong><span id="added-questions" class="text-green"></span></strong> questões adicionadas.<br>
                            <strong><span id="remaining-questions" class="text-red"></span></strong> questões restantes.
                        </div>

                        <div class="do-not-print row">  
                            <button class="col-xs-6 col-xs-offset-3 btn btn-success" id="save-content">Salvar Conteúdo</button>
                            <br><br><br><br>
                            <label class="col-xs-12 text-center"><input type='checkbox' id="autosaving" style="margin-right: 5px">Salvar automaticamente a cada mudança</label>
                        </div>
                    <?php endif; ?> 

                    <!-- PREVIEW -->
                    <div id="preview-page" 
                         class=" <?php echo ($this->editAllowed ? '' : 'view-only'); ?>"
                    >
                        <div class="content-questions">
                        </div>
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.box-body -->
            
        </div>
    </div>
</div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/prepare-content';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>