<section class="content">
    <?php
    $this->headLink()->appendStylesheet('/css/exam-print.css', 'all');
    $this->headTitle()->append('Preparação da Aplicação de Prova')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title"><span class="fa fa-book"></span> INSTRUÇÕES</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <ul>
                        <li>
                            A ferramenta de geração automática de simulados ainda está sendo aprimorada, é possível que não haja o melhor aproveitamento de espaço em algumas páginas ou que questões extravasem o limite entre as questões e o rodapé. Uma maneira de tentar solucionar o eventual problema é rearranjando as questões.
                        </li>
                        <li>
                            Para salvar/imprimir corretamente o simulado gerado é necessário remover as margens de impressão do navegador.<br>
                            <strong>Google Chrome</strong>: <br>
                            - Na janela de impressão, clique em "Mais definições" (<i>More settings</i>).<br>
                            - Em "Margens" (<i>Margins</i>), selecione "Nenhum" (<i>None</i>). <br>
                            <strong>Mozilla Firefox</strong>: <br>
                            - Na janela de impressão, clique na aba "Configurar página" (<i>Page Setup</i>).<br>
                            - Clique em "Tamanho do papel" (<i>Paper size</i>).<br>
                            - Selecione "Gerenciar Tamanhos Personalizados..." (<i>Manage Custom Sizes...</i>).<br>
                            - Certifique-se que as dimensões do papel (largura x altura) estão definidas como 210x297mm (A4).<br>
                            - Em "Margens do papel" (<i>Paper Margins</i>), coloque zero em todos os campos.
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
            </div>
            
            <div class="box box-primary color-palette-box">
                <div class="box-header with-border">
                    <h3 class="box-title text-uppercase"><i class="fa fa-list-alt"></i> DETALHES DA APLICAÇÃO </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    </div><!-- /.box-tools -->
                </div>
                <div class="box-body">
                    <div class="col-xs-6">
                        <h5><strong>APLICAÇÃO</strong></h5>
                        <strong>Nome: </strong><?php echo $this->application->getName(); ?><br>
                    </div>
                    <div class="col-xs-6">
                        <h5><strong>PROVAS</strong></h5>
                        <ul>
                            <?php foreach ($this->application->getExams() as $exam) : ?>
                                <li>
                                    <span id="exam-name-input"><?php echo $exam->getName() ?></span>
                                </li>
                                    <?php echo 'Dia: '; ?>
                                    <span id="exam-day">
                                        <?php echo $exam->getDate()->format('d/m/Y'); ?>    
                                    </span><br>
                                    <?php echo 'Hora: '; ?>
                                    <span id="exam-start-time">
                                        <?php echo $exam->getStartTime()->format('H:i'); ?>    
                                    </span> - 
                                    <span id="exam-end-time">
                                        <?php echo $exam->getEndTime()->format('H:i'); ?>    
                                    </span><br> 
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
            
            <!-- GABARITO -->
            <div class="box box-default collapsed-box">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-check-square-o"></i> GABARITO </h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div><!-- /.box-tools -->
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div class="row text-center">
                        <i class="fa fa-info-circle text-blue" style="font-size: 20px; padding-right: 15px;" aria-hidden="true"></i>
                        Escolha orientação horizontal para a folha ao imprimir/salvar o PDF do gabarito.
                        <br><br>
                    </div>
                    <div class="row">
                        <div class="btn-group col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"> 
                            <a class="col-xs-6 btn btn-primary" id="print-answer-key">Gerar PDF</a>
                            <a class="col-xs-6 btn btn-success" id="save-answers-csv" disabled>Gerar CSV</a>
                        </div>
                        <div class="col-xs-10 col-xs-offset-1" id="answer-key-tables">
                        </div>
                    </div> 
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            
            <!-- TEMPLATE DAS INSTRUÇÕES DO SIMULADO -->  
            <script id="instructions-template" type="text/template">      
                <div class="id-goes-here">
                    <div class="text-center">
                        <h3><strong> <span class="i-exam-name"></span> </strong></h3>
                            <span class="i-exam-date"></span> - 
                            <span class="i-begin-time"></span>h às 
                            <span class="i-end-time"></span>h
                            <div class="text-uppercase">
                                <br>
                                <h4>Instruções gerais para a realização da prova</h4>
                            </div>
                            <h4>
                                <br>
                                <strong> Antes de iniciar a resolução da prova, verifique 
                                        se as regras abaixo estão sendo cumpridas.
                                </strong>
                            </h4>
                    </div>
                    <br>
                    <div class="text-justify">
                        <ol> 
                            <li>Não abra a prova até que o fiscal lhe conceda autorização</li>
                            <li>Em sua mesa de prova <strong>não deve constar nada além de lápis, borracha e caneta.</strong></li>
                            <li>Quaisquer materiais que não sejam os descritos acima devem ser deixados à sua direita, no chão.</li>
                            <li><strong>O candidato</strong> que precisar usar o banheiro ou que, por ventura, 
                                    <strong> venha a se sentir mal, deve chamar o fiscal</strong> à sua mesa. <strong>Não</strong>
                                    se levante da mesa sem comunicar o fiscal.
                            </li>
                            <li>Não haverá correção de erros nas questões. Caso esses existam e comprometam o resultado das mesmas, 
                                    as questões erradas serão anuladas posteriormente.
                            </li>
                            <li>A prova tem duração máxima de 4 (quatro) horas. O tempo mínimo de permanência na sala é de 2
                                    <strong> (duas)</strong> horas. Após este período, você receberá uma folha de respostas, 
                                    onde deverá marcar as repostas de <strong>caneta azul ou preta.</strong> Marque somente 
                                    uma resposta para cada questão, caso contrário, tal questão será considerada anulada em 
                                    sua prova. Logo abaixo, você pode verificar como deve ser marcada a resposta que você julgar correta.
                            </li>
                            
                            <div class="col-xs-6 col-xs-offset-3" style="line-height: 15mm;">
                                <div class="col-xs-1" style="font-size: 30pt; line-height: 15mm;"></div>
                                <div class="col-xs-2 text-center" style="font-size: 30pt; padding: 0mm;"> &#9398 </div>
                                <div class="col-xs-2 text-center" style="font-size: 30pt; padding: 0mm;"> &#9399 </div>
                                <div class="col-xs-2 text-center" style="font-size: 30pt; padding: 0mm;"> &#9400 </div>
                                <div class="col-xs-2 text-center" style="font-size: 30pt; padding: 1mm 0 0;"> 
                                        <svg height="38" width="38"><circle cx="19" cy="19" r="19" fill="black" /></svg>
                                </div>
                                <div class="col-xs-2 text-center" style="font-size: 30pt; padding: 0mm;"> &#9402 </div>
                                <div class="col-xs-1" style="font-size: 30pt; line-height: 15mm;"></div>
                            </div>
                            <br><br><br>
                            
                            <li>Caso exista uma questão que você julgue estar sem sentido, sem resposta correta, mais de uma resposta 
                                    correta, ilegível ou algo do gênero, escreva atrás do gabarito o número da questão e o erro encontrado.
                            </li>
                            <li>É recomendável que se deixem pelo menos 30 (trinta) minutos para o preenchimento da folha de resposta. Em 
                                    hipótese alguma o fiscal irá trocá-la e somente ela deverá ser entregue ao fiscal no fim de sua prova. 
                                    Não se esqueça de escrever o número de matrícula na folha de resposta. O caderno de questões ficará com 
                                    você.
                            </li>
                            <li>Antes de iniciar sua prova, espere autorização do fiscal para conferir se todas as páginas estão em seu 
                                    caderno e se todas estão legíveis.
                            </li>
                            <li>Inicie a prova quando houver autorização do fiscal.</li>
                        </ol>
                    </div>
                </div>
            </script> 
            
            <!-- TEMPLATE DA DE CADA PÁGINA (CABEÇALHO, CONTEÚDO, RODAPÉ) -->
            <div class="exam-page">
                <div class="exam-header">
                    <div class="col-xs-3 no-padding">
                        <img class="center-block cats-logo" src="/img/logo_prova.png">
                    </div>
                    <div class="col-xs-9 no-padding">
                        <p class="text-center header-text"><strong>Curso Assistencial Theodomiro Santiago</strong><br>
                            Av. BPS, 1303 - UNIFEI - Campus Professor J.R. Seabra - Sala I.1.2.47 - Itajubá - MG<br>
                            <strong>Tel.:</strong>(38) 98871-2364 | <strong>Email:</strong> catsensino@gmail.com | familiacats.com.br</p>
                    </div>
                </div>
                <div class="exam-content">

                </div>
                <div class="exam-footer">
                    <p><span class="exam-name"></span><span class="page-number pull-right"></span></p>
                </div>
            </div>
            
            <!-- PROVAS -->
            <?php foreach ($this->application->getExams() as $exam) : ?>
                <div class="box box-warning collapsed-box color-palette-box application-content" 
                     id="content-<?php echo $exam->getContent()->getExamContentId(); ?>"
                     data-content-id="<?php echo $exam->getContent()->getExamContentId(); ?>">
                    <div class="box-header with-border">
                        <h3 class="box-title text-uppercase"><i class="fa fa-file-text-o"></i> <?php echo $exam->getName(); ?> </h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                        </div><!-- /.box-tools -->
                    </div>
                    <div class="box-body exam">
                        <div class="do-not-print row">
                            <div class="checkbox text-center">
                                <label><input type="checkbox" class="exam-instructions" checked>Incluir cabeçalho com instruções</label>
                            </div>
                        </div>
                        <div class="do-not-print row">
                            <button class="col-xs-6 col-xs-offset-3 btn btn-success print-exam">Gerar Prova (PDF)</button>
                            <br><br><br><br>
                        </div>

                        <!-- PREVIEW -->
                        <div class="preview-page tex2jax_ignore">
                            <div class="content-questions">
                            </div>
                        </div>

                        <!-- DIV PARA IMPRESSÃO -->
                        <div id="print-page-<?php echo $exam->getContent()->getExamContentId(); ?>">

                        </div> 
                    </div>
                    <!-- /.col -->
                </div>
            
            <?php endforeach; ?>
            
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/exam/prepare-application';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>