<section class="content-header">
    <h1>Criar Advertência</h1>
    <hr>
    <p><?php echo $this->message; ?></p>
</section>

<section class="content">

    <div class="row">
        <?php if ($form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class="form-group">
                    <label for='warning_type_name'>Nome do Tipo de Advertência</label>
                    <?php
                    echo $this->formRow($form->get('warning_type_name'));
                    ?>
                </div>

                <div class="form-group">
                    <label for='warning_type_description'>Descreva este tipo de advertência</label>
                    <?php
                    echo $this->formRow($form->get('warning_type_description'));
                    ?>
                </div>

                <div class="form-group">
                    <?php
                    echo $this->formSubmit($form->get('submit'));
                    ?>
                    <?php echo $this->form()->closeTag(); ?>
                </div>

            </div>
        <?php endif; ?>
    </div>

</section>