<section class="content">
    
    <p><?php echo $message; ?></p>

    <div class="table-responsive col-xs-8 col-md-8 col-md-offset-2">
        <table id="warning-table" class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Tipo</th>
                    <th class="text-center">Descrição</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->warningTypes as $wt): ?>
                    <tr class="cats-row" data-id="<?php echo $wt->getWarningTypeId(); ?>" id="warning-<?php echo $wt->getWarningTypeId(); ?>">
                        <td class="text-center"> <?php echo $wt->getWarningTypeId(); ?></td>
                        <td class="text-center"> <?php echo $wt->getWarningTypeName(); ?></td>
                        <td class="text-center"> <?php echo $wt->getWarningTypeDescription(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/warning/index';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>
