<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->prepend('CatsSys'); ?>
        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath('/img/favicon.ico')))
            // Sans Pro
            ->appendStylesheet('https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic')
            // Bootstrap
            ->appendStylesheet($this->basePath('vendor/bootstrap/dist/css/bootstrap.min.css'))
            // DataTable
            ->appendStylesheet($this->basePath('vendor/datatables.net-bs/css/dataTables.bootstrap.min.css'))
            // Datepicker
            ->appendStylesheet($this->basePath('vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css'))
            // Font Awesome
            ->appendStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
            // Ionicons
            ->appendStylesheet($this->basePath('vendor/Ionicons/css/ionicons.min.css'))
            // Theme style
            ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/AdminLTE.min.css'))
            // AdminLTE Skins
            ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/skins/skin-blue.min.css'))
            ->appendStylesheet($this->basePath('css/app.css'));

        ?>

    </head>
    <body class="skin-blue sidebar-collapse sidebar-mini" style="background: white;">

        <!-- Site wrapper -->
        <div class="wrapper">
            <!-- Right side column. Contains the content of the page -->
            <div class="content-wrapper" style="height: 100% !important;">
                <!-- Main content -->
                <?php echo $this->content; ?>
            </div><!-- /.right-side -->
        </div>
        <script data-main="/js/config" src="/vendor/requirejs/require.js" ></script>
    </body>
</html>
