<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CatsSys'); ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
                // Bootstrap
                ->appendStylesheet($this->basePath('vendor/AdminLTE/bootstrap/css/bootstrap.min.css'))
                // DataTable
                ->appendStylesheet($this->basePath('vendor/AdminLTE/plugins/datatables/dataTables.bootstrap.css'))
                // Datepicker
                ->appendStylesheet($this->basePath('vendor/AdminLTE/plugins/datepicker/datepicker3.css'))
                // Font Awesome
                ->appendStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
                // Ionicons
                ->appendStylesheet($this->basePath('vendor/Ionicons/css/ionicons.min.css'))
                // Theme style
                ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/AdminLTE.min.css'))
                // AdminLTE Skins
                ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/skins/skin-blue.min.css'))
                // DropzoneJS
                ->appendStylesheet($this->basePath('vendor/dropzone/dist/min/dropzone.min.css'));
        ?>

    </head>
    <body class="skin-blue fixed">

        <!-- Wrapper -->
        <div class="wrapper">

            <header class="main-header">

                <a href="<?php echo $this->url('ums/default'); ?>" class="logo">
                    <b>CATS</b>
                </a>

                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" role="navigation">

                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>

                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="/img/user.png" class="user-image" alt="User Image"/>
                                    <span class="hidden-xs">Usuário</span>
                                </a>

                                <?php
                                $userInfo = $this->userInfo();
                                $userActiveRole = ucwords($userInfo['activeRole']);
                                $userRoles = $userInfo['allRoles'];
                                ?>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <img src="/img/user.png" class="img-circle" alt="User Image" />
                                        <p>
                                            Usuário - <?php echo $userActiveRole; ?>
                                            <small>Membro Desde Nov. 2011</small>
                                        </p>
                                    </li>

                                    <!-- Menu Body -->
                                    <li class="user-body">
                                        <?php foreach ($userInfo['allRoles'] as $userRole): ?>
                                            <?php
                                            $userRole = ucwords($userRole);
                                            if ($userRole != $userActiveRole):
                                                ?>
                                                <div class="col-xs-3 text-center">
                                                    <a href="#"><i class="fa fa-fw fa-user"></i> <span class='role'><?php echo $userRole ?></span> </a>
                                                </div>

                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $this->url('authentication/login', array('action' => 'logout')); ?>"  class="btn btn-default btn-flat">
                                                <i class="fa fa-fw fa-power-off"></i>Sair </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- sidebar menu: : style can be found in sidebar.less -->

                    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                    <ul class="sidebar-menu">
                        <li>
                            <a href="<?php echo $this->url('ums/default', array('action' => 'index')) ?>"><i class="fa fa-fw fa-dashboard"></i> UMS</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ion-ios-unlocked-outline"></i>
                                <span>Autenticação</span>
                                <i class="pull-right fa fa-circle-thin"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('authentication/user', array('action' => 'index')) ?>">Show All Users</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authentication/user', array('action' => 'create')) ?>">Create New User</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ion-ios-unlocked-outline"></i>
                                <span>Autorização</span>
                                <i class="pull-right fa fa-circle-thin"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'index')) ?>">Ver Papéis</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'create')) ?>">Criar Papel</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'add-role-to-user')) ?>">Associar Papel</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/resource', array('action' => 'index')) ?>">Ver Recursos</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/resource', array('action' => 'create')) ?>">Criar Recurso</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/privilege', array('action' => 'index')) ?>">Ver Privilégios</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/privilege', array('action' => 'create')) ?>">Criar Privilégio</a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa fa-users"></i>
                                <span>Processo Seletivo</span>
                                <i class="pull-right fa fa-circle-thin"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('recruitment/recruitment', array('action' => 'index')); ?>"> Ver Processos Seletivos </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('recruitment/recruitment', array('action' => 'create')); ?>"> Criar Processo Seletivo </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('recruitment/registration', array('action' => 'studentRegistration')); ?>"> Formulário de Inscrição (Alunos) </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('recruitment/registration', array('action' => 'showStudentRegistrations')); ?>"> Inscrições (Alunos) </a>
                                </li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">
                                <i class="fa fa-users"></i>
                                <span>Gestão Escolar</span>
                                <i class="pull-right fa fa-circle-thin"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('school-management/student-class', array('action' => 'create')); ?>"> Criar Turma </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('school-management/student-class', array('action' => 'index')); ?>"> Ver Turmas </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('school-management/enrollment', array('action' => 'index')); ?>"> Matricular Alunos </a>
                                </li>

                                <li>
                                    <a href="<?php echo $this->url('school-management/school-warning', array('action' => 'create')); ?>"> Criar Advertência </a>
                                </li>

                                <li>
                                    <a href="<?php echo $this->url('school-management/school-warning', array('action' => 'index')); ?>"> Ver Advertências </a>
                                </li>

                            </ul>
                        </li>

                    </ul>
                    <!-- /.navbar-collapse -->

                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the content of the page -->
            <div class="content-wrapper">
                <!-- Main content -->
                <?php echo $this->content; ?>

            </div><!-- /.right-side -->

            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Versão</b> 0.1
                </div>
                <strong>&copy 2003-<?php echo date('Y'); ?> <a href="http://www.familiacats.com.br/">CATS</a>.</strong> Todos os direitos reservados.
            </footer>


            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- Home tab content -->
                    <div class="tab-pane active" id="control-sidebar-home-tab">
                        <h3 class="control-sidebar-heading">Ações</h3>


                        <?php if (isset($toolbar) && is_array($toolbar)): ?>
                            <ul class="control-sidebar-menu cats-toolbar">
                                <?php foreach ($toolbar['menu'] as $item): ?>
                                    <li class="cats-toolbar-item" 
                                        data-fntype="<?php echo $item['fntype']; ?>" 
                                        data-title="<?php echo $item['title']; ?>"
                                        >
                                        <a href="<?php echo $item['url']; ?>" 
                                        <?php echo empty($item['target']) ? '' : 'target="' . $item['target'] . '" '; ?>
                                        <?php echo empty($item['id']) ? '' : 'id="' . $item['id'] . '" '; ?>
                                           >
                                            <i class="menu-icon <?php echo $item['class']; ?>"></i>
                                            <div class="menu-info">
                                                <h4 class="control-sidebar-subheading text-center"><?php echo $item['title']; ?></h4>
                                                <p class="text-center"><?php echo $item['description']; ?></p>
                                            </div>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php else: ?>
                            <p>Esta página não possui ações disponíveis.</p>
                        <?php endif; ?>
                    </div>
                </div>
            </aside>

            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>

            <script>
                var AdminLTEOptions = {
                    //Add slimscroll to navbar menus
                    //This requires you to load the slimscroll plugin
                    //in every page before app.js
                    navbarMenuSlimscroll: true,
                    navbarMenuSlimscrollWidth: "3px", //The width of the scroll bar
                    navbarMenuHeight: "200px", //The height of the inner menu
                    //General animation speed for JS animated elements such as box collapse/expand and
                    //sidebar treeview slide up/down. This options accepts an integer as milliseconds,
                    //'fast', 'normal', or 'slow'
                    animationSpeed: 500,
                    //Sidebar push menu toggle button selector
                    sidebarToggleSelector: "[data-toggle='offcanvas']",
                    //Activate sidebar push menu
                    sidebarPushMenu: true,
                    //Activate sidebar slimscroll if the fixed layout is set (requires SlimScroll Plugin)
                    sidebarSlimScroll: true,
                    //Enable sidebar expand on hover effect for sidebar mini
                    //This option is forced to true if both the fixed layout and sidebar mini
                    //are used together
                    sidebarExpandOnHover: false,
                    //BoxRefresh Plugin
                    enableBoxRefresh: true,
                    //Bootstrap.js tooltip
                    enableBSToppltip: true,
                    BSTooltipSelector: "[data-toggle='tooltip']",
                    //Enable Fast Click. Fastclick.js creates a more
                    //native touch experience with touch devices. If you
                    //choose to enable the plugin, make sure you load the script
                    //before AdminLTE's app.js
                    enableFastclick: false,
                    //Control Sidebar Options
                    enableControlSidebar: true,
                    controlSidebarOptions: {
                        //Which button should trigger the open/close event
                        toggleBtnSelector: "[data-toggle='control-sidebar']",
                        //The sidebar selector
                        selector: ".control-sidebar",
                        //Enable slide over content
                        slide: false
                    },
                    //Box Widget Plugin. Enable this plugin
                    //to allow boxes to be collapsed and/or removed
                    enableBoxWidget: true,
                    //Box Widget plugin options
                    boxWidgetOptions: {
                        boxWidgetIcons: {
                            //Collapse icon
                            collapse: 'fa-minus',
                            //Open icon
                            open: 'fa-plus',
                            //Remove icon
                            remove: 'fa-times'
                        },
                        boxWidgetSelectors: {
                            //Remove button selector
                            remove: '[data-widget="remove"]',
                            //Collapse button selector
                            collapse: '[data-widget="collapse"]'
                        }
                    },
                    //Direct Chat plugin options
//                    directChat: {
//                        //Enable direct chat by default
//                        enable: true,
//                        //The button to open and close the chat contacts pane
//                        contactToggleSelector: '[data-widget="chat-pane-toggle"]'
//                    },
                    //Define the set of colors to use globally around the website
                    colors: {
                        lightBlue: "#3c8dbc",
                        red: "#f56954",
                        green: "#00a65a",
                        aqua: "#00c0ef",
                        yellow: "#f39c12",
                        blue: "#0073b7",
                        navy: "#001F3F",
                        teal: "#39CCCC",
                        olive: "#3D9970",
                        lime: "#01FF70",
                        orange: "#FF851B",
                        fuchsia: "#F012BE",
                        purple: "#8E24AA",
                        maroon: "#D81B60",
                        black: "#222222",
                        gray: "#d2d6de"
                    },
                    //The standard screen sizes that bootstrap uses.
                    //If you change these in the variables.less file, change
                    //them here too.
                    screenSizes: {
                        xs: 480,
                        sm: 768,
                        md: 992,
                        lg: 1200
                    }
                };
            </script>

            <?php
            echo $this->inlineScript()
                    //DropzoneJS
                    ->prependFile($this->basePath('vendor/dropzone/dist/min/dropzone.min.js'))
                    // BootboxJS
                    ->prependFile($this->basePath('vendor/bootbox.js/bootbox.js'))
                    // AdminLTE App
                    ->prependFile($this->basePath('vendor/AdminLTE/dist/js/app.min.js'))
                    // SlimScroll Plugin
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js'))
                    //DataTable
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js'))
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/datatables/jquery.dataTables.min.js'))
                    // Datepicker
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/datepicker/locales/bootstrap-datepicker.pt-BR.js'))
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/datepicker/bootstrap-datepicker.js'))
                    ->prependFile($this->basePath('vendor/moment/min/moment.min.js'))
                    // Bootstrap 3.3.5
                    ->prependFile($this->basePath('vendor/AdminLTE/bootstrap/js/bootstrap.min.js'))
                    // jQuery 2.1.4
                    ->prependFile($this->basePath('vendor/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js'));
            ?>

            <style>
                .cats-selected-bg {
                    background-color: #d2d6de;
                }
                .table {
                    cursor: pointer;
                }

                .btn-file {
                    position: relative;
                    overflow: hidden;
                }
                .btn-file input[type=file] {
                    position: absolute;
                    top: 0;
                    right: 0;
                    min-width: 100%;
                    min-height: 100%;
                    font-size: 100px;
                    text-align: right;
                    filter: alpha(opacity=0);
                    opacity: 0;
                    outline: none;
                    background: white;
                    cursor: inherit;
                    display: block;
                }

            </style>

            <script>

                /**
                 * @todo Transformar os seletores hardcoded (i.e. '.cats-toolbar', ...) em parâmetros globais
                 * 
                 */
                var toolbarConfig = (function (elements) {

                    var fnTypes = {};

                    initClick = function () {

                        $('.cats-toolbar').on('click', '.cats-toolbar-item', function (e) {
                            // nenhuma ação é executada se não estiver especificada abaixo
                            e.preventDefault();
                            var fnType = $(this).data('fntype');
                            if (fnTypes.hasOwnProperty(fnType)) {
                                fnTypes[fnType].call(this, $(this));
                            } else {
                                bootbox.alert('fnType: (' + fnType + ') não definida.');
                            }
                        });
                    };
                    fnTypes.selectedHttpClick = function (toolbarItem) {
                        var selectedResult = getSelectedItemInfo(toolbarItem);
                        if (selectedResult !== null) {
                            window.open(selectedResult.url, selectedResult.target);
                        } else {
                            bootbox.alert('Nenhuma item (ex: linha de uma tabela) foi escolhido.');
                        }
                    };
                    fnTypes.selectedAjaxClick = function (toolbarItem) {

                        bootbox.confirm('Tem certeza que deseja executar ' +
                                'esta ação? (' + toolbarItem.data('title') + ')', function (result) {
                            if (result) {
                                var selectedResult = getSelectedItemInfo(toolbarItem);
                                if (selectedResult !== null) {
                                    $.ajax({
                                        url: selectedResult.url,
                                        type: 'GET',
                                        success: function (data) {
                                            bootbox.alert(data.message);
                                        },
                                        error: function (jqXHR, textStatus, errorThrown) {
                                            bootbox.alert(textStatus);
                                        }
                                    });
                                } else {
                                    bootbox.alert('Nenhuma item (ex: linha de uma tabela) foi escolhido.');
                                }
                            } else {
                                bootbox.alert('Ação abortada.');
                            }
                        });
                    };

                    fnTypes.ajaxClick = function (toolbarItem) {
                        bootbox.confirm('Tem certeza que deseja executar ' +
                                'esta ação? (' + toolbarItem.data('title') + ')', function (result) {
                            if (result) {
                                var itemInfo = getItemInfo(toolbarItem);

                                $.ajax({
                                    url: itemInfo.url,
                                    type: 'GET',
                                    success: function (data) {
                                        bootbox.alert(data.message);
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        bootbox.alert(textStatus);
                                    }
                                });

                            } else {
                                bootbox.alert('Ação abortada.');
                            }
                        });
                    };

                    getSelectedItemInfo = function (toolbarItem) {
                        if ($('.cats-selected-row').length > 0) {
                            var item = toolbarItem.find('a');
                            var url = item.attr('href');
                            var target = item.attr('target');
                            url = url.replace('$id', $('.cats-selected-row').data('id'));

                            return {
                                url: url,
                                target: (typeof target !== 'undefined' ? target : '_self')
                            };
                        }

                        return null;
                    };

                    getItemInfo = function (toolbarItem) {
                        var item = toolbarItem.find('a');
                        var url = item.attr('href');
                        var target = item.attr('target');

                        return {
                            url: url,
                            target: (typeof target !== 'undefined' ? target : '_self')
                        };
                    };

                    // toolbar actions

                    return {
                        init: function () {
                            initClick();
                        }
                    };
                }());
            </script>

            <script>

                // fileselect event
                $(document).on('change', '.btn-file :file', function () {
                    var input = $(this),
                            numFiles = input.get(0).files ? input.get(0).files.length : 1,
                            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                    input.trigger('fileselect', [numFiles, label]);
                });
                // change user active role
                $(document).ready(function () {

                    //                $('.main-footer').show();
                    $('.role').on('click', function () {
                        var role = $(this);
                        var jsonRole = JSON.stringify({
                            'role': role.text().toLowerCase()
                        });
                        $.ajax({
                            url: '<?php echo $this->url('authorization/role', array('action' => 'changeActiveUserRole')); ?>',
                            type: 'POST',
                            dataType: 'json',
                            async: true,
                            data: jsonRole,
                            success: function (msg) {

                                // change role in menu
                                if (msg.success) {
                                    var newActiveRole = role.text();
                                    role.text($('.active-role').text());
                                    $('.active-role').text(newActiveRole);
                                }

                                console.log(msg);
                            },
                            error: function (msg) {
                                console.log(msg);
                            }
                        });
                    });
                    var url = window.location;
                    // Will only work if string in href matches with location
                    $('ul.sidebar-menu a[href="' + url.pathname + '"]')
                            .closest('ul')
                            .addClass('menu-open')
                            .css('display', 'block')
                            .closest('li')
                            .addClass('active');
                    // select row on click
                    $('table').on('click', '.cats-row', function () {
                        $(this).siblings('tr')
                                .removeClass('cats-selected-row')
                                .find('td')
                                .removeClass('cats-selected-bg');

                        $(this).toggleClass('cats-selected-row');

                        $(this).find('td').toggleClass('cats-selected-bg');
                        if ($(this).hasClass('cats-selected-row')) {
                            if (!$('body').hasClass('control-sidebar-open')) {
                                $('body').addClass('control-sidebar-open');
                            }
                        } else {
                            $('body').removeClass('control-sidebar-open');
                        }
                    });
                    $('.btn-file :file').on('fileselect', function (event, numFiles, label) {
                        $(this).closest('div').siblings('.file-label').text(label);
                    });
                    if (typeof toolbarConfig !== 'undefined') {
                        toolbarConfig.init();
                    }
                    if (typeof standardConfig !== 'undefined') {
                        standardConfig.init();
                    }
                });
            </script>
    </body>
</html>
