<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CatsSys'); ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
                // Bootstrap
                ->appendStylesheet($this->basePath('vendor/AdminLTE/bootstrap/css/bootstrap.min.css'))
                // Font Awesome
                ->appendStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
                // Ionicons
                ->appendStylesheet($this->basePath('vendor/Ionicons/css/ionicons.min.css'))
                // Theme style
                ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/AdminLTE.min.css'))
                // AdminLTE Skins
                ->appendStylesheet($this->basePath('vendor/AdminLTE/dist/css/skins/skin-blue.min.css'));
        ?>
    </head>
    <body class="skin-blue fixed">

        <!-- Wrapper -->
        <div class="wrapper">

            <header class="main-header">

                <a href="<?php echo $this->url('ums/default'); ?>" class="logo">
                    <b>CATS</b>
                </a>

                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top" role="navigation">

                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>

                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account: style can be found in dropdown.less -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="/img/user.png" class="user-image" alt="User Image"/>
                                    <span class="hidden-xs">Usuário</span>
                                </a>

                                <?php
                                $userInfo = $this->userInfo();
                                $userActiveRole = ucwords($userInfo['activeRole']);
                                $userRoles = $userInfo['allRoles'];
                                ?>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <img src="/img/user.png" class="img-circle" alt="User Image" />
                                        <p>
                                            Usuário - <?php echo $userActiveRole; ?>
                                            <small>Membro Desde Nov. 2011</small>
                                        </p>
                                    </li>

                                    <!-- Menu Body -->
                                    <li class="user-body">
                                        <?php foreach ($userInfo['allRoles'] as $userRole): ?>
                                            <?php
                                            $userRole = ucwords($userRole);
                                            if ($userRole != $userActiveRole):
                                                ?>
                                                <div class="col-xs-3 text-center">
                                                    <a href="#"><i class="fa fa-fw fa-user"></i> <span class='role'><?php echo $userRole ?></span> </a>
                                                </div>

                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="<?php echo $this->url('authentication/login', array('action' => 'logout')); ?>"  class="btn btn-default btn-flat">
                                                <i class="fa fa-fw fa-power-off"></i>Sair </a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">

                    <!-- sidebar menu: : style can be found in sidebar.less -->

                    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                    <ul class="sidebar-menu">
                        <li>
                            <a href="<?php echo $this->url('ums/default', array('action' => 'index')) ?>"><i class="fa fa-fw fa-dashboard"></i> UMS</a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-fw fa-arrows-v"></i>
                                <span>Authentication</span>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('authentication/user', array('action' => 'index')) ?>">Show All Users</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authentication/user', array('action' => 'create')) ?>">Create New User</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-fw fa-arrows-v"></i>
                                <span>Authorization</span>
                            </a>
                            <ul class="treeview-menu">
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'index')) ?>">Ver Papéis</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'create')) ?>">Criar Papel</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/role', array('action' => 'add-role-to-user')) ?>">Associar Papel</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/resource', array('action' => 'index')) ?>">Ver Recursos</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/resource', array('action' => 'create')) ?>">Criar Recurso</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/privilege', array('action' => 'index')) ?>">Ver Privilégios</a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('authorization/privilege', array('action' => 'create')) ?>">Criar Privilégio</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <!-- /.navbar-collapse -->

                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the content of the page -->
            <div class="content-wrapper">

<!--                <section class="content-header">
     Page title and breadcrumbs go here 
</section> /.content-header -->

                <!-- Main content -->
                <section class="content">
                    <?php echo $this->content; ?>
                </section><!-- /.content -->
            </div><!-- /.right-side -->

            <footer class="main-footer" style="display:none;">
                <div class="pull-right hidden-xs">
                    <b>Versão</b> 0.1
                </div>
                <strong>&copy 2003-<?php echo date('Y'); ?> <a href="http://www.familiacats.com.br/">CATS</a>.</strong> Todos os direitos reservados.
            </footer>
        </div>

        <?php
        echo $this->inlineScript()
                // AdminLTE App
                ->prependFile($this->basePath('vendor/AdminLTE/dist/js/app.min.js'))
                // Bootstrap 3.3.5
                ->prependFile($this->basePath('vendor/AdminLTE/bootstrap/js/bootstrap.min.js'))
                // jQuery 2.1.4
                ->prependFile($this->basePath('vendor/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js'));
        ?>

        <script>
            // change user active role
            $(document).ready(function () {

                $('.main-footer').show();

                $('.role').on('click', function () {
                    var role = $(this);
                    var jsonRole = JSON.stringify({
                        'role': role.text().toLowerCase()
                    });

                    $.ajax({
                        url: '<?php echo $this->url('authorization/role', array('action' => 'changeActiveUserRole')); ?>',
                        type: 'POST',
                        dataType: 'json',
                        async: true,
                        data: jsonRole,
                        success: function (msg) {

                            // change role in menu
                            if (msg.success) {
                                var newActiveRole = role.text();
                                role.text($('.active-role').text());
                                $('.active-role').text(newActiveRole);
                            }

                            console.log(msg);

                        },
                        error: function (msg) {
                            console.log(msg);
                        }
                    });
                });
            });

        </script>
    </body>
</html>
