<section class="content">

    <p><?php echo $this->message; ?></p>

    <div class="row">
        <?php if ($form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('class_name')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('class_begin_date')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('class_end_date')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('Submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>

            </div>
        <?php endif; ?>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/class/create';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>