<section class="content">

    <p><?php echo $this->message; ?></p>

    <div class="row">
        <?php if ($form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('class_name')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('class_begin_date')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('class_end_date')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('Submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>

            </div>
        <?php endif; ?>
    </div>

</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDatepickers = function () {
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                setDate: moment().format('DD/MM/YYYY'),
                startDate: moment().format('DD/MM/YYYY'),
                endDate: moment().add(2, 'years').format('DD/MM/YYYY'),
                startView: 0,
                autoclose: true,
                language: 'pt-BR'
            });
        };

        return {
            init: function () {
                initDatepickers();
            }
        };

    }());


</script>