<section class="content">

    <p><?php echo $message; ?></p>

    <div class="table-responsive col-xs-8 col-md-8 col-md-offset-2">
        <table id="class-table" class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Turma</th>
                    <th class="text-center">Data de Início</th>
                    <th class="text-center">Data de Término</th>
                    <th class="text-center">Nº de Alunos</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->classes as $class): ?>
                    <tr class="cats-row" data-id="<?php echo $class->getClassId(); ?>">
                        <td class="text-center"> <?php echo $class->getClassId(); ?></td>
                        <td class="text-center"> <?php echo $class->getClassName(); ?></td>
                        <td class="text-center"> <?php echo $class->getClassBeginDate()->format('d/m/Y'); ?></td>
                        <td class="text-center"> <?php echo $class->getClassEndDate()->format('d/m/Y'); ?></td>
                        <td class="text-center"> <?php echo $class->getEnrollments()->count(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/class/index';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>

