<section class="content">
    <?php 
    if ($pdf !== null) :
        $pdf->Output('Carteirinhas', 'I', true);
    else :
    ?>
        <p><?php echo $this->message; ?></p>
        
        <form method="POST">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                    <div class="box box-warning">
                        <div class="box-header with-border">
                            <h3 class="box-title">Data de validade</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i> </button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <?php if ($this->form !== null) :
                                $expiryDateElement = $form->get('expiry_date');

                                echo $this->formElementErrors($expiryDateElement, array('class' => 'text-bold text-red'));
                            endif; ?>
                            
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div id="expiry-date"></div>
                                    </div>
                                </div>
                            </div>
                            
                            <input type="hidden" name="expiryDate" id="expiry-date-input">
                            
                        </div>
                        <!-- /.box-body -->
                    </div>

                    <div class="box box-success">
                        <div class="box-header with-border">
                            <h3 class="box-title">Fundo da carteirinha</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i> </button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <?php if ($this->form !== null) : 
                                $bgConfigElement = $form->get('config_id');

                                echo $this->formElementErrors($bgConfigElement, array('class' => 'text-bold text-red'));
                            endif; ?>
                            
                            <?php 
                                echo $this->partial(
                                    'student-bg-configs/template', 
                                    [
                                        'configs' => $this->configs,
                                    ]
                                );
                            ?>
                            
                            <input type="hidden" name="bgConfigId" id="bg-config-id-input">
                        </div>
                        <!-- /.box-body -->
                    </div>

                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title">Turma</h3>

                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                            </div>
                            <!-- /.box-tools -->
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="row">
                                <div class="col-xs-8 col-md-10">
                                    <div class="form-group">
                                        <select class="form-control" id="class-select">
                                            <?php foreach ($classes as $class) :?>
                                                <option value="<?php echo $class->getClassId(); ?>"><?php echo $class->getClassName(); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xs-4 col-md-2">
                                    <button type="button" class="btn bg-green btn-block" id="fetch-class-students">Buscar alunos</button>
                                </div>
                            </div>
                            <hr>
                            <div class="col-xs-10 col-xs-offset-1 margin-bottom">
                                <div class="col-xs-6">
                                    <button type="button" class="btn bg-blue btn-block" id="select-all-students">Selecionar todos os alunos</button>
                                </div>
                                <div class="col-xs-6">
                                    <button type="button" class="btn bg-blue btn-block" id="unselect-all-students">Desselecionar todos os alunos</button>
                                </div>
                            </div>

                            <table id="students-table" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th class="text-center col-xs-8">Nome</th>
                                        <th class="text-center col-xs-4">CPF</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <div class="col-xs-6 col-xs-offset-3">
                        <button type="submit" class="btn btn-block bg-green" id="generate-id-cards">Gerar carteirinhas</button>
                    </div>
                </div>
            </div>
        </form>
    <?php endif; // pdf ?>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/documents/generate-pdf/student-id-card';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>