<section class="content">
    <?php 
    if ($pdf !== null) {
        $pdf->Output('Carteirinhas', 'I', true);
    }
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <?php if ($this->form !== null): ?>
            <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                    <?php echo $this->formRow($form->get('config_id')); ?>
                    <?php echo $this->formRow($form->get('class_id')); ?>
                    <?php echo $this->formRow($form->get('expiry_date')); ?>
                    <?php echo $this->formRow($form->get('Submit')); ?>
                <?php echo $this->form()->closeTag(); ?>
            </div>

        <?php endif; ?>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/documents/generate-pdf/student-id-card';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>