<section class="content">
    
    <?php 
    if ($pdf !== null) :
        $pdf->Output('Quadro de Alunos', 'I', true); 
    endif;
    ?>
    
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2"> 
            <?php if ($this->form !== null) :
                echo $this->form($form);
            endif; ?>
        </div>
    </div>

</section>
