<section class="content">

    <h3>Preparação</h3>
    <ol>
        <li>Entrevistadores (separados por ; ou ,) [Escrivão; Entrevistador 1; Entrevistador 2]
            <br>
            Escrivão: Aquele que preencheu o formulário durante a entrevista
            Entrevistadores: Aqueles que conversaram diretamente com o candidato.
        </li>
        <li>Hora de início (Marque o horário em que recebeu a ficha do candidato para análise).</li>
    </ol>

    <h3>ESTUDO DO CASO</h3>

    <ol>
        <li>Exibir nome do candidato</li>
        <li>Hora de início (Marque o horário em que recebeu a ficha do candidato para análise).</li>
    </ol>

    <h3>CONTATO DIRETO COM O CANDIDATO</h3>

    <h4>1º MOMENTO – INTRODUÇÃO</h4>

    <h5>Para iniciar a entrevista, e manter o clima leve, neste momento iniciaremos as apresentações.</h5>

    <ol>
        <li>
            É importante que o candidato fique o mais relaxado possível, por isso o tom que a conversa toma é fundamental. 

            Ao se sentir pressionado, emoções como nervosismo e angústia  podem fazer com que as respostas do candidato sejam curtas, secas ou incompletas, atrapalhando a análise da responsabilidade, interesse e foco.
        </li>
        <li>Apresentações
            <ul>
                <li>Apresentem-se, falem sobre si mesmos, o que estudam, onde estudam, o que fazem no CATS.</li>
                <li>Pergunte ao candidato sobre o CATS, e posteriormente explique nosso funcionamento (assistencial, voluntariado, mensalidade, horários, datas, simulados)</li>
                <li>Fale para o candidato sobre a entrevista, explique sobre esse momento inicial de apresentação, sobre o segundo momento sobre a situação socioeconômica, e um terceiro sobre o candidato como estudante.</li>
                <li>Leia sobre como o candidato conheceu o processo seletivo e se conhece alguém que que já cursou o CATS. Peça para ele comentar. A partir de agora, o foco da conversa estará no candidato.</li>
            </ul>
        </li>
    </ol>


    <h5>Comentários e visões do entrevistador.</h5>

    <ol>
        <li>Sobre a postura do candidato, se está nervoso, como reagiu às perguntas.</li>
    </ol>

    <h4>2º MOMENTO - AVALIAÇÃO SOCIOECONÔMICA</h4>

    <p>
        De acordo com as respostas da pré-entrevista, indicada em cada bloco, peça para que ele as comente e em qualquer momento de dúvida em alguma resposta você (entrevistador) fique à vontade para questioná-lo. Aproveite para esclarecer possíveis questões em aberto do questionário.
    </p>

    <ol>
        <li>Situação da casa e localização</li>
        <li>Bens e despesas básicas.</li>
        <li>Membros da família e renda</li>
        <li>Problemas com os membros (Procure por vícios, drogas. Doenças graves ou crônicas.)</li>
        <li>Membros da família e sua relação e pensamento sobre os estudos/trabalho (Verificar o apoio dado ao candidato.)</li>
        <li>Trabalhos do candidato e rotina atual (atividades e hábitos)</li>
        <li>Histórico escolar e comportamento como aluno</li>
        <li>Cursos técnicos, profissionalizantes, de idioma, etc.</li>
        <li>Rotina de estudos e melhores formas de estudar (horas por semana, agenda, estudar por tarefas)</li>
        <li>Cursinho pré-vestibular. Verifique se o candidato já fez simulados, vestibulares e concursos. Converse sobre suas experiências.</li>

    </ol>

    <h4> PERFIL COMO ESTUDANTE/ FOCO</h4>

    <p>Aqui as perguntas são diretas, o formato da conversa será quase um quiz.O candidato irá se sentir pressionado e provavelmente ficará nervoso ou mais tímido. Esses sentimentos também interferem nas respostas negativamente, fique atento para não tornar o clima pesado demais.</p>

    <ol>
        <li>Por que quer ser aluno?</li>
        <li>  Quais são seus objetivos?</li>
        <li>  Por que quer ingressar no Ensino Superior?</li>
        <li>  Já possui algum curso ou área em mente?</li>
        <li>  O que você acha que precisa fazer para conseguir alcançar os seus objetivos (com a rotina que possui)?
            <ul>
                <li>
                    Salientar para candidatos que estão no 3º ano do ensino médio e para aqueles que trabalham ou pretendem trabalhar),
                </li>
            </ul>
        </li>
        <li>  Vai conseguir dar conta? Por que?</li>
    </ol>

    <ol>
        <li>Comentários e visões do entrevistador (Sobre os objetivos do candidato).</li>
        <li> Sobre as atividades do CATS
            <ul>
                <li>Você frequentará as aulas de sábado?/li>
                <li>Você frequentará as monitorias?/li>
                <li>Você frequentará os simulados?</li>
                <li>Você acredita que será capaz de manter o pagamento durante o ano da mensalidade? Você assume o compromisso de manter um diálogo com o diretor financeiro, caso não possa pagar?</li>
                <li>Você acredita merecer a dedicação de todos os voluntários? Por quê?</li>
                <li>Por que devemos escolher você dentre tantos outros candidatos?</li>
                <li>Se ex-aluno, por que dar esta oportunidade a você de novo?</li>
            </ul>
        </li>
        <li>Comentários e visões do entrevistador (Sobre as atividades do CATS.)</li>
    </ol>
    
    
    
</section>
