<section class="content">

    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">CANDIDATO</h3>
                </div>
                <div class="box-body">
                    <p><?php echo $this->person->getPersonName(); ?></p>
                </div>
            </div>


            <?php echo $this->form()->openTag($form); ?>
            <?php $interview = $form->get('studentInterview'); ?>

            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">PREPARAÇÃO</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-4 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewBeginDate')); ?>
                    </div>

                    <div class="col-md-8 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewers')); ?>
                    </div>
                </div>
            </div>

            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">CONTATO COM O CANDIDATO</h3>
                </div>
                <div class="box-body">

                    <h4 class="text-center">Introdução</h4>
                    <hr>
                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewerCommentIntro')); ?>
                    </div>
                    <div class="col-md-6 col-md-12">
                        <p><b>Para iniciar a entrevista, e manter o clima leve, neste momento iniciaremos as apresentações.</b></p>
                        <ol>
                            <li> É importante que o candidato fique o mais relaxado possível, 
                                por isso o tom que a conversa toma é fundamental. Ao se sentir pressionado, 
                                emoções como nervosismo e angústia  podem fazer com que as respostas do candidato sejam curtas, 
                                secas ou incompletas, atrapalhando a análise da responsabilidade, interesse e foco.
                            </li>
                            <li>
                                <ul>
                                    <li>Apresentem-se, falem sobre si mesmos, o que estudam, onde estudam, 
                                        o que fazem como voluntários.
                                    </li>
                                    <li>Pergunte ao candidato sobre o que ele conhece de nós, posteriormente, 
                                        explique funcionamento: assistencial, voluntariado, mensalidade, horários, datas, simulados.
                                    </li>
                                    <li>Fale para o candidato sobre o roteiro da entrevista 
                                        (Introdução, Avaliação Socioeconômica e Perfil de Estudante).
                                    </li>
                                    <li>Leia como o candidato conheceu o processo seletivo e se conhece alguém que já foi aluno. 
                                        Peça para ele comentar. Neste momento, o foco da conversa estará no candidato.
                                    </li>
                                </ul>
                            </li>
                        </ol>
                    </div>
                    <h4 class="text-center">Avaliação Socioeconômica</h4>
                    <hr>

                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewerCommentSocioeconomic')); ?>
                    </div>

                    <div class="col-md-6 col-xs-12">
                        <p>
                            <b>
                                De acordo com as respostas da pré-entrevista, peça para que 
                                ele as comente e, em qualquer momento de dúvida em alguma 
                                resposta você (entrevistador), fique à vontade para questioná-lo. Aproveite 
                                para esclarecer possíveis questões em aberto do questionário.
                            </b>
                        </p>

                        <ol>
                            <li>
                                Situação da casa e localização
                            </li>
                            <li>
                                Bens e despesas básicas.
                            </li>
                            <li>
                                Membros da família e renda
                            </li>
                            <li>
                                Problemas com os membros (Procure por vícios, drogas. Doenças graves ou crônicas.)
                            </li>
                            <li>
                                Membros da família e sua relação e pensamento sobre os estudos/trabalho 
                                (Verificar o apoio dado ao candidato.)
                            </li>
                            <li>
                                Trabalhos do candidato e rotina atual (atividades e hábitos)
                            </li>
                            <li>
                                Histórico escolar e comportamento como aluno
                            </li>
                            <li>
                                Cursos técnicos, profissionalizantes, de idioma, etc.
                            </li>
                            <li>
                                Rotina de estudos e melhores formas de estudar 
                                (horas por semana, agenda, estudar por tarefas)
                            </li>
                            <li>
                                Cursinho pré-vestibular. Verifique se o candidato já fez simulados, 
                                vestibulares e concursos. Converse sobre suas experiências.
                            </li>
                        </ol>
                    </div>

                    <h4 class="text-center">Perfil de Estudante</h4>
                    <hr>


                    <div class="col-md-6 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewerCommentStudent')); ?>
                    </div>

                    <div class="col-md-6 col-xs-12">
                        <p>
                            <b>Aqui as perguntas são diretas, o formato da conversa será quase um quiz. O candidato irá se 
                                sentir pressionado e provavelmente ficará nervoso ou mais tímido. Esses sentimentos também 
                                interferem, negativamente, nas respostas. Fique atento para não tornar o clima muito pesado.
                            </b>
                        </p>

                        <ol>
                            <li>Por que quer ser aluno?</li>
                            <li>Quais são seus objetivos?</li>
                            <li>Por que quer ingressar no ensino superior?</li>
                            <li>Já possui algum curso ou área em mente?</li>
                            <li>O que você acha que precisa fazer para conseguir alcançar os seus objetivos (com a rotina que possui)?
                                <ul>
                                    <li>
                                        Salientar para candidatos que estão no 3º ano do ensino médio e para aqueles que 
                                        trabalham ou pretendem trabalhar
                                    </li>
                                </ul>
                            </li>
                            <li>  Vai conseguir dar conta? Por que?</li>
                        </ol>

                        <ol>
                            <li>Comentários e visões do entrevistador (Sobre os objetivos do candidato).</li>
                            <li> Sobre as nossas atividades:
                                <ul>
                                    <li>Você frequentará as aulas de sábado?</li>
                                    <li>Você frequentará as monitorias?</li>
                                    <li>Você frequentará os simulados?</li>
                                    <li>Você acredita que será capaz de manter o pagamento durante o ano da mensalidade? Você assume o compromisso de manter um diálogo com o diretor financeiro, caso não possa pagar?</li>
                                    <li>Você acredita merecer a dedicação de todos os voluntários? Por quê?</li>
                                    <li>Por que devemos escolher você dentre tantos outros candidatos?</li>
                                    <li>Se ex-aluno, por que dar esta oportunidade a você de novo?</li>
                                </ul>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>

            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">AVALIAÇÃO</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewTotalIncome')); ?>
                    </div>

                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewNumberOfFamilyMembers')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewMaxScholarity')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewHomeType')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewHomeSituation')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewMaxPosition')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewerCommentEvalSocioec')); ?>
                    </div>

                    <div class="col-md-4 col-xs-12">
                        <label>Atentar para os seguintes itens</label>
                        <?php echo $this->formRow($interview->get('interviewFamEthnicity')); ?>
                        <?php echo $this->formRow($interview->get('interviewFamilyProvider')); ?>
                        <?php echo $this->formRow($interview->get('interviewHasChildren')); ?>
                        <?php echo $this->formRow($interview->get('interviewHasDisease')); ?>
                        <?php echo $this->formRow($interview->get('interviewHighSchool')); ?>
                        <?php echo $this->formRow($interview->get('interviewFamDependency')); ?>
                        <?php echo $this->formRow($interview->get('intervewNeedToWork')); ?>
                        <?php echo $this->formRow($interview->get('interviewSingleton')); ?>
                        <?php echo $this->formRow($interview->get('intervewFamilyPropAndGoods')); ?>
                    </div>
                    <div class="col-md-8 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewStudentVulnerability')); ?>
                        <?php echo $this->formRow($interview->get('interviewVulnerabilityGrade')); ?>
                    </div>

                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewStudentQuestion')); ?>
                        <?php echo $this->formRow($interview->get('interviewStudentGrade')); ?>
                    </div>
                    <div class="col-md-12 col-xs-12">
                        <?php echo $this->formRow($interview->get('interviewerGeneralComment')); ?>
                    </div>
                </div>
            </div>

            <div class="col-md-12 col-xs-12">
                <?php echo $this->formRow($form->get('interviewSubmit')); ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>





</section>
