<section class="content">

    <p><?php echo $this->message; ?></p>

    <?php if ($this->registration !== null): ?>

        <?php
        echo $this->partial('profile/template',
            array(
            'registration' => $registration,
            'config' => array(
                'isPhotoEditable' => true,
                'showAge' => true,
                'tabs' => array(
                    'recruitment-timeline' => true,
                    'info' => $form,
                ),
            ),
        ));
        ?>

    <?php endif; ?>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/interview/profile';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>