<section class="content">
    <p><?php echo $this->message; ?></p>
    <?php if ($recruitment !== null): ?>
        <div class="row">
            <form class="form-inline col-xs-12 col-md-10 col-md-offset-1">
                <div class="form-group">
                    <label for="recruitment_id">Processo seletivo: </label>
                    <select class="form-control" id="recruitment_id">

                        <option value="<?php echo $recruitment->getRecruitmentId(); ?>">
                            <?php
                            echo $recruitment->getRecruitmentNumber() . 'º Processo seletivo de ' .
                            $recruitment->getRecruitmentYear();
                            ?>
                        </option>
                    </select>
                </div>

                <div class="form-group">
                    <button type="button" class="btn btn-default" id="recruitment-button"><i class="fa fa-search"></i></button>
                </div>
            </form>
        </div>
        <br>
        <div class="row">
            <div class="table-responsive col-xs-12 col-md-8 col-md-offset-2">
                <table class="table table-condensed table-bordered" id="recruitment-table">
                    <thead>
                    <th>Nº de Inscrição</th>
                    <th>Data</th>
                    <th>Nome</th>
                    <th>Cpf</th>
                    <th>Rg</th>
                    <th>Email</th>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>

    <?php endif; ?>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/enrollment/index';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>
