<section class="content-header">
    <h1>Perfil do Aluno</h1>
    <p><?php echo $this->message; ?></p>
</section>

<section class="content">
    <?php if ($this->registration !== null): ?>

        <?php
        $TimelineItens = [];

        $today = new \DateTime('now');

        foreach ($enrollments as $enr) {
            $TimelineItens[] = array(
                'color' => 'bg-green-active',
                'title' => $enr->getEnrollmentBeginDate()->format('H:i \o\n l jS F Y'),
                'time' => 'Há ' . $today->diff($enr->getEnrollmentBeginDate())->d . ' dias',
                'icon' => 'fa fa-graduation-cap',
                'content-header' => 'Matrícula',
            );
        }



        echo $this->partial('profile/template', array(
            'registration' => $registration,
            'config' => array(
                'isPhotoEditable' => false,
                'showAge' => true,
                'tabs' => array(
                    'recruitment-timeline' => $TimelineItens,
                    'info' => true,
                ),
            ),
        ));
        ?>

    <?php endif; ?>
</section>

<section class="content-header">
    <h1>Turmas Disponíveis</h1>
</section>

<section class="content">
    <?php if ($this->classes !== null): ?>
        <div class="row">
            <div class="table-responsive col-xs-8 col-md-8 col-md-offset-2">
                <table id="class-table" class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Turma</th>
                            <th class="text-center">Data de Início</th>
                            <th class="text-center">Data de Término</th>
                            <th class="text-center">Nº de Alunos</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->classes as $class): ?>
                            <tr class="cats-row" data-id="<?php echo $class->getClassId(); ?>">
                                <td class="text-center"> <?php echo $class->getClassId(); ?></td>
                                <td class="text-center"> <?php echo $class->getClassName(); ?></td>
                                <td class="text-center"> <?php echo $class->getClassBeginDate()->format('d/m/Y'); ?></td>
                                <td class="text-center"> <?php echo $class->getClassEndDate()->format('d/m/Y'); ?></td>
                                <td class="text-center"> <?php echo $class->getEnrollments()->count(); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDataTable = function () {

            $('#class-table').DataTable({
                dom: 'lftip',
                paging: false
            });
        };

        return {
            init: function () {
                initDataTable();
            }
        };

    }());

</script>