<?php echo $this->doctype(); ?>

<html lang="pt-br"
       xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <meta charset="utf-8">
        <meta property="og:image" content="<?php echo $this->basePath('img/logo_fb.png'); ?>">
        <?php echo $this->headTitle('CATS'); ?>


        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
                // Roboto
                ->appendStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,700')
                // Bootstrap
                ->appendStylesheet($this->basePath('vendor/bootswatch-dist/css/bootstrap.min.css'))
                ->appendStylesheet($this->basePath('css/site.css'))
                // Custom Icons
                ->appendStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
                // Social Icons
                ->appendStylesheet($this->basePath('vendor/bootstrap-social/bootstrap-social.css'));
        ?>
    </head>
    <body data-spy="scroll" data-target=".navbar" data-offset="5">
        <div class="wrapper">
            <header class="catssys-header" id="home">
                <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <a class="navbar-brand" href="/">
                                <img src="/img/logo_branco.png" title="Curso Assistencial Theodomiro Santiago" alt="Curso Assistencial Theodomiro Santiago" height="23">
                            </a>
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <p class="navbar-text hidden-sm hidden-xs"><b>Curso Assistencial Theodomiro Santiago</b></p>

                        <div class="collapse navbar-collapse" id="navbar-collapse-main">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a data-scroll href="#home">Início</a></li>
                                <li><a data-scroll href="#about">Sobre</a></li>
                                <li><a data-scroll href="#admin-structure">Estrutura Admin.</a></li>
                                <li><a data-scroll href="#tests">Vestibulinhos</a></li>
                                <li><a data-scroll href="#partners">Parceiros</a></li>
                                <li><a data-scroll href="#contact">Contato</a></li>
                                <li class="divider"></li>
                                <li><a href="/authentication/login">Login</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav>
            </header>
            <main>
                <?php echo $this->content; ?>
            </main>
            <footer>
                <div class="container">
                    <section class="col-md-4 col-sm-6  text-center">
                        <h4>Contato</h4>
                        <p> Av. BPS, 1303 – Sala I.1.2.47 – CEP 37500-903 <br> Pinheirinho – Itajubá – MG
                            <br>Fone: (35) 8871-2364. Email: catsrpp@gmail.com </p>
                    </section>
                    <section class="col-md-4 col-sm-6 text-center">
                        <img src="/img/logo_branco.png" alt="CATS logo">
                        <p>CATS, mais que uma oportunidade, uma família!</p>
                    </section>
                    <section class="col-md-4 hidden-sm hidden-xs text-center">
                        <h4>Redes Sociais</h4>
                        <a href="#"><p>Facebook</p></a>
                        <a href="#"><p>Google+</p></a>
                        <a href="#"><p>Twitter</p></a>
                    </section>
                    <section class="col-sm-12 visible-sm visible-xs text-center">
                        <ul class="list-inline">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>

                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        </ul>
                    </section>
                </div>
                <br>
                <hr>
                <div class="container">
                    <section class="text-center">
                        <p>© 2003-2016 CATS. TODOS OS DIREITOS RESERVADOS.</p>
                    </section>

                </div>
            </footer>
        </div>

        <script data-main="/js/site-config" src="/vendor/requirejs/require.js"></script>

        <script>
            require(['site-config']);
        </script>
    </body>
</html>
