<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CatsSys'); ?>


        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'))
                // Bootstrap core
                ->appendStylesheet($this->basePath('vendor/startbootstrap-sb-admin-1.0.3/css/bootstrap.min.css'))
                // Custom Fonts
                ->appendStylesheet($this->basePath('vendor/startbootstrap-sb-admin-1.0.3/font-awesome/css/font-awesome.min.css'));
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-top">
            <div class='container'>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">CatsSys</a>
                </div>

                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href='<?php echo $this->url('authentication/login'); ?>'>Login</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <footer class='footer navbar-fixed-bottom'>
            <div class='container'>
                <p>
                    &copy <?php echo date('Y') ?> CATS.
                    <br>Todos os direitos reservados.
                    <br> Site construído pelo grupo de informática do CATS.
                </p>
            </div>
        </footer>
        <?php
        echo $this->inlineScript()
                // Bootstrap js
                ->prependFile($this->basePath('vendor/startbootstrap-sb-admin-1.0.3/js/bootstrap.min.js'))
                // JQuery
                ->prependFile($this->basePath('vendor/startbootstrap-sb-admin-1.0.3/js/jquery.js'));
        ?>
    </body>
</html>
