<section class="content">
    <p><?php echo $this->message; ?></p>
    
    <?php if ($info !== null) : ?>
        <div class="table-responsive col-xs-12 col-md-10 col-md-offset-1">
            <table id="info-table" class="table table-hover table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th class="text-center col-xs-3 col-md-3"><?php echo $info['names'][0] ?></th>
                        <th class="text-center"> Respostas </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($info['names'] as $i => $name) { ?>
                        <?php if ($i === 0) continue; ?>
                        <tr data-id="<?php echo $i ?>">
                            <td class="text-center col-xs-3 col-md-3"><h4><?php echo $name ?></h4></td>
                            <td class="text-center">
                                <div>
                                    <div class="box box-default collapsed-box">
                                        <div class="box-header with-border">
                                            <h3 class="box-title">
                                                Mascote favorito dentre os abaixo 
                                                (Radio Button)
                                            </h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div><!-- /.box-tools -->
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                            <?php echo $info['mascots'][$i] ?>
                                        </div><!-- /.box-body -->
                                    </div><!-- /.box -->      
                                    
                                    <div class="box box-default collapsed-box">
                                        <div class="box-header with-border">
                                            <h3 class="box-title">
                                                Jogos Zerados (Checkbox)
                                            </h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div><!-- /.box-tools -->
                                        </div><!-- /.box-header -->
                                        <div class="box-body">
                                            <?php foreach ($info['games'][$i] as $game) { ?>
                                                <?php echo $game ?> <br>
                                            <?php } ?>
                                        </div><!-- /.box-body -->
                                    </div><!-- /.box -->    
                                    
                                    <div class="box box-default collapsed-box">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"> Pergunta Obrigatória (Parágrafo) </h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div><!-- /.box-tools -->
                                        </div><!-- /.box-header -->
                                        <div class="box-body list-group">
                                            <?php echo $info['compulsory'][$i] ?>
                                        </div><!-- /.box-body -->
                                    </div><!-- /.box -->       
                                    
                                    <div class="box box-default collapsed-box">
                                        <div class="box-header with-border">
                                            <h3 class="box-title"> Pergunta Opcional (Parágrafo) </h3>
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div><!-- /.box-tools -->
                                        </div><!-- /.box-header -->
                                        <div class="box-body list-group">
                                            <?php echo $info['optional'][$i] ?>
                                        </div><!-- /.box-body -->
                                    </div><!-- /.box -->                           
                                    
                                    <p><b> Data de submissão: </b><?php echo $info['dates'][$i] ?></p>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        <div class="table-responsive col-xs-8 col-md-8 col-md-offset-2">
    <?php else : ?>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2"> 
                <?php echo $this->form($form); ?>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/csv-viewer/index';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>