<section class="content">
    <?php
    $this->headTitle()->append('Fechamento de Mês')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <?php if ($form !== null): ?>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                <div class="col-xs-6">
                    <div class="box box-default no-border collapsed-box">
                        <div class="box-header with-border no-padding no-border">
                            <div class="box-title col-xs-12 no-padding">
                                <div class="info-box bg-green no-margin">
                                    <span class="info-box-icon"><i class="fa fa-chevron-circle-up"></i></span>
                                    <div class="info-box-content">
                                        <span class="info-box-text" style="line-height: 28px">Receita</span>
                                        <span class="info-box-number"><?php echo $this->openMonth->getMonthlyBalanceRevenue(); ?></span>
                                        <div class="progress">
                                            <div class="progress-bar" style="width: 100%"></div>
                                        </div>
                                        <span class="progress-description">
                                            Previsão: <?php echo $this->openMonth->getMonthlyBalanceProjectedRevenue(); ?>
                                        </span>
                                    </div><!-- /.info-box-content -->
                                </div><!-- /.info-box -->
                            </div>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div><!-- /.box-tools -->
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <table class="table table-condensed">
                                <tr>
                                    <th>Valor</th>
                                    <th>Descrição</th>
                                    <th>Observação</th>
                                </tr>
                                <?php foreach ($this->openMonth->getCashFlows() as $revenue): ?>
                                <?php if ($revenue->getcashFlowType()->getCashFlowTypeDirection() === 
                                        FinancialManagement\Entity\CashFlowType::CASH_FLOW_DIRECTION_OUTFLOW): 
                                    continue;
                                endif;?>
                                    <tr>
                                        <td><?php echo $revenue->getCashFlowAmount(); ?></td>
                                        <td><?php echo $revenue->getCashFlowDescription(); ?></td>
                                        <td><?php echo $revenue->getCashFlowObservation(); ?></td> 
                                    </tr>
                                <?php endforeach; ?>
                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
                <div class="col-xs-6">
                    <div class="box box-default no-border collapsed-box">
                        <div class="box-header with-border no-padding no-border">
                            <div class="box-title col-xs-12 no-padding">
                                <div class="info-box bg-red no-margin">
                                    <span class="info-box-icon"><i class="fa fa-chevron-circle-down"></i></span>
                                    <div class="info-box-content">
                                        <span class="info-box-text" style="line-height: 28px">Despesa</span>
                                        <span class="info-box-number"><?php echo $this->openMonth->getMonthlyBalanceExpense(); ?></span>
                                        <div class="progress">
                                            <div class="progress-bar" style="width: 100%"></div>
                                        </div>
                                        <span class="progress-description">
                                            Previsão: <?php echo $this->openMonth->getMonthlyBalanceProjectedExpense(); ?>
                                        </span>
                                    </div><!-- /.info-box-content -->
                                </div><!-- /.info-box -->
                            </div>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
                            </div><!-- /.box-tools -->
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <table class="table table-condensed">
                                <tr>
                                    <th>Valor</th>
                                    <th>Descrição</th>
                                    <th>Observação</th>
                                </tr>
                                <?php foreach ($this->openMonth->getCashFlows() as $expense): ?>
                                <?php if ($expense->getcashFlowType()->getCashFlowTypeDirection() === 
                                        FinancialManagement\Entity\CashFlowType::CASH_FLOW_DIRECTION_INFLOW): 
                                    continue;
                                endif;?>
                                    <tr>
                                        <td><?php echo $expense->getCashFlowAmount(); ?></td>
                                        <td><?php echo $expense->getCashFlowDescription(); ?></td>
                                        <td><?php echo $expense->getCashFlowObservation(); ?></td> 
                                    </tr>
                                <?php endforeach; ?>
                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
                <?php echo $this->form($form); ?>
            </div>
        </div>
    <?php endif; ?>
</section>
