<section class="content">

    <p><?php if ($message !== null) echo $message; ?></p>
    <div class="container-fluid">
        <div class="col-md-8 col-md-offset-2 text-center">
            <h4 class="row">RECEITAS E DESPESAS</h4>
            <select class="form-control" id="graph-time-range">
                <option value="1">Ano Atual</option>
                <option value="5">Últimos 5 Anos</option>
                <option value="0">Todos os anos</option>
            </select>
            <div class="col-md-12 text-right">
                <div id="total-expense" class="text-right text-red"></div>
                <div id="total-revenue" class="text-right text-blue"></div>
                <div id="balance" class="text-right text-blue"></div>
            </div>
            <canvas id="months-graph"></canvas>  
            <canvas id="years-graph"></canvas>  
            <canvas id="all-time-graph"></canvas>     
            <br>
            <br>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-4 col-xs-12 well">
                <h4 class="text-center">Caixa</h4>
                <hr>
                <div><h4 id="cash-in-hand"></h4></div>
            </div>
            <div class="col-md-4 col-xs-12 well">
                <h4 class="text-center">Receitas Mensais</h4>
                <hr>
                <div id="monthly-revenue">
                    <ul class="list-group">
                    </ul>
                </div>
            </div>   
            <br>
            <div class="col-md-4 col-xs-12 well">
                <h4 class="text-center">Despesas Mensais</h4>
                <hr>
                <div id="monthly-expense">
                    <ul class="list-group">
                    </ul>
                </div>
            </div>   
        </div>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/financial-management/cash-flow/index';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>
