
<section class="catssys-about-us">
    <h2 class="text-center">SOBRE NÓS</h2>
    <hr>
    <div class="container">
        <p class="text-justify">
            O CATS é um cursinho pré-vestibular para alunos que não possuem renda compatível com instituições particulares e têm vontade de ingressar em universidades e faculdades do país. Cada aluno contribui mensalmente com uma taxa simbólica de 30 (trinta) reais, revertido em visitas técnicas para os alunos, compra de material para professores, custear a passagem e alimentação de alunos em simulados caso, comprovadamente, não possuam condições financeiras para tal.<p>

        <p class="text-justify">Todas as atividades do cursinho são realizadas por voluntários, ao todo mais de 70 voluntários que atuam em atividades de ensino, divulgação, gestão de RH, informática e finanças. A maior parte dos voluntários do CATS é composta por alunos da UNIFEI, porém, o cursinho conta com professores já formados e por estudantes de outras instituições de ensino superior.</p>
        <br>
        <p class="pull-right">
            <small><em>Escrito por Yasmine Madella e revisado por Augusto de Almeida Mendes</em></small>
        </p>
    </div>
</section>


<section>
    <h2 class="text-center">ESTRUTURA ADMINISTRATIVA</h2>
    <hr>

    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 catssys-admin-structure">
                <i class="fa fa-briefcase"></i>
                <h4><strong>EXECUTIVA</strong></h4>
                <p class="text-justify">Representante oficial do CATS perante orgãos exteriores e responsável pela 
                    coordenação geral das atividades desenvolvidas pelo CATS.</p>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 catssys-admin-structure">
                <i class="fa fa-graduation-cap"></i>
                <h4><strong>ENSINO</strong></h4>
                <p class="text-justify">
                    Responsável pela elaboração de provas, gestão de professores, aulas e monitorias.
                </p>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 catssys-admin-structure">
                <i class="fa fa-users"></i>
                <h4><strong>RECURSOS HUMANOS</strong></h4>
                <p class="text-justify">Responsável por processos seletivos (processo seletivo de alunos e voluntários),
                    controle da frequência de alunos e responsável por termos e declarações que envolvem o serviço voluntário.</p>
            </div>

            <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 catssys-admin-structure">
                <i class="fa fa fa-usd"></i>
                <h4><strong>FINANCEIRA</strong></h4>
                <p class="text-justify">É responsável pelo controle do patrimônio do CATS, arrecadação das mensalidades, 
                    compra de equipamentos e materiais e,
                    pela gestão da biblioteca.</p>
            </div>

        </div>
    </div>

</section>


<section class="catssys-partners">
    <h2 class="text-center">NOSSOS PARCEIROS</h2>
    <hr>

    <div id="catssys-partners-carousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#catssys-partners-carousel" data-slide-to="0" class="active"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4 col-sm-6 text-center">
                            <img src="/img/unifei.png" alt="Unifei" width="200">
                        </div>
                        <div class="col-lg-4 col-sm-6 text-center">
                            <img src="/img/speaking.png" alt="Speaking" width="200">
                        </div>
                        <div class="col-lg-4 col-sm-12 text-center">
                            <img src="/img/casdvest.png" alt="CASD" width="200">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a class="left carousel-control" href="#catssys-partners-carousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
        <a class="right carousel-control" href="#catssys-partners-carousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
        </a>
    </div>
</section>
