<section class="content">
    <div class="row">
        <div class="container-fluid">
            <div class="col-md-8 col-md-offset-2 col-xs-12">
                <div id="allowanceMonth"></div>
            </div>
        </div>

        <div class="container-fluid">
            <div id="allowanceStudents">
            </div>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/attendance/analyze-edit-allowance';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>