<section class="content">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 col-xs-12">
            <div id="allowanceMonth"></div>
        </div>
    </div>
</section>


<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/attendance/attendance';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>