<section class="content">
    <div class="row">
        <div class="box box-default color-palette-box">
            <div class="box-header with-border">
            </div>
            <div class="box-body">
                <div class="col-xs-12 col-md-8 col-md-offset-2">
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-info"></i> Observação</h4>
                        Clique na engrenagem do canto superior direito para visualizar o botão de salvar listas.
                    </div>
                    <div class="col-xs-12 col-md-12">

                        <div class="box-group" id="accordion">
                            <!-- we are adding the .panel class so bootstrap.js collapse plugin detects it -->
                            <div class="panel box box-primary">
                                <div class="box-header with-border">
                                    <h4 class="box-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                            Configurações
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse in">
                                    <div class="box-body">
                                        <dl class="dl-horizontal">
                                            <dt id="schoolClass" class="text-left">Identificador da turma</dt>
                                            <dd><em></em></dd>
                                            <dt id="attendanceTypes" class="text-left">Tipo(s) de lista</dt>
                                            <dd><em></em></dd>
                                            <dt id="attendanceDates" class="text-left">Data(s) de aplicação</dt>
                                            <dd><em></em></dd>
                                        </dl>
                                    </div>

                                    <div class="form-group">
                                        <label for="attendanceListInput">Lista (.csv)</label>
                                        <div class="input-group btn-file">
                                            <span class="input-group-addon"><i class="fa fa-file-excel-o"></i></span>
                                            <input name="attendanceListInput" id="attendanceListInput" type="file">
                                            <span class="form-control btn-file-name">Nenhum arquivo selecionado</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-group" id="attendanceLists">
            </div>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/attendance/attendance-add-allowance';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>
