<section class="content">
    <div class="row">
        <div class="col-md-12 col-xs-12">
            <div class="box-header with-border">
            </div>
            <div class="box box-success">
                <div class="box-header with-border">
                    <h3 class="box-title"><span class="fa fa-book"></span> Instruções</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body" style="display: block;">
                    <div class="col-md-10 col-md-offset-1">
			Clique na engrenagem do canto superior direito para visualizar o botão de salvar listas.
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <div class="col-md-12 col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title"><span class="fa fa-gears"></span> Configuração</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body" style="display: block;">
                    <div class="col-md-10 col-md-offset-1">
                                                    <div id="collapseOne" class="panel-collapse collapse in">
                                    <div class="box-body">
                                        <dl class="dl-horizontal">
                                            <dt id="schoolClass" class="text-left">Identificador da turma</dt>
                                            <dd><em></em></dd>
                                            <dt id="attendanceTypes" class="text-left">Tipo(s) de lista</dt>
                                            <dd><em></em></dd>
                                            <dt id="attendanceDates" class="text-left">Data(s) de aplicação</dt>
                                            <dd><em></em></dd>
                                        </dl>
                                    </div>

                                    <div class="form-group">
                                        <label for="attendanceListInput">Lista (.csv)</label>
                                        <div class="input-group btn-file">
                                            <span class="input-group-addon"><i class="fa fa-file-excel-o"></i></span>
                                            <input name="attendanceListInput" id="attendanceListInput" type="file">
                                            <span class="form-control btn-file-name">Nenhum arquivo selecionado</span>
                                        </div>
                                    </div>
                                </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
            <div class="box-group" id="attendanceLists">
            </div>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/school-management/attendance/attendance-add-allowance';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>
