<section class="content">
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <?php if ($resources): ?>

                <div class="table-responsive">
                    <table class="table table-condensed table-striped" id="resource-table" style="display:none;">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Resource Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($resources as $resource): ?>
                                <tr class="cats-row" data-id="<?php echo $resource->getResourceId(); ?>">
                                    <td><?php echo $resource->getResourceId(); ?></td>
                                    <td class="text-center"><?php echo $resource->getResourceName(); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/authorization/resource/Resource';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>