<section class="content">
    <p><?php echo $message; ?></p>

    <div class="row">
        <div class="ccol-xs-12 col-md-6 col-md-offset-3">
           <?php echo $this->form($form); ?>
        </div>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/pre-interview/index';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>