<section class="content">
    <p><?php echo $message; ?></p>

    <div class="row">
        <div class="ccol-xs-12 col-md-6 col-md-offset-3">
            <?php $form->prepare(); ?>

            <?php echo $this->form()->openTag($form); ?>

            <div class="form-group">
                <label for="cpf">Cpf</label>
                <?php
                echo $this->formRow($form->get('cpf'));
                ?>
            </div>

            <div class="form-group">
                <?php
                echo $this->formSubmit($form->get('submit'));
                ?>
            </div>

            <?php echo $this->form()->closeTag(); ?>

        </div>
    </div>

</section>
