
<?php
$person = $registration->getPerson();
$form->prepare();
?>
<section class="content">
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Dados de Inscrição</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>

                <div class="box-body">
                    <div class="form-group">
                        <label class="control-label">Número de inscrição: </label>
                        <?php echo $registration->getRegistrationNumber(); ?>
                        <br>
                        <label class="control-label">Nome:</label> 
                        <?php echo $person->getPersonName(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
            <?php echo $this->form()->openTag($form); ?>

            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Endereço</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-2">
                            <?php echo $this->formRow($form->get('cep')); ?>
                        </div>
                        <div class="col-xs-12 col-md-1 col-md-offset-1">
                            <?php echo $this->formRow($form->get('uf')); ?>
                        </div>
                        <div class="col-xs-12 col-md-3 col-md-offset-1">
                            <?php echo $this->formRow($form->get('city')); ?>
                        </div>
                        <div class="col-xs-12 col-md-3 col-md-offset-1">
                            <?php echo $this->formRow($form->get('neighborhood')); ?>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-6">
                            <?php echo $this->formRow($form->get('street')); ?>
                        </div>
                        <div class="col-xs-12 col-md-2 col-md-offset-1">
                            <?php echo $this->formRow($form->get('number')); ?>
                        </div>
                        <div class="col-xs-12 col-md-2 col-md-offset-1">
                            <?php echo $this->formRow($form->get('complement')); ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Educação</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('elementary_school_type')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('high_school_type')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-9">
                            <?php echo $this->formRow($form->get('high_school')); ?>
                        </div>
                        <div class="col-xs-12 col-md-2 col-md-offset-1">
                            <?php echo $this->formRow($form->get('hs_conclusion_year')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('preparation_school')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('language_course')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('current_study')); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Sócioeconômico</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('live_with_number')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('live_with_you')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('number_of_rooms')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('means_of_transport')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('monthly_income')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('father_education_grade')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('mother_education_grade')); ?>
                        </div>
                    </div>
                    <br>
                    <div class="form-group col-md-12">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('expect_from_us')); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
            </div>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

</section>
