<section class="content">

    <div class="row">

        <div class="col-xs-12 col-md-6 col-md-offset-3">


            <div class="box">
                <div class="box-header with-border">
                    <div class="box-title">
                        <h3>Comprovantes </h3>
                        <span>Clique no ícone de pdf (<i class="fa fa-file-pdf-o"></i>) para enviar os arquivos.</span>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <p><?php echo $message; ?></p>

                    <div class="col-md-12 col-xs-12">
                        <div class="info-box <?php echo $files['personal'] ? 'bg-green' : 'bg-red' ?> ">
                            <span class="info-box-icon" 
                                  id="personal" data-id="personal">
                                <i class="fa fa-file-pdf-o"></i>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">Informações pessoais</span>
                                <span class="info-box-number">
                                    <small>
                                        <?php if ($files['personal']): ?>
                                            <a href="/recruitment/pre-interview/getUploadedFile/personal" 
                                               target="_blank">
                                                Informações pessoais.pdf
                                            </a>
                                        <?php endif; ?>
                                    </small>
                                </span>
                                <div class="progress">
                                    <div class="progress-bar" style="opacity: 0; width: 0%"></div>
                                </div>
                                <span class="progress-description">
                                </span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>

                    <!-- /.col -->
                    <div class="col-md-12 col-xs-12">
                        <div class="info-box <?php echo $files['income'] ? 'bg-green' : 'bg-red' ?>">
                            <span class="info-box-icon"
                                  id="income" data-id="income">
                                <i class="fa fa-file-pdf-o"></i>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">Comprovantes de renda</span>
                                <span class="info-box-number">
                                    <small>
                                        <?php if ($files['income']): ?>
                                            <a href="/recruitment/pre-interview/getUploadedFile/income" 
                                               target="_blank">
                                                Comprovantes de renda.pdf
                                            </a>
                                        <?php endif; ?>
                                    </small>
                                </span>
                                <div class="progress">
                                    <div class="progress-bar" style="opacity: 0; width: 0%"></div>
                                </div>
                                <span class="progress-description">
                                </span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                    <!-- fix for small devices only -->
                    <div class="clearfix visible-sm-block"></div>

                    <div class="col-md-12 col-xs-12">

                        <div class="info-box <?php echo $files['expendure'] ? 'bg-green' : 'bg-red' ?>">
                            <span class="info-box-icon"
                                  id="expendure" data-id="expendure">
                                <i class="fa fa-file-pdf-o"></i>
                            </span>

                            <div class="info-box-content">
                                <span class="info-box-text">Comprovantes de despesas</span>
                                <span class="info-box-number">
                                    <small>
                                        <?php if ($files['expendure']): ?>
                                            <a href="/recruitment/pre-interview/getUploadedFile/expendure" 
                                               target="_blank">
                                                Comprovantes de despesa.pdf
                                            </a>
                                        <?php endif; ?>
                                    </small>
                                </span>
                                <div class="progress">
                                    <div class="progress-bar" style="opacity: 0; width: 0%"></div>
                                </div>
                                <span class="progress-description">
                                </span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>
                    <!-- /.col -->
                </div>
            </div>

            <form method="POST">
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-block"> Prosseguir </button>
                </div>
            </form>
        </div>
    </div>
</section>


<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/pre-interview/student-files';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>