

<section class="content">
    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Dados de Inscrição</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>

                <div class="box-body">
                    <?php if ($registration != null): ?>
                        <?php $person = $registration->getPerson(); ?>
                        <div class="form-group">
                            <label class="control-label">Número de inscrição: </label>
                            <?php echo $registration->getRegistrationNumber(); ?>
                            <br>
                            <label class="control-label">Nome:</label> 
                            <?php echo $person->getPersonName(); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php if ($form !== null): ?>
                <?php echo $this->form()->openTag($form); ?>

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Endereço</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="form-group">
                            <div class="col-xs-12 col-md-12">
                                <div class="col-xs-12 col-md-2">
                                    <?php echo $this->formRow($form->get('postal_code')); ?>
                                </div>
                                <div class="col-xs-12 col-md-2">
                                    <?php echo $this->formRow($form->get('state')); ?>
                                </div>
                                <div class="col-xs-12 col-md-4">
                                    <?php echo $this->formRow($form->get('city')); ?>
                                </div>
                                <div class="col-xs-12 col-md-4">
                                    <?php echo $this->formRow($form->get('neighborhood')); ?>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12 col-md-12">
                                <div class="col-xs-12 col-md-6">
                                    <?php echo $this->formRow($form->get('street')); ?>
                                </div>
                                <div class="col-xs-12 col-md-3">
                                    <?php echo $this->formRow($form->get('number')); ?>
                                </div>
                                <div class="col-xs-12 col-md-3">
                                    <?php echo $this->formRow($form->get('complement')); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if ($form->has('relative_relationship')): ?>

                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Responsável</h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                <div class="col-xs-12 col-md-12">
                                    <div class="col-xs-12 col-md-4">
                                        <?php echo $this->formRow($form->get('person_firstname_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-8">
                                        <?php echo $this->formRow($form->get('person_lastname_relative')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('person_gender_relative')); ?>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12 col-md-12">
                                    <div class="col-xs-12 col-md-2">
                                        <?php echo $this->formRow($form->get('person_birthday_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-5">
                                        <?php echo $this->formRow($form->get('person_cpf_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-5">
                                        <?php echo $this->formRow($form->get('person_rg_relative')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12 col-md-12">
                                    <div class="col-xs-12 col-md-3">
                                        <?php echo $this->formRow($form->get('person_phone_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-4">
                                        <?php echo $this->formRow($form->get('person_email_relative')); ?>
                                    </div>                    
                                    <div class="col-xs-12 col-md-5">
                                        <?php echo $this->formRow($form->get('person_confirm_email_relative')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('relative_relationship')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Endereço do Responsável</h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="form-group">
                                <div class="col-xs-12 col-md-12">
                                    <div class="col-xs-12 col-md-2">
                                        <?php echo $this->formRow($form->get('postal_code_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-2">
                                        <?php echo $this->formRow($form->get('state_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-4">
                                        <?php echo $this->formRow($form->get('city_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-4">
                                        <?php echo $this->formRow($form->get('neighborhood_relative')); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12 col-md-12">
                                    <div class="col-xs-12 col-md-6">
                                        <?php echo $this->formRow($form->get('street_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-3">
                                        <?php echo $this->formRow($form->get('number_relative')); ?>
                                    </div>
                                    <div class="col-xs-12 col-md-3">
                                        <?php echo $this->formRow($form->get('complement_relative')); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                <?php endif; ?>

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Educação</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('elementary_school_type')); ?>
                        </div>
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('high_school_type')); ?>
                        </div>
                        <div class="col-xs-12 col-md-9">
                            <?php echo $this->formRow($form->get('high_school')); ?>
                        </div>
                        <div class="col-xs-12 col-md-3">
                            <?php echo $this->formRow($form->get('hs_conclusion_year')); ?>
                        </div>
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('preparation_school')); ?>
                        </div>
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('language_course')); ?>
                        </div>
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('current_study')); ?>
                        </div>
                    </div>
                </div>
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Sócioeconômico</h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('live_with_number')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('live_with_you')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('number_of_rooms')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('means_of_transport')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('monthly_income')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('father_education_grade')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('mother_education_grade')); ?>
                            </div>
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('expect_from_us')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formRow($form->get('submit')); ?>
                        </div>
                    </div>

                    <?php echo $this->form()->closeTag(); ?>
                <?php endif; ?>
                <p><?php echo $message; ?> </p>
            </div>
        </div>
    </div>
</section>
