<section class="content">

    <h3 class="text-center"><?php echo $message; ?></h3>
    <?php if ($form !== null): ?>
        <div class="row">
            <div class="col-xs-12 col-md-10 col-md-offset-1">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <div class="box-title">
                            <h3><i class="fa fa-book pull-left"></i> Instruções 
                                <small>Antes de preencher o formulário leia atentamente as informações a seguir</small></h3>
                        </div>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="container-fluid text-justify">
                            <ol>
                                <li>Este formulário tem por finalidade o estudo da situação socioeconômica do
                                    candidato e seu grupo familiar.</li>
                                <li>Entende-se por grupo familiar a unidade nuclear composta por uma ou mais pessoas, 
                                    eventualmente ampliada por outras pessoas que contribuam para o rendimento ou tenham suas 
                                    despesas atendidas, sendo todas moradoras em um mesmo domicílio. 
                                    Entende-se por morador, a pessoa que tem o domicílio como local habitual de residência e 
                                    nele reside na data da inscrição no processo seletivo.</li>
                                <li>O simples preenchimento e entrega deste formulário não implica a garantia da vaga</li>
                                <li>Formulários incompletos não serão analisados.</li>
                                <li>Todos os dados lançados neste formulário deverão ser referentes ao último mês e somente 
                                    deverão ser registrados os <b>rendimentos brutos</b>.</li>
                                <li>Os candidatos deverão comprovar as informações prestadas por meio de
                                    documentação do solicitante e do seu grupo familiar, somente na data da
                                    entrevista. Em caso de dúvidas, consulte o edital deste processo seletivo.</li>
                                <li>Para maiores esclarecimentos quanto ao preenchimento deste formulário, envie um e-mail 
                                    para <a href="mailto:catspresidencia@gmail.com?subject=Pré-entrevista">
                                        catspresidencia@gmail.com
                                    </a> com o assunto <em>Pré-entrevista</em>.
                                </li>
                                <li>Declarações falsas ou omissão da verdade implicarão a desclassificação do candidato.</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Dados de Inscrição</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    <div class="box-body">
                        <?php if ($registration != null): ?>
                            <div class="form-group">
                                <label class="control-label">Número de inscrição: </label>
                                <?php echo $registration->getRegistrationNumber(); ?>
                                <br>
                                <label class="control-label">Data de inscrição: </label>
                                <?php echo $registration->getRegistrationDate(); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <?php
                $form->prepare();
                echo $this->form()->openTag($form);

                $regForm = $form->get('registration');
                $personForm = $regForm->get('person');
                $preInForm = $regForm->get('preInterview');

                echo $this->partial('person/template', array(
                    'form' => $personForm,
                ));

                echo $this->partial('disclosure/template', array(
                    'form' => $regForm,
                ));

                echo $this->partial('pre-interview/template', array(
                    'form' => $preInForm,
                ));

                ?>

                <div class="form-group">
                    <div class="col-xs-12 col-md-12 text-justify">
                        <?php echo $this->formRow($form->get('preInterviewConsent')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12 col-md-12">
                        <?php echo $this->formRow($form->get('submit')); ?>
                    </div>
                </div>

                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/pre-interview/pre-interview';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>