<section class="content">
    <div class="row">
        <div id="hierarchy" style="overflow-x: auto;">
        </div>
    </div>
</section>

<style>
    .hierarchy-color {
        background-color: #3c8dbc;
        color: white;
        cursor: pointer;
    }
    .hierarchy-color-selected {
        background-color: #008080;
    }


</style>
<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/administrative-structure/job/job';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>