<section class="content">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="table-responsive">
                <table id="jobTable" class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Criado em</th>
                            <th class="text-center">Última Revisão</th>
                            <th class="text-center">Departamento</th>
                            <th class="text-center">Cargo</th>
                            <th class="text-center">Cargo Superior</th>
                            <th class="text-center">Cargos Subordinados</th>
                            <th class="text-center">Descrição </th>
                            <th class="text-center">Situação </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($jobs as $job): ?>
                            <tr class="cats-row" data-id="<?php echo $job->getJobId(); ?>">
                                <td class="text-center">
                                    <?php echo $job->getJobId(); ?>
                                </td>
                                <td class="text-center">
                                    <?php echo $job->getCreationDate(); ?>
                                </td>
                                <td class="text-center">
                                    <?php echo $job->getLastRevisionDate(); ?>
                                </td>
                                <td class="text-center">
                                    <?php echo $job->getDepartment()->getDepartmentName(); ?>
                                </td>

                                <td class="text-center">
                                    <?php echo $job->getJobName(); ?>
                                </td>
                                <td class="text-center">
                                    <?php $parentJob = $job->getParent(); ?>
                                    <?php echo $parentJob !== null ? $parentJob->getJobName() : 'NENHUM'; ?>
                                </td>
                                <td>
                                    <ol type="i">
                                        <?php
                                        foreach ($job->getChildren()->toArray() as $j):
                                            ?>
                                            <li> <?php echo $j->getJobName(); ?></li>
                                        <?php endforeach; ?>
                                    </ol>
                                </td>
                                <td class="text-center">
                                    <?php echo $job->getJobDescription(); ?>
                                </td>
                                <td class="text-center">
    <?php echo $job->getIsAvailable() ? 'ATIVO' : 'INATIVO'; ?>
                                </td>
                            </tr>
<?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/administrative-structure/job/job';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>