<section class="content">
    <p><?php echo $this->message; ?></p>

    <?php if ($form !== null): ?>

        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php
                    echo $this->formRow($form->get('registrationStatus'));
                    ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
                <br>
                <div>
                    <h4 class="text-center">Cargos</h4>
                    <dl id="jobList" class="dl-horizontal"></dl>
                </div>
            </div>            
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <div class="table-responsive">
                    <h4 class="text-center">Voluntários</h4>
                    <table class="table table-condensed table-bordered" id="office-table">
                        <thead>
                        <th>Inscrição</th>
                        <th>Nome</th>
                        <th>Email</th>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    <?php endif; ?>
</section>


<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/administrative-structure/job/job';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>
