<section class="content">

    <?php
    echo $this->message;
    ?>

    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <?php
        $role = $this->roleForm;

        $role->prepare();
        echo $this->form()->openTag($role);
        ?>
        <div class='form-group'>
            <label for='username'>Nome</label>
            <?php
            echo $this->formRow($role->get('role_name'));
            ?>
        </div>
        <div class='form-group'>
            <label for='username'>Herda de </label>
            <?php
            echo $this->formRow($role->get('role_parent'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formRow($role->get('Submit'));
            ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>