<?php


echo $this->message;


$this->roleForm;
?>

<div class='container'>

    <div class="row">
        <h2> Create a new Role </h2>
        <hr>
    </div>
    <div class="col-xs-6 col-md-4">
        <?php
        $role = $this->roleForm;

        $role->prepare();
        echo $this->form()->openTag($role);
        ?>
        <div class='form-group'>
            <label for='username'>Nome</label>
            <?php
            echo $this->formRow($role->get('role_name'));
            ?>
        </div>
        <div class='form-group'>
            <label for='username'>Herda de </label>
            <?php
            echo $this->formRow($role->get('role_parent'));
            ?>
        </div>
        <?php
        echo $this->formSubmit($role->get('Submit'));
        ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>