

<div class="container">
    <h1>Role index</h1>
    <hr>

    <?php if (!empty($this->error)): ?>
        <?php echo $this->error; ?>
    <?php else: ?>

        <div class="table-responsive">
            <table class='table'>
                <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Role Name</th>
                        <th class="text-center">Parent Roles</th>
                        <th></th>
                         <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->roles as $role): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($role->getRoleId()); ?></td>
                            <td><?php echo $this->escapeHtml($role->getRoleName()); ?></td>
                            <td class="text-center">
                                <div class="btn-toolbar" role="toolbar" aria-label="...">
                                    <?php foreach ($role->getRole()->toArray() as $parentRole): ?>
                                    <button type="button" class="btn btn-primary"><?php echo $this->escapeHtml($parentRole->getRoleName()); ?></button>
                                    <?php endforeach; ?>
                                </div>
                            </td>
                            <td><a class="btn btn-danger"  href='<?php echo $this->url('authorization/default', array('controller' => 'role', 'action' => 'edit', 'id' => $role->getRoleId())); ?>'>Edit</a></td>
                            <td><a class="btn btn-danger" href='<?php echo $this->url('authorization/default', array('controller' => 'role', 'action' => 'delete', 'id' => $role->getRoleId())); ?>'>Delete</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>



