<section class="content">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <?php if (!empty($this->error)): ?>
                <?php echo $this->error; ?>
            <?php else: ?>

                <div class="table-responsive">
                    <table id="roleTable" class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Name</th>
                                <th class="text-center">Parents</th>
                                <th class="text-center">Children</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->roles as $role): ?>
                            <tr class="cats-row" data-id="<?php echo $role->getRoleId(); ?>">
                                    <td class="text-center"><?php echo $role->getRoleId(); ?></td>
                                    <td class="text-center"><?php echo $role->getRoleName(); ?></td>
                                    <td class="text-center">
                                        <div class="btn-toolbar" role="toolbar" aria-label="...">
                                            <?php
                                            foreach ($role->getParents()->toArray() as $parentRole):
                                                ?>
                                                <button type="button" class="btn btn-success">
                                                    <?php echo $parentRole->getRoleName(); ?>
                                                </button>
                                            <?php endforeach; ?>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <div class="btn-toolbar" role="toolbar" aria-label="...">
                                            <?php
                                            foreach ($role->getChildren()->toArray() as $childRole):
                                                ?>
                                                <button type="button" class="btn btn-success">
                                                    <?php echo $childRole->getRoleName(); ?>
                                                </button>
                                            <?php endforeach; ?>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endif; ?>
        </div>
    </div>
</section>


<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/authorization/role/role';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>
