
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Divulgação</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('recruitmentKnowAbout')); ?>
        </div>
    </div>
</div>