
<?php foreach ($forms as $indx => $form): ?>
    <div class="box box-solid field-box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title"> <?php echo ($indx + 1); ?> <i class="fa fa-money"></i> </h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="form-group">
                <div class="col-md-12">
                    <div class="col-xs-12 col-md-12">
                        <?php echo $this->formRow($form->get('familyIncomeExpValue')); ?>
                    </div>
                    <div class="col-xs-12 col-md-12">
                        <?php echo $this->formRow($form->get('familyIncomeExpDescription')); ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
<?php endforeach; ?>

<span data-template='<div class="box box-solid field-box box-warning">
      <div class="box-header with-border">
      <h3 class="box-title"> __index__ <i class="fa fa-money"></i> </h3>
      <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse">
      <i class="fa fa-minus"></i>
      </button>
      </div>
      </div>
      <div class="box-body">
      <div class="form-group">
      <div class="col-md-12">
      <div class="col-xs-12 col-md-12">__TEMPLATE0__</div>
      <div class="col-xs-12 col-md-12">__TEMPLATE1__</div>
      </div>
      </div>
      </div>
      </div>'>
</span>
