<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Educação</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewElementarySchoolType')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewHighSchoolType')); ?>
        </div>
        <div class="col-xs-12 col-md-9">
            <?php echo $this->formRow($form->get('preInterviewHighSchool')); ?>
        </div>
        <div class="col-xs-12 col-md-3">
            <?php echo $this->formRow($form->get('preInterviewHSConclusionYear')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewPreparationSchool')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewLanguageCourse')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewCurrentStudy')); ?>
        </div>
    </div>
</div>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Sócioeconômico</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewLiveWithNumber')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewLiveWithYou')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewNumberOfRooms')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewMeansOfTransport')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewMonthlyIncome')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewFatherEducationGrade')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewMotherEducationGrade')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preInterviewExpectFromUs')); ?>
        </div>
    </div>
</div>
