
<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Vulnerabilidade</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('familyEthnicity')); ?>
        </div>

        <div id="family-members" class="field-container" data-min="1">
            <?php $familyMembers = $form->get('familyMembers'); ?>
            <?php echo $this->formLabel($familyMembers); ?>
            <hr>
            <?php echo $this->render('family-members/template', ['forms' => $familyMembers]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyMembers); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>

        </div>

        <div id="family-health" class="field-container" data-min="0">

            <?php $familyHealth = $form->get('familyHealth'); ?>
            <?php echo $this->formLabel($familyHealth); ?>
            <hr>
            <?php echo $this->render('family-health/template', ['forms' => $familyHealth]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyHealth); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>
        </div>

        <div id="family-goods" class="field-container" data-min="1">

            <?php $familyGoods = $form->get('familyGoods'); ?>
            <?php echo $this->formLabel($familyGoods); ?>
            <hr>
            <?php echo $this->render('family-goods/template', ['forms' => $familyGoods]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyGoods); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>
        </div>

        <div id="family-properties" class="field-container" data-min="1">
            <?php $familyProperties = $form->get('familyProperties'); ?>
            <?php echo $this->formLabel($familyProperties); ?>
            <hr>
            <?php echo $this->render('family-properties/template', ['forms' => $familyProperties]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyProperties); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>
        </div>

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('elementarySchoolType')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('highSchoolType')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <div class="col-xs-12 col-md-6">
                <?php echo $this->formRow($form->get('highSchoolAdmissionYear')); ?>
            </div>
            <div class="col-xs-12 col-md-6">
                <?php echo $this->formRow($form->get('highSchoolConclusionYear')); ?>
            </div>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('siblingsUndergraduate')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('otherLanguages')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('homeStatus')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('homeDescription')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('transport')); ?>
        </div>
    </div>
</div>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Perfil de Estudante</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('extraCourses')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('preparationCourse')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('entranceExam')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('undergraduateCourse')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('waitingForUs')); ?>
        </div>
    </div>
</div>

<div class="box box-warning">
    <div class="box-header with-border">
        <h3 class="box-title">Socioeconômico</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

        <div id="family-expenses" class="field-container" data-min="1">
            <?php $familyExpenses = $form->get('familyExpenses'); ?>
            <?php echo $this->formLabel($familyExpenses); ?>
            <hr>
            <?php echo $this->render('family-income-expense/template', ['forms' => $familyExpenses]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyExpenses); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>
        </div>

        <div id="family-income" class="field-container" data-min="1">
            <?php $familyIncome = $form->get('familyIncome'); ?>
            <?php echo $this->formLabel($familyIncome); ?>
            <hr>
            <?php echo $this->render('family-income-expense/template', ['forms' => $familyIncome]); ?>
            <?php echo $this->formCollection()->renderTemplate($familyIncome); ?>
            <div class="text-center">
                <div class="btn-group">
                    <?php echo $this->formButton($form->get('addButton')); ?>
                    <?php echo $this->formButton($form->get('delButton')); ?>
                </div>
                <hr>
            </div>
        </div>

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('live')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('responsibleFinancial')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('infrastructureElements')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('liveArea')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <label>Onde você reside existem: </label>
            <table class="table table-condensed table-striped">
                <thead>
                <th>Item</th>
                <th>Quantidade</th>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemTv')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemTv')); ?>
                            <?php echo $this->formElementErrors($form->get('itemTv')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($form->get('itemBathroom')); ?></td>
                        <td>
                            <?php echo $this->formElement($form->get('itemBathroom')); ?>
                            <?php echo $this->formElementErrors($form->get('itemBathroom')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemSalariedHousekeeper')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemSalariedHousekeeper')); ?>
                            <?php echo $this->formElementErrors($form->get('itemSalariedHousekeeper')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemDailyHousekeeper')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemDailyHousekeeper')); ?>
                            <?php echo $this->formElementErrors($form->get('itemDailyHousekeeper')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemWashingMachine')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemWashingMachine')); ?>
                            <?php echo $this->formElementErrors($form->get('itemWashingMachine')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemRefrigerator')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemRefrigerator')); ?>
                            <?php echo $this->formElementErrors($form->get('itemRefrigerator')); ?>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemCableTv')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemCableTv')); ?>
                            <?php echo $this->formElementErrors($form->get('itemCableTv')); ?>
                        </td>
                    </tr>

                    <tr>
                        <td><?php echo $this->formLabel($form->get('itemComputer')); ?></td>
                        <td>
                            <?php echo $this->formElement($form->get('itemComputer')); ?>
                            <?php echo $this->formElementErrors($form->get('itemComputer')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formLabel($form->get('itemSmartphone')); ?></td>
                        <td>
                            <?php echo $this->formElement($form->get('itemSmartphone')); ?>
                            <?php echo $this->formElementErrors($form->get('itemSmartphone')); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo $this->formLabel($form->get('itemBedroom')); ?>
                        </td>
                        <td>
                            <?php echo $this->formElement($form->get('itemBedroom')); ?>
                            <?php echo $this->formElementErrors($form->get('itemBedroom')); ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Outras Informações</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('moreInformation')); ?>
        </div>
    </div>
</div>