<?php
/**
 * Imprime o perfil do usuário de acordo com as configurações passadas
 * 
 * @todo Formação incompleta, permitir aumento da linha do tempo da aba "situação"
 * 
 */
$person = $registration->getPerson();
$recruitment = $registration->getRecruitment();
$user = $person->getUser();
$addresses = $person->getAddresses();
?>

<div class="row">
    <div class="col-md-3">

        <!-- Profile Image -->
        <div class="box box-primary">
            <div class="box-body box-profile">
                <a href="#">
                    <img class="profile-user-img img-responsive img-circle" 
                         id="profile-img"
                         src="/recruitment/registration/photo/<?php echo $person->getPersonId(); ?>"
                         data-id="<?php echo $person->getPersonId(); ?>"
                         alt="User profile picture">
                </a>

                <?php if ($config['isPhotoEditable']): ?>
                    <span class="fileupload-process">
                        <div id="total-progress" class="progress progress-xs" 
                             role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" style="opacity: 0;">
                            <div class="progress-bar progress-bar-green" style="width: 100%;" data-dz-uploadprogress=""></div>
                        </div>
                    </span>
                <?php endif; ?>

                <h3 class="profile-username text-center" id="identity"
                    data-identity="<?php echo $registration->getRegistrationId(); ?>">
                        <?php echo $person->getPersonName(); ?>
                </h3>

                <p class="text-muted text-center">
                    <?php if ($user !== null): ?>

                    <?php else: ?>

                        <?php
                        echo ($person->getPersonGender() == \Recruitment\Entity\Person::GENDER_M) ?
                            'Candidato' : 'Candidata';
                        echo ($recruitment->getRecruitmentType() ==
                        \Recruitment\Entity\Recruitment::STUDENT_RECRUITMENT_TYPE) ?
                            '<br>(Processo Seletivo de Alunos)' : '<br>(Processo Seletivo de Voluntários)';
                        ?>

                    <?php endif; ?>
                </p>

                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                        <b>Nº de Inscrição</b> <a class="pull-right"> 
                            <?php
                            echo $registration->getRegistrationNumber()
                            ?>
                        </a>
                    </li>
                    <li class="list-group-item">
                        <b>Inscrito em </b> <a class="pull-right">
                            <?php
                            echo $registration->getRegistrationDate();
                            ?>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

        <!-- About Me Box -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Sobre Mim</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <strong><i class="fa fa-birthday-cake margin-r-5"></i> Data de Nascimento</strong>

                <p class="text-muted">
                    <?php
                    echo $person->getPersonBirthday();
                    if ($config['showAge']) {
                        echo ' (' . $person->getPersonAge() . ' anos)';
                    }
                    ?>
                </p>

                <strong><i class="fa fa-phone margin-r-5"></i> Telefone</strong>

                <p class="text-muted">
                    <?php echo $person->getPersonPhone(); ?>
                </p>

                <strong><i class="fa fa-at margin-r-5"></i> Email</strong>

                <p class="text-muted">
                    <?php echo $person->getPersonEmail(); ?>
                </p>

                <strong><i class="fa fa-map-marker margin-r-5"></i> Endereço</strong>

                <p class="text-muted">
                    <?php if ($addresses !== []): ?>

                        <?php foreach ($addresses as $addr): ?>
                            <?php
                            echo $addr->getAddressStreet() . ', ' .
                            $addr->getAddressNumber() . ' ' .
                            ($addr->getAddressComplement() == null ?
                                '' :
                                ('(' . $addr->getAddressComplement() . ') ')) . '- ' .
                            $addr->getAddressNeighborhood() . ' - ' .
                            $addr->getAddressCity() . ' - ' .
                            $addr->getAddressState() . ', CEP: ' .
                            $addr->getAddressPostalCode() . '<br>';
                            ?>
                        <?php endforeach; ?>

                    <?php else: ?>
                        Nenhum endereço cadastrado.
                    <?php endif; ?>
                </p>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-md-9">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <?php if (isset($config['tabs']['recruitment-timeline'])): ?>
                    <li class="active"><a href="#recruitment-timeline" data-toggle="tab" aria-expanded="false">Situação</a></li>
                <?php endif; ?>
                <?php if (isset($config['tabs']['info'])): ?>
                    <li class=""><a href="#info" data-toggle="tab" aria-expanded="true">Editar Dados</a></li>
                <?php endif; ?>
            </ul>
            <div class="tab-content">

                <?php if (isset($config['tabs']['recruitment-timeline'])): ?>

                    <div class="tab-pane active" id="recruitment-timeline">

                        <?php $rstatus = $registration->getRegistrationStatus(); ?>

                        <table class="table">
                            <thead>
                                <tr>
                                    <th> Situação </th>
                                    <th> Data </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($rstatus as $st): ?>
                                    <tr>
                                        <td><?php echo $st->getRecruitmentStatus()->getStatusType(); ?></td>
                                        <td><?php echo $st->getTimestamp() ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>

                <?php endif; ?>
                <?php if ($config['tabs']['info']): ?>

                    <div class="tab-pane" id="info">
                        <?php $form = $config['tabs']['info']; ?>

                        <?php
                        $rType = $recruitment->getRecruitmentType();
                        $form->prepare();
                        echo $this->form()->openTag($form);

                        $regForm = $form->get('registration');
                        $personForm = $regForm->get('person');

                        echo $this->partial('person/template',
                            array(
                            'form' => $personForm,
                        ));


                        if ($rType == Recruitment\Entity\Recruitment::STUDENT_RECRUITMENT_TYPE) {
                            echo $this->partial('disclosure/template',
                                array(
                                'form' => $regForm,
                            ));

                            if ($regForm->has('preInterview')) {
                                echo $this->partial('pre-interview/template',
                                    array(
                                    'form' => $regForm->get('preInterview'),
                                ));
                            }
                        } else {

                            echo $this->partial('volunteer/template',
                                array(
                                'form' => $regForm,
                            ));
                        }
                        ?>

                        <div class="form-group">
                            <div class="col-xs-12 col-md-12">
                                <?php echo $this->formRow($form->get('submit')->setValue('Salvar')); ?>
                            </div>
                        </div>

                        <?php echo $this->form()->closeTag(); ?>

                    </div>
                    <!-- /.tab-pane -->

                <?php endif; ?>

            </div>
            <!-- /.tab-content -->
        </div>
        <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->
</div>