<div style="margin:0;padding:0">
    <table border="0" cellspacing="0" cellpadding="0" width="100%" style="background:#2d3033;border:none;">
        <tbody><tr>
                <td align="center" style="padding:12px 0; vertical-align: middle;">
                    <a href="<?php echo $this->serverUrl();?>" target="_blank" style="text-decoration: none;color:white;
                       font-family: 'Arial Black', Gadget, sans-serif; font-size:18px;">
                        <img src="<?php echo $this->serverUrl('/img/logo_branco.png');?>" alt="CATS" width="120"> Curso Assistencial Theodomiro Santiago
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
    <table border="0" cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;border-spacing:0">
        <tbody>
            <tr>
                <td bgcolor="#088080">
                    <table border="0" cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;border-spacing:0">
                        <tbody>
                            <tr>
                                <td  colspan="3" style="color:#c2dee5;font-family: 'Arial Black', Gadget, sans-serif;font-size:25px;line-height:30px;text-align:center; padding-top: 40px;">
                                    PROCESSO SELETIVO DE ALUNOS - INSCRIÇÃO
                                </td>
                            </tr>
                            <tr>
                                <td style="vertical-align:top;color:#c2dee5;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:16px;line-height:24px;text-align:left;padding:0px 20px 0 20px; width: 20%;">
                                    Informações de inscrição:
                                    <ul>
                                        <li>Nº: <b><?php echo $registrationNumber; ?></b></li>
                                        <li>RG: <b><?php echo $rg; ?></b></li>
                                        <li>CPF: <b><?php echo $cpf; ?></b></li>
                                    </ul>
                                </td>
                                <td style="padding:0px 20px 0 20px; width: 60%;">
                                    <table border="0" cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;border-spacing:0">
                                        <tbody>
                                            <tr>
                                                <td align="left" style="vertical-align:top;color:#c2dee5;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:16px;line-height:24px;text-align:justify;">
                                                    Parabéns, <?php echo $name ?>! Sua inscrição para o processo seletivos de alunos foi realizada com sucesso. Por favor, esteja sempre atento as etapas, documentos e datas do processo seletivo.<br><br>
                                                    Para auxiliá-lo preparamos um espaço para que você acompanhe sua inscrição. Para acessá-lo basta utilizar o cpf de inscrição.
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="padding-top:16px">
                                                    <a href="<?php echo $this->serverUrl($this->url('recruitment/registration', [
                                                        'action' => 'access',
                                                    ])); ?>" style="background-color:transparent;cursor:pointer;
                                                    border-radius:100px;color:#ffffff;display:inline-block;
                                                    font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:20px;
                                                    font-weight:600;line-height:64px;text-align:center;text-decoration:none;width:100%;
                                                    border:2px solid #ffffff; max-width: 600px;" target="_blank">Minha Inscrição</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td style="vertical-align:top;color:#c2dee5;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:16px;line-height:24px;text-align:center;padding:0px 20px 0 20px; width: 20%;">
                                    Você poderá estudar utilizando nossas provas anteriores<br><br>
                                    <a href="<?php echo $this->serverUrl('/#tests'); ?>" style="background-color:transparent;cursor:pointer;
                                                    border-radius:100px;color:#ffffff;display:inline-block;
                                                    font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:20px;
                                                    font-weight:600;line-height:64px;text-align:center;text-decoration:none;width:100%;
                                                    border:2px solid #ffffff;max-width: 300px;" target="_blank">Provas</a><br><br>
                                                    
                                    Caso queira consultar novamente o edital, basta acessar o link abaixo<br><br>
                                    <a href="<?php echo $this->serverUrl('/docs/' . $publicNotice); ?>" style="background-color:transparent;cursor:pointer;
                                                    border-radius:100px;color:#ffffff;display:inline-block;
                                                    font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:20px;
                                                    font-weight:600;line-height:64px;text-align:center;text-decoration:none;width:100%;
                                                    border:2px solid #ffffff;max-width: 300px;" target="_blank">Edital</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table border="0" cellspacing="0" cellpadding="0" width="100%" style="border-collapse:collapse;border-spacing:0">
                        <tbody>
                            <tr>
                                <td>
                                    <!--<img src="https://ci6.googleusercontent.com/proxy/qPkz7D0JddssUqYOqI-OXjeAOIgyyOA8eZtBLtwi5ooNsJVhmP2IDWJB_pUnufvP_YHD9hd1hR1yZUeMxjC2xhBBEIgNnjZRjyp0n9h4a9nSYRbOCeaBbcms35jRhv-an6u6xynlY0NaTFNSCXdYu6eJr8rzfdGYZtWRa-g=s0-d-e1-ft#https://gallery.mailchimp.com/8234ed62d6a7fa87721ff1d8a/images/086139ca-316f-4880-b26b-8f83696e0bf4.png" alt="{alt}" style="display:block;max-width:100%" width="100%" tabindex="0">-->
                                   <img src="<?php echo $this->serverUrl('/img/psaemail_v7.jpg'); ?>" alt="Processo Seletivo de Alunos" style="display:block;max-width:100%" width="100%" tabindex="0">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <table bgcolor="#2d3033" border="0" cellpadding="0" cellspacing="0" style="background:#2d3033;color:#aebdc1;font-size:12px;border-collapse:collapse;border-spacing:0" width="100%">
        <tbody><tr>
                <td align="center">
                    <table align="center" border="0" cellpadding="0" cellspacing="0" class="m_5471447872896103326flex-size" style="border-collapse:collapse;border-spacing:0">
                        <tbody><tr>
                                <td align="left" class="m_5471447872896103326text--footer m_5471447872896103326s-tac" style="color:#aebdc1;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:14px;line-height:21px;padding-top:24px">
                                    Tem dúvidas ou precisa de ajuda?
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0">
                        <tbody>
                            <tr>
                                <td align="center" style="padding:32px 12px 0 12px">
                                    <a href="https://www.facebook.com/cats.familia/" style="text-decoration:none;cursor:pointer;" target="_blank">
                                        <img alt="Facebook Icon" border="0" height="30" src="<?php echo $this->serverUrl('/img/facebook.png');?>" width="30">
                                    </a>
                                </td>
                            </tr>
                        </tbody></table>
                    <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0">
                        <tbody>
                            <tr>
                                <td align="center" style="color:#aebdc1;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;padding:32px 20px 0 20px">
                                    © 2003-<?php echo date('Y'); ?> CATS. TODOS OS DIREITOS RESERVADOS.
                                </td>
                            </tr>
                            <tr>
                                <td align="center" style="color:#aebdc1;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;padding:0 20px">
                                    <span>Av. BPS, 1303 – Sala I.1.2.47 – CEP 37500-903, Pinheirinho – Itajubá – MG </span>
                                </td>
                            </tr>
                            <tr>
                                <td align="center" style="color:#aebdc1;font-family:'Open Sans',Verdana,Helvetica,Arial,sans-serif;font-size:12px;line-height:18px;padding:0 20px 10px 20px;">
                                    <span>Fone: (35) 8871-2364. Emails: catsprocessosseletivos@gmail.com catsrpp@gmail.com</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>