
<?php $title = empty($title) ? 'Informações do Responsável' : $title; ?>

<?php foreach ($forms as $relative) : ?>
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title"><?php echo $title; ?></h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="col-xs-12 col-md-12">
                <?php echo $this->formRow($relative->get('relativeRelationship')); ?>
            </div>

        </div>
        <div class="box-body">
            <?php
            echo $this->partial('person/template',
                array(
                'suffix' => ' do Responsável',
                'form' => $relative->get('relative'),
            ));
            ?>
        </div>
    </div>

    <?php
endforeach;
