
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Formação</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('occupation')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('education')); ?>
        </div>
    </div>
</div>


<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Voluntariado</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('volunteerWork')); ?>
        </div>

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('howAndWhenKnowUs')); ?>
        </div>

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('whyWorkWithUs')); ?>
        </div>

        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('volunteerWithUs')); ?>
        </div>
    </div>
</div>

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Autoavaliação</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('responsibility')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('responsibility')); ?>
                    <?php echo $this->formElementErrors($form->get('responsibility')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('proactive')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('proactive')); ?>
                    <?php echo $this->formElementErrors($form->get('proactive')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('volunteerSpirit')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('volunteerSpirit')); ?>
                    <?php echo $this->formElementErrors($form->get('volunteerSpirit')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('commitment')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('commitment')); ?>
                    <?php echo $this->formElementErrors($form->get('commitment')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('teamWork')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('teamWork')); ?>
                    <?php echo $this->formElementErrors($form->get('teamWork')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('efficiency')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('efficiency')); ?>
                    <?php echo $this->formElementErrors($form->get('efficiency')); ?>
                </div>
            </div>
        </div>
        <hr>
        <div class="col-xs-12 col-md-12">
            <div class="form-group">
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formLabel($form->get('courtesy')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formElement($form->get('courtesy')); ?>
                    <?php echo $this->formElementErrors($form->get('courtesy')); ?>
                </div>
            </div>
        </div>
    </div>
</div>