<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Entrevista</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('proactivity')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('commitmentAndEfficiency')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('volunteerProfile')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('interest')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('interpersonalRelationship')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('personality')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('coherence')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('testClass')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('result')); ?>
        </div>
    </div>
</div>
