
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Formação</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('occupation')); ?>
        </div>
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('education')); ?>
        </div>
    </div>
</div>  

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Interesse</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12 col-md-12">
            <?php echo $this->formRow($form->get('desiredJobs')); ?>
        </div>
    </div>
</div>

<?php
if ($form->has('volunteerInterview')) {
    echo $this->partial('volunteer-interview/template', array(
        'form' => $form->get('volunteerInterview'),
        'regForm' => $form,
    ));
}