<?php $this->headLink()->appendStylesheet($this->basePath('vendor/AdminLTE/plugins/bootstrap-slider/slider.css')); ?>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Entrevista</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('date')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('startTime')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('interviewers')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('interviewersInitialComments')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($regForm->get('volunteerWork')); ?>
        </div>

        <div class="col-xs-12">
            <?php echo $this->formRow($regForm->get('howAndWhenKnowUs')); ?>
        </div>

        <div class="col-xs-12">
            <?php echo $this->formRow($regForm->get('extensionProjects')); ?>
        </div>

        <div class="col-xs-12">
            <?php echo $this->formRow($regForm->get('whyWorkWithUs')); ?>
        </div>

        <div class="col-xs-12">
            <?php echo $this->formRow($regForm->get('volunteerWithUs')); ?>
        </div>
        
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('hometown')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('interests')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('interpersonalRelationship')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('proactivity')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('qualities')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('flaws')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('potentialIssues')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('flexibilityAndResponsability')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('coherenceTest')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('expectedContribution')); ?>
        </div>
        <div class="col-xs-12 interview-slider">
            <?php echo $this->formRow($form->get('interestRating')); ?>
        </div>
        <div class="col-xs-12">
            <?php echo $this->formRow($form->get('endTime')); ?>
        </div>
    </div>
</div>
