
<?php $this
    ->headLink()
    ->appendStylesheet($this->basePath('vendor/AdminLTE/plugins/bootstrap-slider/slider.css')); ?>

<section class="content">

    <p><?php echo $this->message; ?></p>

    <div class="row">
        <?php if ($this->form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_number')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_year')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_begindate')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_enddate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group 
                    <?php
                    echo $this->formElementErrors($form->get('recruitment_public_notice')) !== "" ? 'has-error' : '';
                    ?>" >
                             <?php echo $this->formLabel($form->get('recruitment_public_notice')); ?>
                        <div class="input-group btn-file">
                            <span class="input-group-addon"><i class="fa fa-file-pdf-o"></i></span>
                            <?php echo $this->formElement($form->get('recruitment_public_notice')); ?>
                            <span class="form-control btn-file-name">Nenhum arquivo selecionado</span>
                        </div>

                        <?php echo $this->formElementErrors($form->get('recruitment_public_notice')); ?>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('recruitment_type')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('recruitmentSocioeconomicTarget')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('recruitmentVulnerabilityTarget')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('recruitmentStudentTarget')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <br>
                    <?php echo $this->formRow($form->get('Submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>

        <?php endif; ?>
    </div>

</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/recruitment/create';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>