<section class="content">

    <p><?php echo $this->message; ?></p>

    <div class="row">
        <?php if ($this->form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_number')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_year')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_begindate')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment_enddate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group 
                    <?php
                    echo $this->formElementErrors($form->get('recruitment_public_notice')) !== "" ? 'has-error' : '';
                    ?>" >
                             <?php echo $this->formLabel($form->get('recruitment_public_notice')); ?>
                        <div class="input-group btn-file">
                            <span class="input-group-addon"><i class="fa fa-file-pdf-o"></i></span>
                            <?php echo $this->formElement($form->get('recruitment_public_notice')); ?>
                            <span class="form-control btn-file-name">Nenhum arquivo selecionado</span>
                        </div>
                        
                        <?php echo $this->formElementErrors($form->get('recruitment_public_notice')); ?>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('recruitment_type')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('Submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>

        <?php endif; ?>
    </div>

</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDatepickers = function () {

            $('.datepicker').closest('.input-group').datetimepicker({
                format: 'DD/MM/YYYY',
                minDate: moment(),
                useCurrent: false,
                maxDate: moment().add(18, 'months'),
                locale: 'pt-br',
                viewMode: 'years',
                viewDate: moment()
            });
        };

        return {
            init: function () {
                initDatepickers();
            }
        };

    }());


</script>