<section class="content-header">
    <h1>Criar um novo processo seletivo</h1>
    <hr>
    <p><?php echo $this->message; ?></p>
</section>

<section class="content">



    <div class="row">
        <?php if ($this->form !== null): ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php
                $form = $this->form;

                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class='form-group'>
                    <label for='recruitment_number'>Nº do processo seletivo</label>
                    <?php
                    echo $this->formRow($form->get('recruitment_number'));
                    ?>
                </div>

                <div class='form-group'>
                    <label for='recruitment_year'>Ano do processo seletivo</label>
                    <?php
                    echo $this->formRow($form->get('recruitment_year'));
                    ?>
                </div>

                <div class="row">
                    <div class="form-group col-xs-6 col-md-6">
                        <label for='recruitment_begindate'>Data de Início</label>
                        <?php
                        echo $this->formRow($form->get('recruitment_begindate'));
                        ?>
                    </div>
                    <div class="form-group col-xs-6 col-md-6">
                        <label for='recruitment_enddate'>Data de Término</label>
                        <?php
                        echo $this->formRow($form->get('recruitment_enddate'));
                        ?>
                    </div>
                </div>
                <div class='form-group'>
                    <label for='recruitment_public_notice'>Edital</label><br>
                    <div class="btn btn-success btn-file">
                        <i class="fa fa-file-pdf-o"></i> Procurar

                        <?php
                        echo $this->formRow($form->get('recruitment_public_notice'));
                        ?>
                    </div>
                    <span class="file-label"></span>
                </div>

                <div class='form-group'>
                    <label for='recruitment_type'>Tipo de processo seletivo</label>
                    <?php
                    echo $this->formRow($form->get('recruitment_type'));
                    ?>
                </div>

                <div class="form-group">
                    <?php
                    echo $this->formSubmit($form->get('Submit'));
                    ?>
                    <?php echo $this->form()->closeTag(); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>

</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDatepickers = function () {
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                setDate: moment().format('DD/MM/YYYY'),
                startDate: moment().format('DD/MM/YYYY'),
                endDate: moment().add(1, 'years').format('DD/MM/YYYY'),
                startView: 0,
                autoclose: true,
                language: 'pt-BR'
            });
        };

        return {
            init: function () {
                initDatepickers();
            }
        };

    }());


</script>