<?php
$this
    ->headLink()
    ->appendStylesheet($this->basePath('vendor/AdminLTE/plugins/bootstrap-slider/slider.css'));

?>

<section class="content">
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <?php if ($this->form !== null): 
                
            ?>
            <div class="col-xs-12 col-md-6 col-md-offset-3">
                <?php
                $form->prepare();
                $fs = $this->form->get('recruitment');
                echo $this->form()->openTag($form);
                ?>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('recruitmentNumber')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('recruitmentYear')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('recruitmentBeginDate')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('recruitmentEndDate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group 
                    <?php
                    echo $this->formElementErrors($fs->get('recruitmentPublicNotice')) !== "" ? 'has-error' : '';
                    ?>" >
                             <?php echo $this->formLabel($fs->get('recruitmentPublicNotice')); ?>
                        <div class="input-group btn-file">
                            <span class="input-group-addon"><i class="fa fa-file-pdf-o"></i></span>
                            <?php echo $this->formElement($fs->get('recruitmentPublicNotice')); ?>
                            <span class="form-control btn-file-name">Nenhum arquivo selecionado</span>
                        </div>
                        
                        <?php echo $this->formElementErrors($fs->get('recruitmentPublicNotice')); ?>
                    </div>
                    <p>Obs.: Tente manter o arquivo do edital com menos de 1MB. Assim, os candidatos poderão acessá-lo mais rapidamente em redes <em>Wi-Fi</em>.
                        <br>
                    </p>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('recruitmentType')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <hr>
                    <h4 class="text-center">Os Campos a seguir são apenas para processos seletivos de alunos</h4>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('recruitmentSocioeconomicTarget')); ?>
                    <p class="text-center">Quanto maior o número, melhor a condição socioeconômica do candidato</p>

                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('recruitmentVulnerabilityTarget')); ?>
                    <p class="text-center">Quanto maior o número, mais vulnerável é o candidato</p>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('recruitmentStudentTarget')); ?>
                    <p class="text-center">Quanto maior o número, maior é a capacidade de aprendizado do candidato</p>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('subscriptionDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('confirmationStartDate')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('confirmationEndDate')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('confirmationDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('examDate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('examDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('examResultDate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('examResultDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('preInterviewStartDate')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('preInterviewDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('interviewStartDate')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('interviewEndDate')); ?>
                </div>
                
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('interviewDescription')); ?>
                </div>
                
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('resultDate')); ?>
                </div>
                
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('resultDescription')); ?>
                </div>
                
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('enrollmentStartDate')); ?>
                </div>
                
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($fs->get('enrollmentEndDate')); ?>
                </div>
                
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($fs->get('enrollmentDescription')); ?>
                </div>

                <div class="col-xs-12 col-md-12">
                    <br>
                    <?php echo $this->formRow($form->get('Submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        <?php endif; ?>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/recruitment/create';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();
</script>