<section class="content-header">
    <h1>Processos seletivos</h1>
    <hr>
    <p><?php echo $this->message; ?></p>
</section>


<section class="content">
    
    <div class="table-responsive col-xs-8 col-md-8 col-md-offset-2">
        <table id="recruitment-table" class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Nº</th>
                    <th class="text-center">Ano</th>
                    <th class="text-center">Data de Início</th>
                    <th class="text-center">Data de Término</th>
                    <th class="text-center">Tipo</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->recruitments as $recruitment): ?>
                    <tr class="cats-row" data-id="<?php echo $recruitment->getRecruitmentId(); ?>">
                        <td class="text-center"> <?php echo $this->escapeHtml($recruitment->getRecruitmentId()); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($recruitment->getRecruitmentNumber()); ?></td>
                        <td class="text-center"> <?php echo $this->escapeHtml($recruitment->getRecruitmentYear()); ?></td>
                        <td class="text-center"> <?php echo $recruitment->getRecruitmentBeginDate()->format('d/m/Y'); ?></td>
                        <td class="text-center"> <?php echo $recruitment->getRecruitmentEndDate()->format('d/m/Y'); ?></td>
                        <td class="text-center"> <?php
                            echo ($recruitment->getRecruitmentType() == 1) ? 'Processo Seletivo de Alunos' : 'Processo Seletivo de Voluntários';
                            ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDataTable = function () {

            var recruitmentTable = $('#recruitment-table').DataTable({
                dom: 'lftip',
                paging: false
            });
        };

        return {
            init: function () {
                initDataTable();
            }
        };

    }());

</script>
