<section class="content">
    <?php 
        $this->headTitle()->append('Criar configuração de fundo')
            ->setSeparator(' - ');
    ?>
    <p><?php echo $this->message; ?></p>
    <div class="row">
        <?php
        echo $this->partial('student-bg-config-form/template', array(
                'form' => $this->form,
                'imgFieldText' => 'Nenhum arquivo selecionado.',
                'config' => null,
                'students' => null,
            ));
        ?>
    </div>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/documents/student-bg-config/create';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>