<section class="content">
    
    <p> <?php echo $message ?> </p>
    
    <?php if ($configs): ?>
        <div class="table-responsive col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <table id="config-table" class="table table-condensed table-striped">
                <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Frase</th>
                        <th class="text-center">Autor</th>
                        <th class="text-center">Imagem</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->configs as $config): ?>
                        <tr class="cats-row" data-id="<?php echo $config->getStudentBgConfigId(); ?>">
                            <td class="text-center"> <?php echo $config->getStudentBgConfigId(); ?></td>
                            <td class="text-center"> <?php echo $config->getStudentBgConfigPhrase(); ?></td>
                            <td class="text-center"> <?php echo $config->getStudentBgConfigAuthor(); ?></td>
                            <td class="text-center"> <a href="/img/<?php echo $config->getStudentBgConfigImg(); ?>">
                                <?php echo $config->getStudentBgConfigImg(); ?> </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else: ?>
        <p> Não há configurações cadastradas. </p>
    <?php endif; ?>
</section>

<script>

    var standardConfig = (function () {

        initDataTable = function () {

            $('#config-table').DataTable({
                dom: 'lftip',
                paging: false
            });
        };

        return {
            init: function () {
                initDataTable();
            }
        };

    }());

</script>