<section class="content">

    <p><?php echo $this->message; ?></p>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-2">
            <?php 
                echo $this->partial(
                    'student-bg-configs/template', 
                    [
                        'configs' => $this->configs,
                    ]
                );
            ?>
        </div>
    </div>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/documents/student-bg-config/index';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();

</script>