
<div class='container'>

    <div class="row">
        <h2> Hello from loginAction of LoginController! </h2>
        <hr>
        <?php
        echo $this->message;
        ?>
    </div>
    <div class="col-xs-6 col-md-4">
        <?php
        $form = $this->form;

        $form->setAttribute('action', $this->url('authentication/default', array('controller' => 'login', 'action' => 'login'))
        );

        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class='form-group'>
            <label for='username'>Email</label>
            <?php
            echo $this->formRow($form->get('username')
                            ->setAttribute('class', 'form-control')
            );
            ?>
        </div>
        <div class='form-group'>
            <label for='password'>Senha</label>
            <?php
            echo $this->formRow($form->get('password')
                            ->setAttribute('class', 'form-control')
            );
            ?>
        </div>
        <div class='checkbox'>
            <label>
                <?php
                echo $this->formRow($form->get('rememberme'));
                ?>
                Remember Me?
            </label>
        </div>
        <?php
        echo $this->formSubmit($form->get('submit')
                        ->setAttribute('class', 'btn btn-primary btn-lg'));
        ?>
        <?php echo $this->form()->closeTag(); ?>
        <?php
        // view helper
        $user = $this->identity();
        if ($user):
            echo 'Logged in as ' . $this->escapeHtml($user->getUserName());
            ?>
            | <a href="<?php echo $this->url('authentication/default', array('controller' => 'login', 'action' => 'logout')); ?>">
                <?php echo $this->translate('Logout'); ?>
            </a> 
            <?php
        else:
            echo $this->translate('Not logged in');
        endif;
        ?>
        <p>
            <a href="<?php echo $this->url('authentication/default', array('controller' => 'registration', 'action' => 'forgotten-password')); ?>"><?php echo $this->translate('Forgotten Password'); ?></a>
        </p>
    </div>
</div>