

<div class = "container">
    <div class="wrapper">
        
        <?php
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        
        <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>

        <?php
        echo $this->formRow($form->get('username'));
        echo $this->formRow($form->get('password'));
        echo $this->formRow($form->get('rememberme')) . ' ' . 'Continuar conectado?';
        echo '<br><br>';
        echo $this->formSubmit($form->get('submit')) . '<br>';
        echo $this->message;
        ?>

    </div>
</div>

<style>

    .wrapper {    
        margin-top: 80px;
        margin-bottom: 20px;
    }

    .form-signin {
        max-width: 420px;
        padding: 30px 38px 66px;
        margin: 0 auto;
        background-color: #eee;
        border: 3px solid rgba(0,0,0,0.1);  
    }

    .form-signin-heading {
        text-align:center;
        margin-bottom: 30px;
    }

    .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
    }

    input[type="text"] {
        margin-bottom: 0px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }

    input[type="password"] {
        margin-bottom: 20px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }

</style>