<section class="content">
    <div class="row">
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <?php $person = $registration->getPerson(); ?>
                    <h2 class="text-center"><?php echo $person->getPersonFirstName() . " " . $person->getPersonLastName() ?></h2>
                    <h2 class="text-muted text-center">
                        <small>Nº de inscrição: <?php echo $registration->getRegistrationNumber(); ?></small>
                    </h2>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Data de nascimento: </b> <a class="pull-right"><?php echo $person->getPersonBirthday(); ?></a>
                        </li>
                        <li class="list-group-item">
                            <b>CPF:</b> <a class="pull-right"><?php echo $person->getPersonCpf(); ?></a>
                        </li>
                        <li class="list-group-item">
                            <b>RG:</b> <a class="pull-right"><?php echo $person->getPersonRg(); ?></a>
                        </li>
                        <li class="list-group-item">
                            <b>Email:</b> <a class="pull-right"><?php echo $person->getPersonEmail(); ?></a>
                        </li>
                        <li class="list-group-item">
                            <b>Telefone:</b> <a class="pull-right"><?php echo $person->getPersonPhone(); ?></a>
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="box box-primary">
                <!-- /.box-header -->
                <div class="box-body">
                    <a target="_blank" href="/docs/<?php echo $recruitment->getRecruitmentPublicNotice(); ?>" class="btn btn-flat btn-primary btn-block"><b>Edital</b></a>
                    <a target="_blank" href="https://www.facebook.com/cats.familia" class="btn btn-block btn-social btn-facebook">
                        <i class="fa fa-facebook"></i> Nos encontre no Facebook
                    </a>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#status" data-toggle="tab" aria-expanded="true">Situação do Candidato</a></li>
                    <li class=""><a href="#edit" data-toggle="tab" aria-expanded="false">Editar Dados</a></li>
                </ul>
                <div class="tab-content">
                    <!--PAINEL DE STATUS DO CANDIDATO-->
                    <?php
                    //TO-DO Tratamento de candidatos na lista de espera
                    //INICIO tratamento dos blocos em cores
                    //candidato passou pela etapa
                    $completed = "green-active";
                    //etapa está sendo confirmada/prova ainda não realizada/resultado da prova ainda não divulgado/...
                    $processing = "navy";
                    //todas as etapas que esperam pelas anteriores que não são "processing"
                    $incomplete = "teal";
                    //etapas de convocação ou dias de prova
                    $summoned = "primary";
                    //etapas de reprovação ou cancelamento
                    $disapproved = "black";

                    $inscription = $completed;
                    $confirmation = $processing;
                    $exam = $incomplete;
                    $examResult = $incomplete;
                    $preInterview = $incomplete;
                    $interview = $incomplete;
                    $finalResult = $incomplete;
                    $enrollment = $incomplete;

                    //recolhe os timeStamp
                    $rstatus = $registration->getRegistrationStatus();
                    foreach ($rstatus as $st):
                        if ($st->getRecruitmentStatus()->getStatusType() == "INSCRITO") {
                            $inscriptionStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "CONFIRMADO") {
                            $confirmationStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "CONVOCADO PARA PRÉ-ENTREVISTA") {
                            $preInterviewSummonedStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "PRÉ-ENTREVISTA CONCLUÍDA") {
                            $preInterviewConclusionStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "CONVOCADO PARA ENTREVISTA") {
                            $interviewSummonedStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "APROVADO EM ENTREVISTA") {
                            $approvedStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "REPROVADO EM ENTREVISTA") {
                            $disapprovedStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        } elseif ($st->getRecruitmentStatus()->getStatusType() == "LISTA DE ESPERA DA ENTREVISTA") {
                            $waitListStatusTime = $st->getTimestamp('d/m/Y \à\s H:i:s');
                        }
                    endforeach;

                    //tratamento para blocos que mudam com o tempo 
                    //só modifca a cor se o candidato foi devidamente confirmado/entrevistad
                    $currentDate = new \DateTime();
                    $confirmationStartDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getConfirmationStartDate());
                    $confirmationEndDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getConfirmationEndDate());
                    $examDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getExamDate());
                    $examResultDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getExamResultDate());
                    $finalResultDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getResultDate());
                    $preInterviewDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getPreInterviewStartDate());
                    $interviewDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getInterviewStartDate());
                    $enrollmentStartDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getEnrollmentStartDate());
                    $enrollmentEndDate = \DateTime::createFromFormat('d/m/Y', $recruitment->getEnrollmentEndDate());

                    //dia da confirmação
                    //tratamento com tempo e status
                    if (isset($confirmationStatusTime) == false) {
                        if ($confirmationStartDate > $currentDate) {
                            $confirmation = $processing;
                        } elseif ($confirmationStartDate <= $currentDate && $currentDate <= $confirmationEndDate) {
                            $confirmation = $summoned;
                        } elseif ($confirmationEndDate < $currentDate) {
                            //demora na confirmação
                            $confirmation = $processing;
                        }
                    } else {
                        $confirmation = $completed;
                    }

                    //dia da prova
                    //tratamento com tempo
                    if ($confirmation == $completed) {
                        if ($examDate > $currentDate) {
                            $exam = $processing;
                        } elseif ($examDate == $currentDate) {
                            $exam = $summoned;
                        } elseif ($examDate < $currentDate) {
                            $exam = $completed;
                        }
                    }

                    //dia do resultado da prova
                    //tratamento com tempo
                    if ($exam == $completed) {
                        if ($examResultDate > $currentDate && $examDate < $currentDate) {
                            $examResult = $processing;
                        } elseif ($examResultDate == $currentDate) {
                            $examResult = $summoned;
                        } elseif ($examResultDate < $currentDate) {
                            $examResult = $completed;
                        }
                    }

                    //dia da pré entrevista
                    //tratamento com tempo e status
                    if (isset($preInterviewSummonedStatusTime) && isset($preInterviewConclusionStatusTime)) {
                        $preInterview = $completed;
                    } elseif (isset($preInterviewSummonedStatusTime) && isset($preInterviewConclusionStatusTime) == false) {
                        if ($preInterviewDate > $currentDate) {
                            $preInterview = $processing;
                        } elseif ($preInterviewDate < $currentDate) {
                            //candidato não fez a pré-entrevista
                            $preInterview = $disapproved;
                        }
                    } elseif (isset($preInterviewSummonedStatusTime) == false && $preInterviewDate < $currentDate) {
                        //candidato não chamado para pré-entrevista
                        $preInterview = $disapproved;
                    } elseif (isset($preInterviewSummonedStatusTime) == false && $preInterviewDate == $currentDate) {
                        $preInterview = $processing;
                    }

                    //dia da entrevista
                    //tratamento com tempo e status
                    if (isset($approvedStatusTime) == false) {
                        if ($preInterview == $completed) {
                            if ($interviewDate > $currentDate) {
                                $interview = $processing;
                            } elseif ($interviewDate == $currentDate) {
                                $interview = $summoned;
                            } elseif (isset($disapprovedStatusTime)) {
                                //não aprovado em entrevista
                                $interview = $disapproved;
                            } else {
                                //demora na aprovação/não aprovação
                                $interview = $processing;
                            }
                        }
                    } else {
                        //aprovado em entrevista
                        $interview = $completed;
                    }

                    //dia do resultado Final
                    //tratamento com tempo
                    if ($interview == $completed) {
                        if ($finalResultDate > $currentDate) {
                            $finalResult = $processing;
                        } elseif ($finalResultDate == $currentDate) {
                            $finalResult = $summoned;
                        } elseif ($finalResultDate < $currentDate) {
                            $finalResult = $completed;
                        }
                    }

                    //dia da matrícula
                    //tratamento com tempo
                    if ($finalResult == $completed) {
                        if ($enrollmentStartDate > $currentDate) {
                            $enrollment = $processing;
                        } elseif ($enrollmentStartDate <= $currentDate && $currentDate <= $enrollmentEndDate) {
                            $enrollment = $summoned;
                        } elseif ($enrollmentEndDate < $currentDate) {
                            $enrollment = $completed;
                        }
                    }
                    ?>
                    <!--
                        Os blocos: Confirmação; Pré-Entrevista; e Entrevista, contém
                        tratamento para substituir a informação de "a confirmação será realizada nos dias..."
                        por "confirmação realizada no dia..." caso o candidato seja confirmado.
                    -->
                    <div class="tab-pane active" id="status">
                        <div class="row">
                            <div class="col-lg-12 col-xs-12">
                                Olá candidato. Esta é a área de acompanhamento de sua inscrição. Nela você encontrará todas as informações sobre o processo seletivo: 
                                etapas, requisitos, edital e muito mais. Recomendamos sempre que você leia o edital e caso tenha dúvidas entre em contato conosco pela 
                                nossa página do facebook.
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-lg-6 col-xs-12">                      
                                <div class="small-box bg-<?php echo $inscription ?>">
                                    <div class="inner">
                                        <h3>Inscrição</h3>
                                        <p>Realizada no dia <?php echo $inscriptionStatusTime ?></p>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-edit"></i>
                                        1
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getSubscriptionDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-6 col-xs-12">                      
                                <div class="small-box bg-<?php echo $confirmation ?>">
                                    <div class="inner">
                                        <h3>Confirmação </h3>
                                        <?php
                                        if (isset($confirmationStatusTime)) {
                                            echo "<p>Realizada no dia " . $confirmationStatusTime;
                                        } else {
                                            echo "<p>Entre os dias " . $recruitment->getConfirmationStartDate() . ' e ' . $recruitment->getConfirmationEndDate() . "</p>";
                                        }
                                        ?>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-users"></i>
                                        2
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getConfirmationDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $exam ?>">
                                    <div class="inner">
                                        <h3>Prova</h3>
                                        <p>Dia <?php echo $recruitment->getExamDate() ?></p>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-file-text-o"></i>
                                        3
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getExamDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $examResult ?>">
                                    <div class="inner">
                                        <h3>Resultado da Prova</h3>
                                        <p>Dia <?php echo $recruitment->getExamResultDate() ?></p>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-check-square-o"></i>
                                        4
                                    </div>

                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getExamResultDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $preInterview ?>">
                                    <div class="inner">
                                        <h3>Pré-Entrevista</h3>
                                        <?php
                                        if (isset($preInterviewConclusionStatusTime)) {
                                            echo "<p>Realizada no dia " . $preInterviewConclusionStatusTime;
                                        } else {
                                            echo "<p>Dia " . $recruitment->getPreInterviewStartDate() . "</p>";
                                        }
                                        ?>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-files-o"></i>
                                        5
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getPreInterviewDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $interview ?>">
                                    <div class="inner">
                                        <h3>Entrevista</h3>
                                        <?php
                                        if (isset($approvedStatusTime)) {
                                            echo "<p>Candidato APROVADO no dia " . $approvedStatusTime;
                                        } elseif (isset($disapprovedStatusTime)) {
                                            echo "<p>Candidato REPROVADO no dia " . $disapprovedStatusTime;
                                        } else {
                                            echo "<p>Entre os dias " . $recruitment->getInterviewStartDate() . ' e ' . $recruitment->getInterviewEndDate() . "</p>";
                                        }
                                        ?>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-commenting-o"></i>
                                        6
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getInterviewDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $finalResult ?>">
                                    <div class="inner">
                                        <h3>Resultado Final </h3>
                                        <p>Dia <?php echo $recruitment->getResultDate() ?></p>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa fa-gavel"></i>
                                        7
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getResultDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-xs-12">
                                <div class="small-box bg-<?php echo $enrollment ?>">
                                    <div class="inner">
                                        <h3>Matrícula</h3>
                                        <p>Entre os dias <?php echo $recruitment->getEnrollmentStartDate() . ' e ' . $recruitment->getEnrollmentEndDate() ?></p>
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-user"></i>
                                        8
                                    </div>
                                    <div class="small-box-footer">
                                        <p>
                                            <?php echo $recruitment->getEnrollmentDescription(); ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--Edição dos dados-->
                    <div class="tab-pane" id="edit">
                        <?php if ($this->form !== null): ?>
                            <?php $form->prepare(); ?>
                            <div class="row">
                                <div class="col-xs-12 col-md-10 col-md-offset-1"
                                <?php echo $this->form()->openTag($form); ?>
                                <?php
                                $registration = $form->get('registration');
                                $person = $registration->get('person');
                                echo $this->partial('person/template', array(
                                    'form' => $person,
                                ));
                                echo $this->partial('disclosure/template', array(
                                    'form' => $registration,
                                ));
                                ?>

                                     <?php echo $this->formHidden($form->get('registrationCsrf')); ?>

                                     <div class="col-xs-12 col-md-12">
                                        <div class="form-group">
                                            <?php echo $this->formRow($form->get('registrationConsent')->setAttribute('checked', true)); ?>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="col-xs-12 col-md-12">
                                        <?php echo $this->formRow($form->get('submit')->setValue('Atualizar')); ?>
                                    </div>
                                    <?php echo $this->form()->closeTag(); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/candidate';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>