<section class="content">
    <?php if ($registration): ?>
        <div class="row">
            <div class="col-md-3">
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        <?php $person = $registration->getPerson(); ?>
                        <h2 class="text-center"><?php echo $person->getPersonFirstName() . " " . $person->getPersonLastName() ?></h2>
                        <h2 class="text-muted text-center">
                            <small>Nº de inscrição: <?php echo $registration->getRegistrationNumber(); ?></small>
                        </h2>

                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b>Data de nascimento: </b> <a class="pull-right"><?php echo $person->getPersonBirthday(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>CPF:</b> <a class="pull-right"><?php echo $person->getPersonCpf(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>RG:</b> <a class="pull-right"><?php echo $person->getPersonRg(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>Email:</b> <a class="pull-right"><?php echo $person->getPersonEmail(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>Telefone:</b> <a class="pull-right"><?php echo $person->getPersonPhone(); ?></a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <a target="_blank" href="/docs/<?php echo $recruitment->getRecruitmentPublicNotice(); ?>" class="btn btn-flat btn-primary btn-block"><b>Edital</b></a>
                        <a target="_blank" href="https://www.facebook.com/cats.familia" class="btn btn-block btn-social btn-facebook">
                            <i class="fa fa-facebook"></i> Nos encontre no Facebook
                        </a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>

            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#status" data-toggle="tab" aria-expanded="true">Situação do Candidato</a></li>
                        <li class=""><a href="#edit" data-toggle="tab" aria-expanded="false">Editar Dados</a></li>
                    </ul>
                    <div class="tab-content">
                        <!--PAINEL DE STATUS DO CANDIDATO-->
                        <?php
                        $prev = "green-active";
                        $next = "primary";

                        ?>
                        <!--
                            Os blocos: Confirmação; Pré-Entrevista; e Entrevista, contém
                            tratamento para substituir a informação de "a confirmação será realizada nos dias..."
                            por "confirmação realizada no dia..." caso o candidato seja confirmado.
                        -->
                        <div class="tab-pane active" id="status">
                            <div class="row">
                                <div class="col-lg-12 col-xs-12">
                                    Olá candidato. Esta é a área de acompanhamento de sua inscrição. Nela você encontrará todas as informações sobre o processo seletivo: 
                                    etapas, requisitos, edital e muito mais. Recomendamos sempre que você leia o edital e caso tenha dúvidas entre em contato conosco pela 
                                    nossa página do facebook.
                                </div>
                            </div>
                            <hr>

                            <div class="row">
                                <div class="col-lg-6 col-xs-12">                      
                                    <div class="small-box bg-<?php echo $blockStatus['registration'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Inscrição</h3>
                                            <p>Sua inscrição foi realizada com sucesso.</p>
                                            <span>
                                                <?php echo $recruitment->getSubscriptionDescription(); ?>
                                            </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-edit"></i>
                                            1
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-xs-12">                      
                                    <div class="small-box bg-<?php echo $blockStatus['confirmation'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Confirmação </h3>
                                            <p>
                                                <?php if ($blockStatus['confirmation']): ?>
                                                    Sua confirmação foi realizada com sucesso.
                                                <?php else: ?>
                                                    A confirmação deve ser feita entre os dias <?php echo $recruitment->getConfirmationStartDate(); ?> e <?php echo $recruitment->getConfirmationEndDate(); ?>.
                                                <?php endif; ?>
                                                <span>
                                                    <?php echo $recruitment->getConfirmationDescription(); ?>
                                                </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-users"></i>
                                            2
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['exam'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Prova</h3>
                                            <p>Dia <?php echo $recruitment->getExamDate() ?></p>
                                            <span>
                                                <?php echo $recruitment->getExamDescription(); ?>
                                            </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-file-text-o"></i>
                                            3
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['exam-result'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Resultado da Prova</h3>
                                            <p>Dia <?php echo $recruitment->getExamResultDate() ?></p>
                                            <span><?php echo $recruitment->getExamResultDescription(); ?></span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-check-square-o"></i>
                                            4
                                        </div>
                                        <?php if ($blockStatus['exam-result']): ?>
                                            <a class="small-box-footer" href="/recruitment/registration/exam-result">
                                                <h4>Acessar Resultado <i class="fa fa-arrow-circle-right"></i>
                                                </h4>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['preinterview'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Pré-Entrevista</h3>
                                            <p>
                                                <?php if ($blockStatus['preinterview-complete']): ?>
                                                    Sua pré-entrevista foi realizada com sucesso.
                                                <?php else: ?>
                                                    A pré-entrevista deve ser realizada a partir de <?php echo $recruitment->getPreInterviewStartDate(); ?>.
                                                <?php endif; ?>
                                            </p>
                                            <span>
                                                <?php echo $recruitment->getPreInterviewDescription(); ?>
                                            </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-files-o"></i>
                                            5
                                        </div>
                                        <?php if ($blockStatus['preinterview']): ?>
                                            <a class="small-box-footer" href="/recruitment/pre-interview/student-pre-interview-form">
                                                <h4>Acessar Formulário de Pre-entrevista <i class="fa fa-arrow-circle-right"></i>
                                                </h4>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['interview'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Entrevista</h3>
                                            <p>
                                                <?php if ($blockStatus['interviewed']): ?>
                                                    Sua entrevista foi realizada com sucesso.
                                                <?php else: ?>
                                                    Entre os dias <?php echo $recruitment->getInterviewStartDate(); ?> e <?php echo $recruitment->getInterviewEndDate(); ?>. 
                                                <?php endif; ?>
                                                <span>
                                                    <?php echo $recruitment->getInterviewDescription(); ?>
                                                </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-commenting-o"></i>
                                            6
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['result'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Resultado Final </h3>
                                            <p>Dia <?php echo $recruitment->getResultDate() ?></p>
                                            <span>
                                                <?php echo $recruitment->getResultDescription(); ?>
                                            </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa fa-gavel"></i>
                                            7
                                        </div>
                                        <?php if ($blockStatus['result']): ?>
                                            <a class="small-box-footer" href="/recruitment/registration/final-result">
                                                <h4>Acessar o Resultado Final <i class="fa fa-arrow-circle-right"></i>
                                                </h4>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-xs-12">
                                    <div class="small-box bg-<?php echo $blockStatus['enroll'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Matrícula</h3>
                                            <p>Entre os dias <?php echo $recruitment->getEnrollmentStartDate() . ' e ' . $recruitment->getEnrollmentEndDate() ?></p>
                                            <span><?php echo $recruitment->getEnrollmentDescription(); ?></span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-user"></i>
                                            8
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Edição dos dados-->
                        <div class="tab-pane" id="edit">
                            <?php if ($this->form !== null): ?>
                                <?php $form->prepare(); ?>
                                <div class="row">
                                    <div class="col-xs-12 col-md-10 col-md-offset-1">
                                        <?php echo $this->form()->openTag($form); ?>
                                        <?php
                                        $registration = $form->get('registration');
                                        $person = $registration->get('person');
                                        echo $this->partial('person/template', array(
                                            'form' => $person,
                                        ));
                                        echo $this->partial('disclosure/template', array(
                                            'form' => $registration,
                                        ));

                                        ?>

                                        <?php echo $this->formHidden($form->get('registrationCsrf')); ?>

                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group">
                                                <?php echo $this->formRow($form->get('registrationConsent')->setAttribute('checked', true)); ?>
                                            </div>
                                        </div>
                                        <br>
                                        <div class="col-xs-12 col-md-12">
                                            <?php echo $this->formRow($form->get('submit')->setValue('Atualizar')); ?>
                                        </div>
                                        <?php echo $this->form()->closeTag(); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
        <?php else: ?>
            <h3 class="text-center">Erro inesperado, por favor, entre em contato com o administrador do sistema.</h3>
        <?php endif; ?>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/candidate';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>