<section class="content">
    <p class="no-print">
        <?php echo $this->message; ?>
    </p>
    <br>
    <?php if (isset($this->registrationCardContent)): ?>
        <div class="container no-print">
            <button target="_blank" class="btn btn-primary btn-flat" onclick="window.print();">
                <i class="fa fa-file-pdf-o"></i> Salvar
            </button>
            <br>
        </div>

        <?php echo $this->render('registration-card/template', $registrationCardContent); ?>

    <?php endif; ?>
    <br>
    <?php if ($this->form !== null): ?>
        <?php $form->prepare(); ?>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                <?php
                $registration = $form->get('registration');
                $person = $registration->get('person');
                echo $this->partial('person/template', array(
                    'form' => $person,
                ));

                if ($type === Recruitment\Entity\Recruitment::STUDENT_RECRUITMENT_TYPE) {
                    echo $this->partial('disclosure/template',
                        array(
                        'form' => $registration,
                    ));
                } else {
                    echo $this->partial('volunteer/template',
                        array(
                        'form' => $registration,
                    ));
                }
                ?>

                <?php echo $this->formHidden($form->get('registrationCsrf')); ?>

                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('registrationConsent')); ?>
                    </div>
                </div>
                <br>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/registration';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>
