<section class="content">
    <?php echo $this->message; ?>
    <?php if ($this->form !== null): ?>
        <?php $form->prepare(); ?>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                <?php
                $registration = $form->get('registration');
                $person = $registration->get('person');
                echo $this->partial('person/template', array(
                    'form' => $person,
                ));

                if ($type === Recruitment\Entity\Recruitment::STUDENT_RECRUITMENT_TYPE) {
                    echo $this->partial('disclosure/template',
                        array(
                        'form' => $registration,
                    ));
                } else {
                    echo $this->partial('volunteer/template',
                        array(
                        'form' => $registration,
                    ));

                    if ($registration->has('volunteerInterview')) {
                        echo $this->partial('volunteer-interview/template',
                            array(
                            'form' => $registration->get('volunteerInterview'),
                        ));
                    }
                }
                ?>

                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formLabel($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElement($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElementErrors($form->get('registrationCaptcha')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('registrationConsent')); ?>
                    </div>
                </div>
                <br>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    <?php endif; ?>
</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/registration';

        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };

    })();

</script>
