<section class="content">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 col-xs-10 col-xs-offset-1">
            <p>Formulários disponíveis: </p>
            <ul>
                <li><a href="/recruitment/registration/registrationForm/1">Processos seletivos de alunos</a></li>
                <li><a href="/recruitment/registration/registrationForm/2">Processos seletivos de voluntários</a></li>
            </ul>
        </div>
    </div>
</section>