<section class="content">
    <?php echo $this->message; ?>
    <?php if ($this->form !== null): ?>
        <?php $form->prepare(); ?>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                <?php
                $registration = $form->get('registration');
                $person = $registration->get('person');
                echo $this->partial('person/template', array(
                    'form' => $person,
                ));
                echo $this->partial('disclosure/template',
                    array(
                    'form' => $registration,
                ));
                ?>

                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formLabel($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElement($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElementErrors($form->get('registrationCaptcha')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('registrationConsent')); ?>
                    </div>
                </div>
                <br>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
<?php endif; ?>
</section>

<script>
    var standardConfig = (function () {
        // your module code goes here
        // var config = null;
        /**
         * 
         * private functions
         */
        initDatepickers = function () {
            $('.datepicker').closest('.input-group').datetimepicker({
                format: 'DD/MM/YYYY',
                minDate: moment().subtract(100, 'years'),
                useCurrent: false,
                maxDate: moment().subtract(15, 'years'),
                locale: 'pt-br',
                viewMode: 'years',
                viewDate: moment().subtract(21, 'years')
            });
        };
        initCaptchaOperations = function () {
            $('#captcha_input-refresh').click(function () {
                $.ajax({
                    url: '/recruitment/captcha/refresh',
                    dataType: 'json',
                    success: function (data) {
                        $('#captcha_input-image').attr('src', data.src);
                        $('#captcha_input-hidden').attr('value', data.id);
                    }
                });
            });
        };
        return {
            init: function () {
                initDatepickers();
                initCaptchaOperations();
            }
        };
    }());
</script>