<section class="content">
    <?php echo $this->message; ?>
    <?php if ($this->form !== null): ?>
        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">

                <?php $form->prepare(); ?>

                <?php echo $this->form()->openTag($form); ?>
                <?php
                $registration = $form->get('registration');
                $person = $registration->get('person');
                ?>
                <div class="col-xs-12 col-md-4">
                    <?php echo $this->formRow($person->get('personFirstName')); ?>
                </div>
                <div class="col-xs-12 col-md-8">
                    <?php echo $this->formRow($person->get('personLastName')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($person->get('personGender')); ?>
                </div>

                <div class="form-group">
                    <div class="col-xs-12 col-md-12">
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personBirthday')); ?>
                        </div>
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personCpf')); ?>
                        </div>
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personRg')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-md-12">
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personPhone')); ?>
                        </div>
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personEmail')); ?>
                        </div>                    
                        <div class="col-xs-12 col-md-4">
                            <?php echo $this->formRow($person->get('personEmailConfirm')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($registration->get('recruitmentKnowAbout')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <div class="col-xs-12 col-md-12">
                            <?php echo $this->formLabel($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElement($form->get('registrationCaptcha')); ?>
                        </div>
                        <div class="col-xs-12 col-md-6 col-md-offset-3">
                            <?php echo $this->formElementErrors($form->get('registrationCaptcha')); ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12">
                    <div class="form-group">
                        <?php echo $this->formRow($form->get('registrationConsent')); ?>
                    </div>
                </div>
                <br>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>

            </div>

            <?php echo $this->form()->closeTag(); ?>

        </div>
    </div>
<?php endif; ?>
</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initDatepickers = function () {

            $('.datepicker').closest('.input-group').datetimepicker({
                format: 'DD/MM/YYYY',
                minDate: moment().subtract(100, 'years'),
                useCurrent: false,
                maxDate: moment().subtract(15, 'years'),
                locale: 'pt-br',
                viewMode: 'years',
                viewDate: moment().subtract(21, 'years')
            });
        };

        initCaptchaOperations = function () {
            $('#captcha_input-refresh').click(function () {
                $.ajax({
                    url: '/recruitment/captcha/refresh',
                    dataType: 'json',
                    success: function (data) {
                        $('#captcha_input-image').attr('src', data.src);
                        $('#captcha_input-hidden').attr('value', data.id);
                    }
                });
            });
        };

        return {
            init: function () {
                initDatepickers();
                initCaptchaOperations();
            }
        };

    }());


</script>