<section class="content-header">
    <h1>Perfil do Candidato</h1>
    <p><?php echo $this->message; ?></p>
</section>

<section class="content">
    <?php if ($this->registration !== null): ?>

        <?php
        echo $this->partial('profile/template', array(
            'registration' => $registration,
            'config' => array(
                'isPhotoEditable' => true,
                'showAge' => true,
                'tabs' => array(
                    'recruitment-timeline' => true,
                    'documentation' => true,
                    'score' => true,
                    'info' => true,
                ),
            ),
        ));
        ?>

    <?php endif; ?>
</section>

<script>

    var standardConfig = (function () {
        // your module code goes here
        // var config = null;

        /**
         * 
         * private functions
         */

        initImageUpload = function () {

            var profileDropzone = new Dropzone("#profile-img", {
                paramName: 'profilePhoto',
                maxFilesize: 5,
                uploadMultiple: false,
                acceptedFiles: "image/png, image/jpeg",
                url: "/recruitment/registration/changePhoto/" + $("#profile-img").data('id')
            });

            profileDropzone.on("sending", function (file) {
                // Show the total progress bar when upload starts
                $("#total-progress").css('opacity', '1');
            });

            profileDropzone.on("totaluploadprogress", function (progress) {
                $("#total-progress .progress-bar").css('width', progress + '%');
            });

            profileDropzone.on("queuecomplete", function (progress) {
                // Hide the total progress bar when nothing's uploading anymore
                $("#total-progress").css('opacity', '0');
            });

            profileDropzone.on('success', function (file, data) {
                bootbox.alert(data.message);
                if (data.file !== null) {
                    $("#profile-img").attr('src', data.file + '?' + new Date().getTime());
                }
            });
        };

        return {
            init: function () {
                initImageUpload();
            }
        };

    }());


</script>