<section class="content">

    <p><?php echo $this->message; ?></p>

    <?php if ($form !== null): ?>

        <div class="row">
            <div class="col-xs-12 col-md-8 col-md-offset-2">
                <?php echo $this->form()->openTag($form); ?>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('recruitment')); ?>
                </div>
                <div class="col-xs-12 col-md-6">
                    <?php echo $this->formRow($form->get('registrationStatus')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($form->get('submit')); ?>
                </div>
                <div class="col-xs-12 col-md-12">
                    <?php echo $this->formRow($timestamp->get('timestamp')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
            <input id="showDesiredJobs" type="hidden" value="1">
        </div>
        <br>
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table table-condensed table-bordered" id="recruitment-table" data-show-desired-jobs="1">
                        <thead>
                        <th>Nº de inscrição</th>
                        <th>Data</th>
                        <th>Nome</th>
                        <th>Cpf</th>
                        <th>Rg</th>
                        <th>Telefone</th>
                        <th>Email</th>
                        <th>Cargo desejado</th>
                        <th>Outros cargos de interesse</th>
                        <th>Situação</th>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    <?php endif; ?>

</section>

<script>

    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/registrations';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>