<section class="content">
    <?php if ($registration): ?>
        <div class="row">
            <div class="col-md-3">
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        <?php $person = $registration->getPerson(); ?>
                        <h2 class="text-center"><?php echo $person->getPersonFirstName() . " " . $person->getPersonLastName() ?></h2>
                        <h2 class="text-muted text-center">
                            <small>Nº de inscrição: <?php echo $registration->getRegistrationNumber(); ?></small>
                        </h2>

                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b>Data de nascimento: </b> <a class="pull-right"><?php echo $person->getPersonBirthday(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>CPF:</b> <a class="pull-right"><?php echo $person->getPersonCpf(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>RG:</b> <a class="pull-right"><?php echo $person->getPersonRg(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>Email:</b> <a class="pull-right"><?php echo $person->getPersonEmail(); ?></a>
                            </li>
                            <li class="list-group-item">
                                <b>Telefone:</b> <a class="pull-right"><?php echo $person->getPersonPhone(); ?></a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.box-body -->
                </div>
                <div class="box box-primary">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <a target="_blank" href="/docs/<?php echo $recruitment->getRecruitmentPublicNotice(); ?>" class="btn btn-flat btn-primary btn-block"><b>Edital</b></a>
                        <a target="_blank" href="https://www.facebook.com/cats.familia" class="btn btn-block btn-social btn-facebook">
                            <i class="fa fa-facebook"></i> Nos encontre no Facebook
                        </a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>

            <div class="col-md-9">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#status" data-toggle="tab" aria-expanded="true">Situação do Candidato</a></li>
                        <li class=""><a href="#edit" data-toggle="tab" aria-expanded="false">Editar Dados</a></li>
                    </ul>
                    <div class="tab-content">
                        <!--PAINEL DE STATUS DO CANDIDATO-->
                        <?php
                        $prev = "green-active";
                        $next = "primary";
                        $blockNumber = 1;
                        ?>
                        <!--
                            Os blocos: Confirmação; Pré-Entrevista; e Entrevista, contém
                            tratamento para substituir a informação de "a confirmação será realizada nos dias..."
                            por "confirmação realizada no dia..." caso o candidato seja confirmado.
                        -->
                        <div class="tab-pane active" id="status">
                            <div class="row">
                                <div class="col-lg-12 col-xs-12">
                                    Olá candidato. Esta é a área de acompanhamento de sua inscrição. Nela você encontrará todas as informações sobre o processo seletivo: 
                                    etapas, requisitos, edital e muito mais. Recomendamos sempre que você leia o edital e caso tenha dúvidas entre em contato conosco pela 
                                    nossa página do facebook.
                                </div>
                            </div>
                            <hr>

                            <div class="row">
                                <div class="col-lg-6 col-xs-12">                      
                                    <div class="small-box bg-<?php echo $blockStatus['registration'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Inscrição</h3>
                                            <p>Sua inscrição foi realizada com sucesso.</p>
                                            <span>
                                                <?php echo $recruitment->getSubscriptionDescription(); ?>
                                            </span>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa-edit"></i>
                                            <?php echo $blockNumber++; ?>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($blockStatus['interview'] || $blockStatus['interviewWaitingList']) : ?>
                                    <div class="col-lg-6 col-xs-12">
                                        <div class="small-box 
                                             bg-<?php echo $blockStatus['interview'] ? $prev : $next; ?>">
                                            <div class="inner">
                                                <h3>Entrevista</h3>
                                                <p>
                                                    <?php if ($blockStatus['interviewed']) : ?>
                                                        Sua entrevista foi realizada com sucesso.    
                                                    <?php elseif ($blockStatus['interview']) : ?>
                                                        Sua entrevista foi agendada para o dia 
                                                            <?php echo $interviewDate; ?>. 
                                                    <?php elseif ($blockStatus['interviewWaitingList']) : ?>
                                                        Você está na lista de espera.
                                                    <?php else : ?>
                                                        Sua entrevista ainda não foi agendada.
                                                    <?php endif; ?>
                                                </p>
                                            </div>
                                            <div class="icon">
                                                <i class="fa fa-commenting-o"></i>
                                                <?php echo $blockNumber++; ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>

                            <div class="row">
                                <?php if ($blockStatus['testClass'] || $blockStatus['testClassWaitingList']) : ?>
                                    <div class="col-lg-6 col-xs-12">
                                        <div class="small-box 
                                             bg-<?php echo $blockStatus['testClass'] ? $prev : $next; ?>">
                                            <div class="inner">
                                                <h3>Aula Teste</h3>
                                                <p>
                                                    <?php if ($blockStatus['testClassDone']) : ?>
                                                        Sua aula teste foi realizada com sucesso.  
                                                    <?php elseif ($blockStatus['testClassWaitingList']) : ?>
                                                        Você está na lista de espera.
                                                    <?php else : ?>
                                                        Sua aula teste foi agendada para o dia 
                                                            <?php echo $testClassDate; ?>
                                                    <?php endif; ?>
                                                    <span>
                                                        <?php echo $recruitment->getInterviewDescription(); ?>
                                                    </span>
                                                </p>
                                            </div>
                                            <div class="icon">
                                                <i class="fa fa-commenting-o"></i>
                                                <?php echo $blockNumber++; ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="col-lg-6 col-xs-12">
                                    <?php 
                                        if ($blockStatus['result'] && !$blockStatus['resultApproved']) {
                                            $prev = "red-active";                                         
                                        }
                                    ?>
                                    <div class="small-box bg-<?php echo $blockStatus['result'] ? $prev : $next; ?>">
                                        <div class="inner">
                                            <h3>Resultado Final </h3>
                                            <p>
                                                <?php if ($blockStatus['result']): ?>
                                                    <?php if ($blockStatus['resultApproved']): ?>
                                                        Você foi aprovado.
                                                    <?php else : ?>
                                                        Você não foi aprovado.
                                                    <?php endif; ?>      
                                                <?php else: ?>
                                                    O resultado ainda não foi divulgado.
                                                <?php endif; ?>
                                                <span>
                                                    <?php echo $recruitment->getResultDescription(); ?>
                                                </span>
                                            </p>
                                        </div>
                                        <div class="icon">
                                            <i class="fa fa fa-gavel"></i>
                                            <?php echo $blockNumber++; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Edição dos dados-->
                        <div class="tab-pane" id="edit">
                            <?php if ($this->form !== null): ?>
                                <?php $form->prepare(); ?>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <?php echo $this->form()->openTag($form); ?>
                                        <?php
                                        $registration = $form->get('registration');
                                        $person = $registration->get('person');
                                        echo $this->partial('person/template', array(
                                            'form' => $person,
                                        ));
                                        echo $this->partial('disclosure/template', array(
                                            'form' => $registration,
                                        ));

                                        ?>

                                        <?php echo $this->formHidden($form->get('registrationCsrf')); ?>

                                        <div class="col-xs-12 col-md-12">
                                            <div class="form-group">
                                                <?php echo $this->formRow($form->get('registrationConsent')->setAttribute('checked', true)); ?>
                                            </div>
                                        </div>
                                        <br>
                                        <div class="col-xs-12 col-md-12">
                                            <?php echo $this->formRow($form->get('submit')->setValue('Atualizar')); ?>
                                        </div>
                                        <?php echo $this->form()->closeTag(); ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
        <?php else: ?>
            <h3 class="text-center">Erro inesperado, por favor, entre em contato com o administrador do sistema.</h3>
        <?php endif; ?>
    </div>
</section>

<script>
    appConfig = (function () {
        var scriptSrc = 'app/pages/recruitment/registration/candidate';
        return {
            getScriptSrc: function () {
                return scriptSrc;
            }
        };
    })();
</script>